### PR TITLE
rocling 22 ingestion

### PR DESCRIPTION
**Pull request by xinru1414**

### CODE REVIEW

**Review by mjpost — COMMENTED** [review]
A lot of these papers are in Chinese. Can you add the appropriate `<language>` tag?

**Comment by xinru1414** [comment]
@mjpost re adding the `<language>` tag -- 1) How can we tell which paper is written in which language? I checked bib files but can't find info there. Are we manually checking each pdf? 2) What code do we use for traditional Chinese (opposed to simplified Chinese, for which we use `zh` I believe)?

**Comment by mjpost** [comment]
I believe it's zho but check other rocling files. you'll have to just check manually it shouldn't take long.

**Comment by davidweichiang** [comment]
That seems like mixing two different language coding systems (ISO 639-2 and 639-3).

**Comment by mjpost** [comment]
Here are all the language codes we've used. 

```
<language>de-DE</language>
<language>deu</language>
<language>eng</language>
<language>fra</language>
<language>no-NO</language>
<language>pt-BR</language>
<language>zho</language>
```

It seems we have a mix of BCP-47 and ISO 639-2/3, but all of our ISO codes are identical between the two standards.

I do think it would be good to settle on one standard, and I think BCP-47 is the recommended one. I don't know if these papers are zh-CN, zh-HK, or zh-TW.

Unless someone can inform us, let's just use "zh" here, and then convert the others in a separate PR?

**Comment by davidweichiang** [comment]
I'm not familiar with BCP-47 but if we're using zho for Chinese already then I would think we should stick with zho.

**Review by mjpost — APPROVED** [review]

**Pull request merged**
