### PR TITLE
fixed C18 abstracts

### PR DESCRIPTION
**Pull request by mjpost**
Adds incomplete abstracts from C18.xml (#290).

@davidweichiang or @danielgildea, how can I add the `<tex-mode>` tags? Do I need to modify `anthologize/latex.py` in ACLPUB, or is there an easier way?

### CODE REVIEW

**Comment by davidweichiang** [comment]
Did you convert this from BibTeX using anthologize? I thought it should have converted the math for you.

**Comment by davidweichiang** [comment]
Long term, it seems to me that I should modify `normalize_xml.py` to keep it in sync with `anthologize` (currently `anthologize` is more up-to-date), and also incorporate `protect.py` for fixed-casing as well. I will create an issue for this.

**Comment by mjpost** [comment]
Sorry, I spent some time looking at this last night. I am trying to apply it to an existing XML file (i.e., not from the original BibTeX). What I want is basically a `protect.py` but for `tex-math` instead of `fixed-case`. I spent some time trying to factor this out of ACLPUB's `latex.py`, but it seems that your `normalize_anth.py` is what I want.

Since some data comes from non-START and non-ACLPUB sources, I wonder if we should move all normalization and so on to work from the XML, instead of the LaTeX. That is, the model would be (a) ingest BibTeX to XML (b) apply all of our normalization procedures.

**Comment by davidweichiang** [comment]
Agreed -- I think that's pretty much the gist of #293.

**Pull request merged**
