### PR TITLE
Replace deadname with Jasmijn

### PR DESCRIPTION
**Pull request by bastings**
Affected: D17, D19, L14, N18, P19, W17, W18
Thanks!

### CODE REVIEW

**Comment by mbollmann** [comment]
Thanks for the PR! Why did you remove videos and attachments from some papers?

**Comment by bastings** [comment]
I removed 1 slide deck since the slides also contain my deadname and I cannot update these particular slides. (I do provide a new slide deck on my website though, with correct name, so they are still available to the public.)

Regarding the 2 video links: I would really prefer the *actual videos* to be removed on Vimeo (since they misrepresent me), but as a first step I removed the link to those. I really hope this is ok. :-) Thanks for the quick response.

**Comment by bastings** [comment]
Thanks for the quick response! :-)

I removed 1 slide deck since the slides also contain my deadname and I cannot update these particular slides (I don't have the source anymore). However, I provide a replacement slide deck on my website, with correct name, so they are still available to the public. 

Regarding the 2 video links: I've followed up over e-mail.

**Comment by mbollmann** [comment]
Cool! I'd let @mjpost approve & merge this since he's the one who has to replace the PDFs (in #883) as well.

For the attachment, if we remove the link, we should also physically remove the file from the server, so we don't accumulate more "dead files" on there. Again, that's something @mjpost would have to do, so I'll let him weigh in on this. :)

**Comment by mbollmann** [comment]
Or maybe we could also archive your replacement slide deck on the Anthology, if you're okay with that? We don't have a concept of "revisions for attachments", but maybe replacing an attachment would be preferable to removing it? Not sure here, just a thought.

**Comment by bastings** [comment]
Thanks Marcel!

Regarding the attachment (the accompanying slides): it has my preference to delete the file, since I don't have the source anymore and cannot revise it, and for me to host a completely redone slide deck on my website. Then I can also easily make edits to it without having to cause more work here. 
If that's not acceptable somehow then I could provide an alternative PDF some time soon, once all the slides have been redone.

**Comment by bastings** [comment]
Thank you Matt!

**Pull request merged**
