### PR TITLE
Update 2024.eacl.xml for the paper with anthology ID: 2024.eacl-long.117

### PR DESCRIPTION
**Pull request by ipavlopoulos**
The software does not exist and the link is broken. The software should not exist, because the paper shares a GitHub repository. But a video should exist.

Removed the link to the attachment.

### CODE REVIEW

**Comment by mjpost** [comment]
It seems that no attachments exist for EACL 2024. @anthology-assist, can you please check if these were inadvertently not uploaded?

**Comment by anthology-assist** [comment]
Looks like the attachments were not uploaded. But it also seems like  some attachments shouldn't be uploaded (like this PR mentioned). Shall we remove all attachment element for EACL?

**Comment by mjpost** [comment]
Authors are free to upload data when they submit their papers, independent of whether they have a github link in their paper. In fact doing so serves an archival purpose since the Github link may disappear. But it's worrisome that we created the link to the attachment when it was not in fact there. That shouldn't be possible from the ingestion script.

I would also check with the EACL pub chairs to see if these submissions were inadvertently lost.

**Comment by mjpost** [comment]
Videos will be added soon in #3296.

**Pull request closed without merging**
