### PR TITLE
Automatic projection of curly braces from BibTeX to XML

### PR DESCRIPTION
**Pull request by davidweichiang**
Automatic projection of curly braces in BibTeX entries (for protecting fixed-case words) into XML as <fixed-case> tags.

- `{\cmd ...}` does _not_ protect case, and even braces within don't protect case (this is how BibTeX apparently works)
- `{$...$}` is not tagged, because I figure the conversion back to BibTeX can add the curly braces easily
- In `\cmd{...}`, the argument is not tagged, because I didn't see any cases where it was clearly intended to protect case.

The script asks for manual intervention when the XML has been changed from the BibTeX; I'll make those changes later.

To protect a word like `English`, one is supposed to write `{E}nglish`, but a lot of people (myself included) write `{English}`. The reason is that if a bib style wanted to make the title all-caps, the `nglish` should not be protected. It would be very easy to modify the script to interpret `{English}` as `{E}nglish`, but there are some edge cases, like a system named `{fokas}` where the lowercasing apparently _should_ be protected. So the script currently follows the curly braces strictly, but let me know if you want the other behavior.

### CODE REVIEW

**Comment by mjpost** [comment]
Cool! Do we know if the Rails app will properly handle the `<fixed-case>` tags? If not, we should merge this against `static-rewrite` instead. (I'm hoping we'll be able to flip the switch this month).

**Comment by davidweichiang** [comment]
No, I can’t imagine the current conversion to HTML knows about it. I would hope that it would just delete the tag or pass it through (and get deleted by the browser), but unfortunately based on an example you once pointed out, I kind of suspect that the current version cuts a field off at the first sight of any tag.

How do I change the PR so it applies to static-rewrite instead?

**Comment by mjpost** [comment]
You can click "Edit" to the right of the title on [this page](https://github.com/acl-org/acl-anthology/pull/161), and change the branch your issuing against. I could do it myself but it warned me of something that it seemed to me you're more qualified to judge.

**Comment by mjpost** [comment]
(I think @danielgildea or someone may have fixed that error, but I am not sure and don't know the tech well enough to test, and I don't think waiting a little bit longer will hurt too much)

**Comment by davidweichiang** [comment]
I just noticed @danielgildea's https://github.com/acl-org/acl-anthology/commit/443b39b28a4552704c66f7ab77145df056ef1e94 ; this is slightly incompatible because it uses the XML tag `<fixed-case>` instead of curly braces.

**Comment by mjpost** [comment]
I think we decided to go full XML.

@mbollmann I think this merge's in your hands.

**Comment by mbollmann** [comment]
> I just noticed @danielgildea's [443b39b](https://github.com/acl-org/acl-anthology/commit/443b39b28a4552704c66f7ab77145df056ef1e94) ; this is slightly incompatible because it uses the XML tag `<fixed-case>` instead of curly braces.

That script exports from the SQL database though, which is a route we wouldn't go anymore with the static rewrite.

I'll look over the changes once more later and then merge.

**Comment by davidweichiang** [comment]
After selecting a new branch, there are a bunch of commits that came along for the ride. Is it too late for me to rebase?

**Comment by mbollmann** [comment]
Let me merge in the recent changes on the master branch first, then the PR will probably look a lot cleaner.

**Comment by davidweichiang** [comment]
If you prefer, I can just redo the whole PR.

**Comment by mbollmann** [comment]
I think you can edit the target branch back to master and then back to static-rewrite again, and it should update the changes. Can you try that?

**Comment by mbollmann** [comment]
Just did, looking good now. :)

**Pull request merged**
