### PR TITLE
add video links for HumEval workshop at EACL

### PR DESCRIPTION
**Pull request by Shimorina**
Hello,

This PR adds video links to some papers presented as talks at [HumEval 2021](https://aclanthology.org/volumes/2021.humeval-1/). 

Here is the link to all the original recordings:
https://drive.google.com/file/d/1gLEyL7sq674fioQ9__4xsmyk9h0OBKw9/view?usp=sharing

### CODE REVIEW

**Comment by mjpost** [comment]
The link appears to be a link to a single video. Can you link to a complete folder?

**Comment by Shimorina** [comment]
Apologies, here's the right link: https://drive.google.com/drive/folders/1Fdp7ve2MSH4u1SaMhkoiJV65CtViFuSr?usp=sharing

**Comment by Shimorina** [comment]
Hello,

Wouldn't you mind giving a time estimate for merging this PR? Many thanks!!

**Comment by xinru1414** [comment]
@Shimorina I just noticed that the google drive there are 9 videos in total, however only 7 video links were ingested. The two missing videos are invited talks. Is this correct?

**Comment by mjpost** [comment]
We don’t have a way to represent the keynote yet, hopefully we will soon. I think we can just put them on the server for now.

**Review by xinru1414 — APPROVED** [review]
LGTM

**Comment by Shimorina** [comment]
> 
> 
> @Shimorina I just noticed that there are 9 videos in total on the shared google drive, however only 7 video links were ingested. The two missing videos are invited talks. Is this correct?

Yes, that's correct!

Thank you!

**Pull request merged**
