### PR TITLE
Link to vimeo videos (see #167)

### PR DESCRIPTION
**Pull request by akoehn**
These are the ones that could be automatically linked.  I checked them
and removed two incorrect automatic matches.

The videos that could not automatically be linked as of now can be included later.

### CODE REVIEW

**Comment by akoehn** [comment]
If you want to verify the data: the mapping I used is attached.
[vimeo_videos.tar.gz](https://github.com/acl-org/acl-anthology/files/3010377/vimeo_videos.tar.gz)

**Comment by mjpost** [comment]
This is awesome. I'll spot check a few of these later today and then merge it.

**Comment by mjpost** [comment]
I haven't had a chance to do spot checks yet and may not have time this weekend. If someone else manages to do so, or you're confident of it, we can merge. Sorry for the delay and thanks for doing this!

BTW, Weyond has been uploading more videos that they're salvaging from hard drives that were lost in the techtalks.tv crash. So we should be able to run your script and get more hits in the near future.

**Comment by akoehn** [comment]
I checked the CSV list my script exported and now also spot-checked the links generated on the anthology website, which I built locally to see that the XML export works as expected.  I think it is safe to merge.

**Comment by mjpost** [comment]
Thank you!

**Pull request merged**
