### PR TITLE
A few name corrections

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by davidweichiang** [comment]
Could you add these to name_variants.yaml?

**Comment by mjpost** [comment]
Just "dePaiva", right? Not the incorrectly-split name?

**Comment by davidweichiang** [comment]
Do we think it was split that way in START? If so, yes, I think we should include it in name_variants.yaml.

**Comment by mjpost** [comment]
No, it came that way from EasyChair (from her report). Same thing I guess, I'll add it.

**Pull request merged**
