### PR TITLE
eamt-2022-reingestion

### PR DESCRIPTION
**Pull request by xinru1414**

### CODE REVIEW

**Comment by xinru1414** [comment]
@BramVanroy Since this is a re-ingestion, if the full archive (the zip file) is updated (meaning that the page element in the bib file in the bib folder for each paper is updated to reflect the page number change), then the xml would be correct. I thought that's the case but apparently the full archive isn't updated.

Could you clarify the new pages for each paper (that needs to be updated)? I can manually update them. Or if you prefer, you can update the full archive.

Thanks!

**Comment by BramVanroy** [comment]
@xinru1414 Thank you for your patience! I've uploaded the version [here](https://lt3.ugent.be/media/uploads/eamt2022/eamt2022_data_v2.tgz). I hope that everything is okay now.

Note: I cannot find the root of [this issue](https://github.com/acl-org/acl-anthology/pull/1976) so I cannot solve it from my end. I think that during processing of the proceedings on your end (?) the `ł` cuts off the rest of the name or something. In the metadata in my files I always find the correct full name `Mikołaj`. So after processing, you may need to manually change this person's name again.

**Comment by xinru1414** [comment]
@BramVanroy The URLs should stay the same since the anthology ids didn't change.

**Review by mjpost — APPROVED** [review]
LGTM

**Pull request merged**
