### PR TITLE
Ingested MT Summit 2011.

### PR DESCRIPTION
**Pull request by davidstap**
See https://aclanthology.org/www.mt-archive.info/10/MTS-2011-TOC.htm for original.

### CODE REVIEW

**Comment by xinru1414** [comment]
- Should https://preview.aclanthology.org/ingest-mtsummit-2011/volumes/2011.mtsummit-papers/, https://preview.aclanthology.org/ingest-mtsummit-2011/volumes/2011.mtsummit-plenaries/, https://preview.aclanthology.org/ingest-mtsummit-2011/volumes/2011.mtsummit-systems/ and https://preview.aclanthology.org/ingest-mtsummit-2011/volumes/2011.mtsummit-tutorials/ be one page?
- `plenaries` --> `keynotes`?
- `Message from the Program Committee Chair:` is ingested as `Proceedings of Machine Translation Summit XIII: Plenaries` on the `plenaries` page

**Comment by mjpost** [comment]
All right, let’s get this finished up!

* I think the volume division is good
* It seems the last paper from the workshop is missing? There’s no “Example-based Translation of Japanese Functional Expressions utilizing Semantic Equivalence Classes”

**Comment by davidstap** [comment]
* Let's keep `plenaries` instead of `keynotes` for consistency with other MT Summit volumes, even though in this case there are only keynotes?
* I treated `Message from the President ...` as Frontmatter, which is why it is listed that way. Makes sense or not? (`Message from the Program Committee Chair` is in the same PDF)
* `Tutorials` is the fourth link on the original website. For consistency with other MT Summit volumes, I created a separate `tutorials` volume. 
* The `4th Workshop on Patent Translation` papers were listed in the `wpt` volume. The last paper was indeed missing (thanks for spotting @mjpost), I have added this one now.

@xinru1414 I hope this clears things up, let me know :)

**Review by xinru1414 — APPROVED** [review]
Everything looks good!

**Pull request merged**
