### PR TITLE
expand author name: L. E. Dostert -> Léon Dostert

### PR DESCRIPTION
**Pull request by nschneid**
merges https://aclanthology.org/people/l/l-e-dostert/ with https://aclanthology.org/people/l/leon-dostert/

### CODE REVIEW

**Review by anthology-assist — APPROVED** [review]
LGTM

**Review by mjpost — DISMISSED** [review]

**Review by mjpost — COMMENTED** [review]
This is nice, but we typically take the PDF name format as canonical. I think the appropriate way to do this would be to list the expanded name as a variant in name_variants.yml.

**Comment by nschneid** [comment]
The full name appears in the PDF for the 1957 ones.

**Comment by mjpost** [comment]
Ah, I only checked the first one. So we'd need to revert that one, then add a name variants entry.

**Comment by anthology-assist** [comment]
To be clear: we'd like to use `Leon Dostert` https://aclanthology.org/people/l/leon-dostert/ and add `L. E. Dostert` https://aclanthology.org/people/l/l-e-dostert/ as  a name variant. Correct?

**Comment by mjpost** [comment]
1. Metadata should match what's on PDFs (check each of them, make corrections here as needed)
2. Merge names making Léon Dostert (note the diacritic) the canonical
3. Merge into March corrections
4. I will then complete the PR

**Comment by mjpost** [comment]
Merged into #3107

**Pull request closed without merging**
