### PR TITLE
germeval 2022 ingestion (merge 9/5)

### PR DESCRIPTION
**Pull request by xinru1414**

### CODE REVIEW

**Comment by salarmohtaj** [comment]
Hi @xinru1414,
I found two errors in the names in the proceedings and the overview paper. Is it still possible to resolve the issue?
I am sorry for the inconvenience.

**Comment by akoehn** [comment]
@salarmohtaj sure, it is not yet merged (and we could also change it afterwards). But it is only possible to fix the errors if you tell us what they are ;-)

**Comment by salarmohtaj** [comment]
@akoehn great, thank you!
Actually, our names as the editors of the proceeding and the author of the overview paper (Overview of the GermEval 2022 Shared Task ...) are mixed up. Right now, it's like one name instead of three separate names. I replaced the fixed BibTex files on the Google drive. Should I share the link to the Google drive directory, here?
There is also an additional bracket in the title of the proceeding ({Proceedings of the GermEval 2022 Workshop on Text ...})

**Comment by salarmohtaj** [comment]
thank you so much. The editor names in the proceedings seem perfect now.
Can you kindly replace the author tag for the overview paper <paper id="1"> (Overview of the GermEval 2022 Shared Task ...) with the following tags, please?
Everything else seems good. 

<author><first>Salar</first><last>Mohtaj</last></author>
<author><first>Babak</first><last>Naderi</last></author>
<author><first>Sebastian</first><last>Möller</last></author>

**Review by mjpost — APPROVED** [review]

**Pull request merged**
