### PR TITLE
Restructure venue YAML files

### PR DESCRIPTION
**Pull request by mbollmann**
This PR addresses #527. Concretely, it reduces our current four YAML files to two:

- `venues.yaml` contains a dict of all venues:
  - The key is the **new-style ID** (e.g. `iwclul`). For old venues, I automatically generated a valid key from the venue's acronym, which means ingesting new proceedings with IDs `acl`, `emnlp` etc. will automatically work.
  - A venue can have an entry `oldstyle_letter`, which will associate old-style IDs beginning with this letter with that venue.
  - A venue can have a `joint` field, indicating that *all* volumes belonging to that venue should *also* be registered with the given other volume(s). I envision this to be mainly useful for workshops, which currently need to be associated with the `WS` venue to appear correctly on the website. **This eliminates the need to add a "joint" mapping for every single proceedings of a workshop.**

- `events.yaml` contains a dict with further information for events/volumes:
  - The key is a **volume ID** (e.g. `W97-01` or `2020.iwclul-1`).
  - This maps to a dict whose only entry currently is `joint`, giving the (additional) venues that this particular event should be linked with.
  - I made this into a dict to support adding other volume-level information in the future, most notably [short names for events, as discussed previously](https://github.com/acl-org/acl-anthology/issues/149#issuecomment-467044062).

### CODE REVIEW

**Comment by mjpost** [comment]
This is really great! It will be nice to have this knot of files simplified in this way.

I have one thought about the events file. The main use of joint mapping is for a specific workshop (e.g. 2019.wmt) to indicate which conference it was colocated with (e.g., 2019.acl).  In your proposal, we accomplish this, not with (child event: parent event) links, but with (child volume: parent venue) links. Conceptually, this is a little irksome, though on the positive side, it gives us finer-grained control, since it retains the possibility that volumes from an event could be associated with different venues. And practically, it would be much more succinct if the links were from parent to child, e.g., 

```yaml
P19:
  joint: [W19-33, W19-34, W19-35, ... W19-54]
```

This would require the keys to be events, of course. This might not be worth the trouble, but I thought I'd bring it up.

**Comment by mbollmann** [comment]
This wouldn't be too much trouble to implement, I think. One possible downside is that it requires us to introduce yet another YAML file if we want to implement the "shortname" idea, as that [should be tied to volumes, not events](https://github.com/acl-org/acl-anthology/issues/149#issuecomment-471607580). Or have a hierarchy, like:

```yaml
P19:
  joint: [W19-33, W19-34, W19-35, ... W19-54]
  shortnames:
    P19-1: "ACL 2019"
    P19-2: "ACL 2019 SRW"
    ...
```

But that's maybe a little too restrictive if we want to add further volume-level info?

**Comment by mjpost** [comment]
My thought for short names was to put them in the XML, as a `<shortbooktitle>` tag, next to `<title>` in the `<meta>` block.

We would then effectively have three places for information:

- Venues: `data/yaml/venues.yaml`
- Events: `data/yaml/events.yaml`
- Volumes, grouped into collections: `data/xml/*.xml`

**Comment by mbollmann** [comment]
> My thought for short names was to put them in the XML, as a `<shortbooktitle>` tag, next to `<title>` in the `<meta>` block.

That makes a lot of sense, and if that was suggested before, I must've missed it.

The more I think about your proposal, the more I like it conceptually; but I don't think it's sufficient to represent the proceedings volumes we currently have.

Take [W18-49](https://www.aclweb.org/anthology/volumes/W18-49/) for example, which is associated with COLING, LAW, MWE, and WS. Even if we mapped it to new-style IDs and called it `2018.law-1`, this wouldn't work – where would the MWE tag come from, if not from an explicit association of this particular *volume* with the venue?

**Comment by mjpost** [comment]
Hmm. If I understand, there are actually two types of events, that we have been conflating:

- colocated: events that have separate volumes that were presented in the same physical place (e.g., 2019.wmt was colocated with 2019.acl)
- joint: a single event (and its volumes) that have multiple names

Furthermore, there is the problem that in the old-style IDs, for all "W" events, there is no distinction between the event and its volume (e.g., W18-49 is both the event and the volume). This has been problematic in the past—for example, with WMT, which is a single "W" event with three volumes in 2019: W19-5{2,3,4}—but will be fixed with our new-style IDs.

What if we just explicitly distinguish colocated from joint events in the `events.yaml` file? The keys are anything that could be an event (straightforward in 2020+, a bit more complicated prior to that, but still not too difficult to lay out) :

```
P19:
  colocated: [W19-33, W19-34, W19-35, ... W19-54]
W18-49:
  joint: [COLING,LAW,MWE]
```

Here, with the old-style ID, the default event association is implicit ("WS" for W18-49, "ACL" for P19). Valid values for "colocated" are volumes, and for "joint", venues.

**Comment by mbollmann** [comment]
Do we gain anything by making this distinction? I'm not sure what we could do with it, and wonder if it would just introduce unnecessary complexity. Essentially, `W18-49` would have its own key to associate LAW and MWE with it, but would also have to appear under `C18: colocated: ...`, no?

And to be pedantic, a proceedings volume can't really be colocated with an event, another event is :)

(I might have to think about this a bit more.)

**Comment by mjpost** [comment]
My thinking is that separating `joint` and `colocated` would answer this question:

> Take W18-49 for example, which is associated with COLING, LAW, MWE, and WS. Even if we mapped it to new-style IDs and called it 2018.law-1, this wouldn't work – where would the MWE tag come from, if not from an explicit association of this particular volume with the venue?

The `joint` keyword would provide these names, which would all function as an equivalence class.

For `colocated`, the keyword would point from parent even to children events, and its function would be to cause those child events to appear on the parent event page, e.g., https://www.aclweb.org/anthology/events/acl-2019/. We would not need backpointers from the child event to the parent (since workshop pages don't display their parent conference).

**Comment by mbollmann** [comment]
> For `colocated`, the keyword would point from parent even to children events, and its function would be to cause those child events to appear on the parent event page

Do you propose to change the way the website uses this information?

You said earlier that we were conflating two types of events, but from a software engineering point of view, we don't really have any concept of "event" right now -- we only have venues that are attached to volumes, and "event pages" are simply a view of all volumes tagged with a given venue in a particular year. Therefore, right now, `C18` having `colocated: W18-49` would give the exact same result as `W18-49` having `joint: COLING`. Hence my confusion.

So what I'd like to understand is, are you proposing that we should introduce an explicit concept of "event" so that we can make this colocated-vs.-joint distinction, and integrate it into the website? Or is it more about succinctness and conceptual ease of adding new volumes in the YAML in the future?

**Comment by mjpost** [comment]
My original proposal was based on succinctness, i.e.,

```yaml
2019.acl:
  colocated: [W19-01 W19-02 ...]
```

is more concise than:

```yaml
W19-01:
  joint: acl
W19-02:
  joint: acl
...
```

but I now understand the problem, which is that we don't really have a notion of an event like `2019.acl`---at least not explicitly, so there wouldn't be a way in my proposal for W19-01, etc. to also indicate that they're joint with, saw MWE (or whatever).

### Solution 1: Defining events (verdict: probably not worth it)
One solution would be for us to actually implement the idea of an event. With few exceptions, I think we could say that an event is the same as a collection ID, e.g., "2020.acl" is an event.

However, I suspect that the exception list here would grow. There are many times where I had to assign multiple workshop IDs to an event, since we had no more top-level letters for them. [NoDaLiDa](https://www.aclweb.org/anthology/venues/nodalida/) is one—a larger conference that had no common identifier. 

Identifying all of these would be a big manual effort that would also (likely) introduce code complications. And maybe this solution is needless work, anyway.

### Solution 2: Get rid of `events.yaml` entirely (verdict: TBD)
Another solution that would capture the succinctness would be to get rid of `events.yaml` entirely, and just add the joint information to the `venues.yaml` file. For example,

```yaml
acl:
   acronym: ACL
   is_acl: duh
   is_toplevel: true
   name: Annual Meeting of the Association for Computational Linguistics
   oldstyle_letter: P
   joint:
      2020: [2020.wngt-1 ...]
      2019: [W19-01 W19-02 ...]
      2018: [W18-74 W18-75 ...]
```

Here, the year-level keys under `joint` are technically not necessary, but help keep things organized.

This is a bit more succinct in specifying joint events. However, it does conflate the relatively static information currently in `venues.yaml` with the dynamic data added at every ingestion.

### Solution 3: Solution 2, but split out joint information into `joint.yaml`

This would keep Solution 2 above, renaming `events.yaml` to `joint.yaml`, with data as follows:

```yaml
acl:
   2020: [2020.wngt-1 ...]
   2019: [W19-01 W19-02 ...]
   2018: [W18-74 W18-75 ...]
```

The advantage is that `venues.yaml` could stay tidier and just contain venue meta-information, while `joint.yaml` would have year-to-year information.

So I guess this is just your proposal, but (1) mapping from (venue → volume) instead of (volume → venue), and (2) optionally renaming the file (we could also just keep this named `events.yaml` but `joint.yaml` seems more on-topic to me).

### Solution 4: Just keep it as you've proposed
If Solution 2 doesn't work, or introduces problems,

**Comment by mbollmann** [comment]
Yes, Solution 1 might potentially introduce complications, and my main issue with it is that it's unclear to me what value we would gain from it.

Solutions 2/3/4 are kinda equivalent from an implementation perspective, it's mainly a matter of which (logical) perspective we want to take:

1. Venues are organizing/hosting events that publish proceedings (map *venue → volume*); or
2. Proceedings indicate with venue(s) they belong to/are affiliated with (map *volume → venue*).

The former is more succinct if we consider, e.g., adding a bunch of ACL workshops – just list all the workshop volumes under `acl:`. You can also quickly see at a glance which volumes are associated with a venue. However, if a workshop has multiple affiliations, like the W18-49 example from above, it would have to be listed multiple times in different places in the YAML file – that's a potential drawback.

My original thought with the latter was that it's more flexible if we want to add other volume-level information in the future. However, you made a good point that info like "short titles" can be added to the XML directly, so I don't know if we'll ever actually need this.

- - - 

If we don't anticipate to use the flexibility of Solution 4, maybe Solution 2/3 is more practical since it is easier to work with when ingesting new workshops?

**Comment by mjpost** [comment]
The main reason that the current (volume → venue) mapping (in `venues_joint_map.yaml`) is so human-unfriendly is that most of the current volume names are so opaque. This will no longer be the case with the new IDs, so it may be that we could just stick with it.

That said, I think I would prefer Solution 3, if you are okay with implementing it. I agree there will be some redundancy when there are multiple shared venues, but the information I usually want is venue-level associations. And it is easier, I think, to quickly get (volume → venue) associations from the (venue → volume) format, from the command line, than vice versa.

Should we need the flexibility later, it's a quick conversion and a bit of code change to move to 4.

**Comment by mbollmann** [comment]
No, that should be easy to change.

**Comment by mbollmann** [comment]
I made the dictionary substructure optional in the new YAML file now, since the way I see it, it has no practical purpose except for readability. That means all of these work now:

```yaml
icon:
- W14-51
- W15-59
- W16-63
- W17-75
icos: [W06-39]
ijcnlp:
  2009: [P09-1, P09-2, P09-3, P09-4, P09-5]
  2015: [P15-1, P15-2, P15-3, P15-4, P15-5]
```

If you think we should have a stricter syntax, I can also unify that, though.

**Comment by mjpost** [comment]
This looks fantastic!

**Pull request merged**
