### PR TITLE
2724 look at dois for frontmatter

### PR DESCRIPTION
**Pull request by yufei118liu**
Allow assigning dois to frontmatter [bin/generate_crossref_doi_metadata.py](https://github.com/acl-org/acl-anthology/blob/2724-look-at-dois-for-frontmatter/bin/generate_crossref_doi_metadata.py)

### CODE REVIEW

**Comment by yufei118liu** [comment]
Solved #2724

**Comment by mjpost** [comment]
Oh, fantastic! This is a long-standing issue. I'll review shortly.

**Comment by mjpost** [comment]
The only thing I need to do is determine if this is *correct*. I was not aware, for example, that we already generate complete-volume DOIs (e.g., this is defined: https://doi.org/10.18653/v1/2024.acl-long), because we do not display them. So a related issue is that we need to add these to the `add_dois.py` script so that they are present in the XML.

**Comment by mjpost** [comment]
Okay, this looks good now, and I'm merging it. Here are a few changes I made:
* We were missing the "Front Matter" title from the front matter in the DOI
* We were already generating the DOI for the volume itself, but not displaying it on the volume page
* As a test, I uploaded 2024.acl-long

**Review by mjpost — APPROVED** [review]

**Pull request merged**
