### PR TITLE
Faster loading times

### PR DESCRIPTION
**Pull request by mbollmann**
This PR implements a bunch of changes to speed up instantiation of the Anthology class (re #835).

They're a mix of:
- delaying computations until the values are actually needed;
- general optimizations (using f-strings instead of `.format` gives a surprisingly large boost!);
- introducing a `fast_load` parameter to the Anthology class which skips some error checking and computes fewer information in the AnthologyIndex by default.

Here's a list of the most relevant commits and the effect on instantiation time as measured by `python -m timeit -n 2 -r 3 "from anthology import Anthology; Anthology(importdir='../data/')"`, additionally with `fast_load=True` from the commits that introduced it:

- 881e19c1 (master, before any changes)
  11.6 sec
- f9f8e3d1 Lazily infer URLs
  10.4 sec
- d3c69f67 f-strings everywhere
  8.46 sec
- e5a22878 Cache Anthology ID construction
  7.82 sec
- f9df8ab7 Replace re.sub with while-loop
  7.2 sec
- a39a7eef Refactor variant scoring and person ID sorting
  7.45 sec *(this one seems counterproductive but I still think it makes sense to refactor this; maybe I'll revisit why it makes things slower)*
- 13edbe94 Lazily render paper titles
  5.83 sec
- d3b7e980 Add fast_load option, disabling some error checking during load
  5.5 sec
- f9b88e15 Load id_to_used & coauthors lazily if fast_load=True
  4.34 sec

We should check carefully that nothing in the appearance/generation of the website changed, as I already had to make some fixes because of that.

### CODE REVIEW

**Comment by mbollmann** [comment]
Seeing some diffs regarding canonical names locally:

```
< <a href=/people/y/yujie-zhang/>Yujie Zhang</a>,
---
> <a href=/people/y/yujie-zhang/>Yujie Zhang (张玉洁)</a>,
```

...but strangely not on the preview branch. I'll turn this into a draft until I can better verify that nothing has functionally changed.

**Comment by mjpost** [comment]
I'm really excited about this but am buried under ingestions and other issues at the moment. I'll review when I can but if you're passing tests you could also merge without waiting for me.

**Comment by mbollmann** [comment]
Better be more careful with this one, I still have the author name differences to investigate. This would be a really good situation to have some proper unit tests for, as right now I'm basically relying on building and diffing the full website, which is a bit clunky to say the least...

**Comment by mbollmann** [comment]
This should be ready for review now. The only differences in the build that I could see, compared to the master branch, are:

- The generated YAML files often use IDs and pointers instead of repeating people's names; this is likely a consequence of introducing caching for name lookups *(...and is a good thing)*.
- The order of name variants on people's pages is different, likely as it previously wasn't sorted, so not guaranteed to be in a specific order *(...but it now is)*.

It would be great if others could test this locally, especially with regards to the instantiation times on this branch compared to `master`. (I currently only have one device that I can't reliably test with, since it had some overheating issues and I'm throttling CPU power...)

**Comment by mbollmann** [comment]
So, the temporary fix for this [is really ugly](https://github.com/acl-org/acl-anthology/commit/16e838b6f0f44a5c92bfa4d6adbe779b2ba4887d). In hindsight, storing local name variants in `PersonName` objects was a mistake from a coding perspective, but one that I also didn't anticipate at that time. We shouldn't see that latest commit as anything but a band-aid solution until a proper refactoring of how names work, which I really want to prioritize now.

**Review by mjpost — APPROVED** [review]
I haven’t looked at the code closely, but did run the script I mentioned earlier and found it produced the same result (except for the difference you explained).

**Pull request merged**
