### PR TITLE
Added frontmatter block for TAL

### PR DESCRIPTION
**Pull request by mjpost**
It seems frontmatter blocks are only created if there is a frontmatter PDF. We should always create the block, however, and only add the `<url>` tag inside the block if there is a PDF.

### CODE REVIEW

**Comment by mcandito** [comment]
Hi @mjpost , thanks for the manual addition

- in https://preview.aclanthology.org/tal-updates/2011.tal-1.0/ and all the other tal-xxx.0 pages,
the bibtex should be \@proceedings instead of \@article

- also note that the issues have a "subtitle", provided in XXX.0.bib files in the aclpub zip
For the issues number 1 of each year, the subtitle is "Varia"
but the issues number 2 and 3 of each year are thematic issues, and have variable subtitles.
Can you check the full title is taken from the XXX.0.bib files?

@proceedings{tal-2011-52-1,
  title = "Traitement Automatique des Langues}, Volume 52, Num{\'e}ro 1 : Varia [Varia]",
  editor = "Villemonte de la Clergerie, {\'E}ric and Daille, B{\'e}atrice and Lepage, Yves and Yvon, Fran{\c{c}}ois",
  publisher = "ATALA (Association pour le Traitement Automatique des Langues)",
  year = "2011",
  address = "France",
  url = "https://aclanthology.org/2011.tal-1.0",
}

- in https://preview.aclanthology.org/tal-updates/2011.tal-1.0/ :
The name of first author should be "Éric Villemont**e** de La Clergerie" instead of "Éric Villemont de La Clergerie"
(this is not a manual error but a bug I had noticed before, don't know why the e is erased)

- in https://preview.aclanthology.org/tal-updates/2018.tal-1.0/ :
The name of first author should be "Emmanuel Morin" instead of "Morin Emmanuel"

- for the other 4 issues, the .0/ pages seem missing
  - https://preview.aclanthology.org/tal-updates/2011.tal-2.0/
  - https://preview.aclanthology.org/tal-updates/2011.tal-3.0/
  - https://preview.aclanthology.org/tal-updates/2018.tal-2.0/
  - https://preview.aclanthology.org/tal-updates/2018.tal-3.0/
Is it on purpose because they contain a preface by the same people that are editors of the full issue?

**Comment by mjpost** [comment]
@mcandito TAL is a journal, correct? My understanding is that [`@article is used for journal papers](https://www.bibtex.com/e/entry-types/).

**Comment by mcandito** [comment]
@mjpost 
yes @article is for journal **papers**
but if you use @article for the **full issue** of a journal, you end up with redundant citations, like

"Éric Villemont de La Clergerie, Béatrice Daille, Yves Lepage, and François Yvon. 2011. [Traitement Automatique des Langues 2011 Volume 52 Numéro 1](https://aclanthology.org/2011.tal-1.0). Traitement Automatique des Langues, 52(1)."

Instead, it seems @proceedings does the job for a full issue.
Note this is what is currently used in the aclanthology for the IJCLCLP journal

**Comment by mcandito** [comment]
Hi @mjpost @xinru1414 ,

for making ingestion requests of the other tal volumes,
am I correct that I should wait until the frontmatter debug is done on your side?

I have 14 other volumes.
For the last four of them, I do have a tal-XXX.0.pdf file, but I don't have it for the older volumes.
Thanks

**Comment by xinru1414** [comment]
@mjpost did you manually create the bibkey as well?

**Comment by mjpost** [comment]
Two TODOs here:

- [ ] We need to use `@proceedings` for the frontmatter for journals
- [ ] We need to change the ingestion script to always generate the frontmatter block, even if there is no PDF.

**Comment by mjpost** [comment]
@xinru1414 This is ready for review.

**Comment by mjpost** [comment]
@anthology-assist this is ready for review. Once merged it will fix the citation type for frontmatter.

**Review by anthology-assist — APPROVED** [review]
LGTM

**Comment by mcandito** [comment]
Hi @mjpost @anthology-assist 
There remains a minor problem when generating `@proceedings` for the frontmatter for journals:

Currently, in the `@proceedings`entry, the addition of the "journal", "volume", "number" attributes still creates a redundant citation:
cf. e.g.
https://preview.aclanthology.org/continued-tal-ingestion/2017.tal-1.0/
The name of the journal appears twice:
Jean-Luc Minel, Emmanuel Morin, Pascale Sébillot, and Isabelle Tellier. 2017. Traitement Automatique des Langues, Volume 58, Numéro 1 : Varia [Varia]. Traitement Automatique des Langues, 58(1).

**Could you remove the journal, volume, number attributes of the `@proceedings`entries?**

In order to get:
Jean-Luc Minel, Emmanuel Morin, Pascale Sébillot, and Isabelle Tellier, editors. 2017. Traitement Automatique des Langues, Volume 58, Numéro 1 : Varia [Varia]. ATALA (Association pour le Traitement Automatique des Langues), France.

Sorry about all these problems, due to the rarity of journals on the anthology
Thanks

**Pull request merged**
