### PR TITLE
abstract for L14-1412

### PR DESCRIPTION
**Pull request by leondz**
adds one missing abstract in L14

### CODE REVIEW

**Comment by akoehn** [comment]
Thanks for the PR! Is there a reason why you added this one abstract?  It seems to me that no paper from lrec 2014 currently has an abstract.

**Comment by leondz** [comment]
Sure, I noticed it was missing for this paper, and didn't have time to bulk
update all of them straight away

**Comment by akoehn** [comment]
I am okay with merging this.  It is very unlikely, but could merging this interfere with #395 @mbollmann?

**Comment by mjpost** [comment]
I'll let @mbollmann merge in light of @akoehn's question.

**Comment by mbollmann** [comment]
I'm not touching any papers that have abstracts already for #395, so add away. (It might just make sense in terms of time investment to wait until we've bulk-added as many as we can.)

**Pull request merged**
