### PR TITLE
Merge in some pronunciations and websites

### PR DESCRIPTION
**Pull request by davidweichiang**
from https://github.com/mjpost/pronunciations/blob/master/_data/pronunciations.yaml, but I included only the entries that had IPA -- please discuss whether websites are wanted and whether pronunciations should be in IPA.

Also,
- sorted alpha by last name
- reformatted more compactly
- added some brief instructions

### CODE REVIEW

**Comment by mjpost** [comment]
Looks like the new names DB broke the build...

**Comment by davidweichiang** [comment]
Does the reader not like fields it wasn’t expecting?

**Comment by mjpost** [comment]
I guess not. You can see the output by clicking on the "Details" link in the failed Travis message: https://travis-ci.org/acl-org/acl-anthology/builds/509983016?utm_source=github_status&utm_medium=notification

**Comment by mbollmann** [comment]
> Does the reader not like fields it wasn’t expecting?

The other way around: It doesn't like that there are entries without any `variants` now. After all, I originally conceived it as a *variant* list. :)

I'm not sure about the added websites and pronunciations. I like the idea of providing that information on the website, but it seems to me this will increase the manual upkeep (and modification requests by authors) by *a lot.*

Also, we haven't really addressed the name collision issue yet, and this might potentially make it more difficult to address at some point. What do we do right now if one (or several) of the authors named Yang Liu, for example, would like to have their website added?

**Comment by davidweichiang** [comment]
If users submit changes through PRs that require approval, I can see that that might get laborious.

I think that's orthogonal to the issue of people with the same name. I think it'd be really important to try to separate them no matter what.

**Comment by mjpost** [comment]
I just created a new issue (#208) for discussion on how to handle name collisions.

**Comment by mjpost** [comment]
I agree about websites—I think David just grabbed my raw YAML file, which had other information like that. I do think the idea of having the pronunciation (in IPA or ARPABET) would be a nice feature fitting to a library, and isn’t something that changes.

**Comment by mbollmann** [comment]
Also, I'm not sure everyone's noticed it yet, but I've made the "Search" button on the author pages explicitly search for Google Scholar profiles associated with that name. Those can then easily lead to the person's website as well. Requires a bit more clicks, but less maintenance for us.

**Comment by mjpost** [comment]
@mbollmann I've tried this with many authors and have not been able to get it to return a Google Scholar profile, e.g., http://www.aclweb.org/anthology/search/?q=stuart+m.+schieber. Can you link an example?

**Comment by mbollmann** [comment]
No, I meant the search button on the author pages.

**Comment by davidweichiang** [comment]
So, it sounds like the websites are a no; pronunciations maybe? In any case, this PR should be closed.

**Pull request closed without merging**
