### PR TITLE
Added ACL 24 videos

### PR DESCRIPTION
**Pull request by davidstap**

### CODE REVIEW

**Comment by davidstap** [comment]
@mjpost Gentle ping on this PR

**Comment by mjpost** [comment]
I did a bunch of spot-checking and found mistaken alignments on these papers, which suggests there are likely many more:

* https://preview.aclanthology.org/add_acl24_videos/2024.acl-long.782/
* https://preview.aclanthology.org/add_acl24_videos/2024.acl-long.781/
* https://preview.aclanthology.org/add_acl24_videos/2024.acl-long.777/
* https://preview.aclanthology.org/add_acl24_videos/2024.acl-long.778/

**Comment by mjpost** [comment]
Another thing we should be thinking about is how this process could be improved. At some point in the video creation process, there is a definitive alignment of videos to papers. It would be nice to be able to make use of that instead of having to rely on semi-automatic post-hoc heuristic alignment.

**Comment by davidstap** [comment]
Thanks for catching that - it turns out my random sample  happened to be lucky. I investigated and found that the file from Underline has mismatched titles and videos. (This was the source of earlier errors too.) I'll contact them about fixing it, though they're likely to be tied up with EMNLP next week.

**Comment by mjpost** [comment]
Thanks, @davidstap. I thought you used a heuristic mapping using titles and other information? Do they give you the mapping nowadays?

**Comment by davidstap** [comment]
Yes, Underline provides the mapping nowadays. Given the mismatches I assume they do this heuristically. I haven't got a response from them yet, will send a reminder. I'll also discuss how to improve the process to prevent these errors in the future.

**Comment by davidstap** [comment]
Update: Underline responded; they are currently investigating the issue.

**Comment by mjpost** [comment]
Any updates? Might be worth pinging them again. I also see there are lots of conflicts; can you either resolve them, or maybe it's easier to just start over once you have the updates?

**Comment by davidstap** [comment]
No updates, I'll send another reminder. I think it's easier to simply start over given all the conflicts, I'll close this PR and open a new one when I receive the updated data from Underline.

**Comment by davidstap** [comment]
Still no updates, I have sent another reminder.

**Pull request closed without merging**
