### PR TITLE
EMNLP 2022 ingestion

### PR DESCRIPTION
**Pull request by xinru1414**
# **Notice**: The EMNLP organizers have not delivered a complete proceedings to us

The official ingestion is delayed because it is not yet complete. Once we have all the material in its correct format, we will ingest it.

Open issues on missing items:
- [ ] Full-volume PDF for main and findings proceedings
- [ ] Attachments for main and findings
- [ ] Complete industry volume
- [ ] Complete system demonstrations volume
- [ ] Author affiliation metadata
- [ ] Backlink from [WS 2022](https://aclanthology.org/events/ws-2022/)

### CODE REVIEW

**Comment by xinru1414** [comment]
Not ready to merge.
Issues:
1. Waiting on proceedings.pdf and frontmatter.pdf for the main volume; current ones are only placeholders.
2. Waiting on attachments

**Comment by mjpost** [comment]
Hi, [checking the PDFs on this page](https://preview.aclanthology.org/emnlp-22-ingestion/volumes/2022.emnlp-main/), none of them are right.

**Comment by mjpost** [comment]
Also this page has no metadata: https://preview.aclanthology.org/emnlp-22-ingestion/2022.findings-emnlp.103/

**Comment by abumafrim** [comment]
The last 10 authors in this page (https://preview.aclanthology.org/emnlp-22-ingestion/2022.emnlp-main.298/) are omited.

Missing author names, as on appeared on star softcont, and on the paper:

Neo Lerato Mokono, Ignatius Ezeani, Chiamaka Chukwuneke, Mofetoluwa Oluwaseun Adeyemi, Gilles Quentin HACHEME, Idris Abdulmumin, Odunayo Ogundepo, Oreen Yousuf, Tatiana Moteu and Dietrich Klakow

**Comment by ryancotterell** [comment]
> 

This appears to be an export error in our script that maps the softconf data to yaml. I'll look into it.

**Comment by mjpost** [comment]
If this was done in softconf why don't we just import it directly? We already have direct support for that. Why introduce the aclpub2 conversion?

**Comment by ryancotterell** [comment]
> If this was done in softconf why don't we just import it directly? We already have direct support for that. Why introduce the aclpub2 conversion?

Not all workshops are in softconf, so there's that. The idea was also to keep improving aclpub2 for the switch to OpenReview when it comes.

**Comment by mjpost** [comment]
It seems to be adding extra complexity. My suggestion is we take the most direct route, on a volume-by-volume basis. But I will leave it to you two.

**Comment by mjpost** [comment]
@ryancotterell @xinru1414 The tutorial abstracts are out-of-sync. For example click on the PDF for this one: https://preview.aclanthology.org/emnlp-22-ingestion/2022.emnlp-tutorials.2/

**Comment by mjpost** [comment]
What's the status here? Are we still waiting for data from the EMNLP folks?

**Comment by xinru1414** [comment]
@mjpost yes!

**Comment by Doragd** [comment]
Any timeline to see EMNLP2022 papers online?

**Comment by mjpost** [comment]
We're still waiting for the EMNLP folks to deliver it. We don't have a timeline from them.

**Comment by mjpost** [comment]
user fei-liu-em does not exist

**Comment by evanmiltenburg** [comment]
Small correction to the preview: the GEM workshop was approved/supported by SIGGEN, so our SIG label should be added to make the workshop more easily findable in the Anthology.

**Comment by cdmalon** [comment]
Where are the System Demonstrations papers?

**Comment by akoehn** [comment]
@cdmalon this pr is still marked as a draft and, to quote @xinru1414:
> We are, in fact, still waiting on certain EMNLP material to be delivered

It seems like a lot of people are visiting the preview rendering (judging from logs). To be very clear: this is not a published version, the preview is only an internal tool to check whether a pull request works as intended. Please do not view this as "the emnlp proceedings". If you want to know when the proceedings are published: watch this PR and wait for the merge notification. Only then will the proceedings be published. (Or wait for an announcement on other channels)

**Comment by cdmalon** [comment]
Thanks @akoehn, but the System Demonstrations are notably absent from the preview rendering, which is why I asked.  It seems very odd that they have not yet been delivered almost two months after the conference.  Most other papers at least have a preview rendering.  If they indeed have not been delivered, I wonder if someone can poke them to see what is stopping the delivery.

**Comment by abumafrim** [comment]
@xinru1414 @mjpost a reminder that some of the EMNLP main papers have some missing author names.

**Comment by akoehn** [comment]
@cdmalon the nature of incomplete data is that some data is missing. I am pretty sure that everyone involved in the process knows that the proceedings are not done yet (see also the other messages here). This might sound a bit snarky, but please let's keep the discussion here on point; missing / incorrect data can still be checked and pointed out once we actually think we have all the data.

**Review by mjpost — APPROVED** [review]
I suggest we just merge this. We are still missing many items which have yet to be delivered to us, but this is getting too out of hand.

**Comment by mjpost** [comment]
> Thanks @akoehn, but the System Demonstrations are notably absent from the preview rendering, which is why I asked. It seems very odd that they have not yet been delivered almost two months after the conference. Most other papers at least have a preview rendering. If they indeed have not been delivered, I wonder if someone can poke them to see what is stopping the delivery.

@cdmalon The system demonstrations papers are noticeably absent from the preview because the EMNLP program chairs never delivered them to us. If this is affecting you, you have my sympathies, but unfortunately there is nothing we can do for you. I suggest you email the program chairs and ask why we still do not have them, six weeks after the conference ended.

**Comment by akoehn** [comment]
> I suggest we just merge this. We are still missing many items which have yet to be delivered to us, but this is getting too out of hand.

It might make sense to adapt the github issue templates if we do that so everyone wanting to report missing data for emnlp 2022 knows that this is a know problem and no new issue is needed.

**Review by mjpost — APPROVED** [review]
This is incomplete, and as a rule we prefer to ingest entire proceedings, due in part to the fact that it reduces the chances for errors. However, given how far past the actual conference we are, I am going to approve this so that we can have at least partial availability.

**Comment by mbollmann** [comment]
@mjpost PR is still marked as a draft, do you want to tinker with it more or should we merge this? Should we also create an issue out of the info in @xinru1414's opening post?

**Comment by mjpost** [comment]
@mbollmann yes and yes! was just waiting for the build to finish.

**Pull request merged**
