### PR TITLE
Ingestion: tal

### PR DESCRIPTION
**Pull request by xinru1414**

### CODE REVIEW

**Comment by mcandito** [comment]
Hi @xinru1414 thanks for the ingestion

I identified a problem for the .0.bib files : they correspond to the whole issue, and thus the bibtex entry should not be \@article, but \@proceedings (cf. also discussion in https://github.com/acl-org/acl-anthology/pull/2412)
as is done for https://aclanthology.org/2021.ijclclp-1.0/ 

Another minor problem are the curly braces in the full issue titles
e.g. in https://preview.aclanthology.org/continued-tal-ingestion/volumes/2017.tal-1/
Shall I remove them in the input aclpub I provide to you?

**Comment by xinru1414** [comment]
@mcandito for future ingestion material please remove the curly braces.
@mjpost i'm not sure about proceedings vs article could you advise?

**Comment by xinru1414** [comment]
closes #2430

**Comment by mcandito** [comment]
Hi @xinru1414 ok I've modified my scripts to remove the curly braces

If easier to redo the ingestion, the updated zips are here
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2017.zip
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2019.zip
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2020.zip
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2021.zip

**Comment by mcandito** [comment]
Hi @xinru1414 ,
It seems to me the "proceedings" instead of "article" for frontmatter is validated cf. comment in https://github.com/acl-org/acl-anthology/pull/2412
Is it possible to retry the ingestion of tal-2017 2019 2020 and 2021
with the updated zips above?
(so that this also fix the curly bracket bug)
 Thanks

**Comment by mjpost** [comment]
The volume titles for 2011 and 2018 are formatted differently on [the venue page](https://preview.aclanthology.org/continued-tal-ingestion/venues/tal/); can we come up with a consistent format?

**Comment by mcandito** [comment]
Hi @mjpost 
I'm confused about which changes explain the different formatting, cf. there were changes both in my scripts and in the ingestion script on your side, followed by manual addition of frontmatter block for 2011.tal-1 and 2018.tal-1

Is it possible to reinject ?? 
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2018.zip
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2011.zip

BUT **NB** for 2011, there is the additional problem that before 2017, there is no pdf for full issues.
If I understood well, currently your script will not produce a frontmatter block
cf. pending debug on your side
https://github.com/acl-org/acl-anthology/pull/2412 stating:
"We need to change the ingestion script to always generate the frontmatter block, even if there is no PDF"

Also, cf. my last comment in https://github.com/acl-org/acl-anthology/pull/2412
Could you **not** include the journal, volume, number attributes of the `@proceedings` entries?
Thanks a lot

**Comment by mjpost** [comment]
@mcandito on (2), can you note what you want this to look like?

* Here's an example: https://aclanthology.org/2011.tal-1.0.bib
* Here's the spec: https://www.bibtex.com/e/entry-types/#proceedings

But I'm not sure what it's supposed to look like.

**Comment by mcandito** [comment]
Hi @mjpost,

**on (3) different formatting of volume titles:**
- the target format is that of 2019, and not that of 2018
- your script has taken it from the **yyyy.tal-x.0.bib** file (same for years 2017, 2019, 20, 21)
- for the ingestion of 2011 and 2018, which were the first one we tried: at that time I had not provided any .0.bib file, so it seems your script took the volume titles from the **meta** file 
- since now I've debugged and I provide the .0.bib files, 
I think reinjecting 2011 and 2018 with the current zips will solve the discrepancy.
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2018.zip
http://www.linguist.univ-paris-diderot.fr/~mcandito/tmp/2011.zip

Do you prefer me to modify the meta files ??
Note reinjecting 2011 and 2018 will also solve the problem of missing frontmatter blocks for 2011.tal-2 2011.tal-3 2018.tal-2 2018.tal-3 (I think you manually added for the -1 issues).

**on (2)** : note the `@proceedings` entry is a workaround , cf. there is no entry specific to full journal issues

  Could it look like:
Éric Villemonte de La Clergerie, Béatrice Daille, Yves Lepage, and François Yvon, editors. 2011. Traitement Automatique des Langues, Volume 52, Numéro 1 : Varia [Varia]. ATALA (Association pour le Traitement Automatique des Langues), France.

To get this could you use the `proceedings`type,
  - with the `title` attribute equal to that I provide in my .0.bib files (does your script use this??)
  - without the `journal` nor the `number` attribute (in accordance with the spec)
  - but also if possible without the `volume` attribute (in contradiction with the spec) 
  - be careful to concatenate the **number** to the bibkey otherwise the same key will be produced for all 3 issues of a year-volume
  
Namely produce a bib file like:
`@proceedings`{tal-2011-1,
  title = {Traitement Automatique des Langues, Volume 52, Numéro 1 : Varia [Varia]},
  editor = {Villemonte de la Clergerie, Éric and Daille, Béatrice and Lepage, Yves and Yvon, François},
  publisher = {ATALA (Association pour le Traitement Automatique des Langues)},
  year = "2011",
  address = "France",
  url = {https://aclanthology.org/2011.tal-1.0},
}

**If you don't like the idea of contradicting the spec of bibtex entries,**
alternatively it could look like: 
Éric Villemonte de La Clergerie, Béatrice Daille, Yves Lepage, and François Yvon, editors. 2011. Varia [Varia], volume 52 of Traitement Automatique des Langues. ATALA (Association pour le Traitement
Automatique des Langues), France

(no way to add the number) 
**BUT** this supposes to create the following bib entry:

`@proceedings`{tal-2011-52-1,
    title = "**Varia [Varia]**",
    editor = "Villemonte de La Clergerie, {\'E}ric  and Daille, B{\'e}atrice  and      Lepage, Yves  and      Yvon, Fran{\c{c}}ois",
    year = "2011",
      **series**    = "Traitement Automatique des Langues",
    volume="52",
    address = "France",
    publisher = "ATALA (Association pour le Traitement Automatique des Langues)",
    url = "https://aclanthology.org/2011.tal-1.0",
}

If so, tell me how I should mofify the zip I provide to you.

I had no idea it would cause so many subtleties to handle for you!! 
I guess this is because the anthology mostly concerns proceedings and not journals

Thanks for reading so far
Marie

**Comment by mjpost** [comment]
On (3), with your permission, @anthology-assist will just edit them directly in our data. There is no need to reingest. Is that okay with you? So we will make 2011 and 2018 look like 2019 in terms of booktitle formatting.

**Comment by mcandito** [comment]
Hi @mjpost 
on (3) : yes no problem !
Thanks

**Comment by mcandito** [comment]
Hi @mjpost, @anthology-assist , 
I modified the 2011.tal.xml and 2018.tal.xml to homogenize booktitle formatting. cf. new pull requests 12464 and #2465

**Comment by mcandito** [comment]
Hi, @mjpost @xinru1414 is it possible to merge the continued-tal-ingestion to see it on the front page?
What is blocking?
Thanks

**Comment by mjpost** [comment]
I think we can merge this. I'm afraid enough time has passed that I've lost track of the details. I think we still have one bug, the handling of the frontmatter BibTeX entry, but we can make that a separate issue.

**Review by mjpost — APPROVED** [review]
LGTM

**Pull request merged**
