### PR TITLE
Automatic corrections

### PR DESCRIPTION
**Pull request by davidweichiang**
I wrote a script to automatically convert the XML to the conventions that (I think) were agreed upon in #135, and this huge PR contains the result. It's easy to rerun, in case you want something to be done differently.

I think I've looked through all of the changes and corrected any errors I saw.

I originally hoped that the tool to do these corrections would be idempotent, so it could be run at any time to clean up the XML, but I don't think that's possible, unfortunately. For example, `\{` becomes `{` becomes nothing, and `\textasciitilde` becomes `~` becomes a space.

But the script has a fairly careful TeX to Unicode converter whose output has been checked, so I suggest that this converter could replace existing ones (there seem to be several, and I'm not sure why).

- Outside of formulas, all TeX is converted to Unicode equivalents.

- Even characters that were already Unicode are encoded as UTF-8
      instead of using XML escapes. This is more readable/editable,
      but only if your editor supports it.

- Formulas are wrapped inside `<tex-math>` and left as-is. However,
      some formulas that are just numbers or just @ are converted to
      plain text.

- Italics are converted to `<i>` and boldface is converted to
      `<b>`. Small caps (`\sc` and `\textsc`) is thrown away.

- URLs are wrapped in `<url>`.

- Straight (single and double) quotes are converted to curly ones
      (these rules are the hairiest).

- Line breaks and indentation are _not_ preserved. I apologize that
      this makes the diffs of abstracts hard to read. I can provide a
      easier to read diff if needed.

### CODE REVIEW

**Comment by mbollmann** [comment]
I haven't had time to look over the changes yet, but if we decide to merge this, we should also remember to update the XML schema alongside it. `<url>` and `<tex-math>` are not currently allowed tags, for example.

**Comment by davidweichiang** [comment]
I’ve also already introduced <fixed-case> in a commit in master. But I removed <sup> for you :)

**Comment by mbollmann** [comment]
I'll happily add support for these things in the static rewrite :)

But I wondered, do we know if the currently live website will cope with these tags well, if we merged this now?

**Comment by davidweichiang** [comment]
That's a good question. The current website currently renders math with `$...$`, so `<tex-math>...<tex-math>` wouldn't be that much worse. The `<url>` tag would also show up, but it occurs only 7 times anyway. (There are lots of URLs in abstracts that are not tagged...at some point it would be nice to automatically detect and tag them, and have them show up as hyperlinks on the website?)

If it's desirable to keep the schema simple, we could remove the `<b>` tag, which occurs only 9 times and (IMO) never with any semantic importance.

**Comment by davidweichiang** [comment]
Oh, I guess it's also possible that the new tags disappear since they're not HTML tags, or that the XML to HTML converter crashes?

**Comment by mjpost** [comment]
I've paged though some of these and the changes look good to me. I prefer native unicode to the HTML escapes (though note @danielgildea's [comment about &amp;](https://github.com/acl-org/acl-anthology/issues/124#issuecomment-459368104)). I think modern readers should be expected to support unicode.

I was worried that removing line breaks would break paragraph boundaries in abstracts, but a few minutes of paging through the diff from the command line did not turn up any paragraph breaks in the old side of the diff (where incidentally the diffs are presented just fine). Condensing the abstracts actually cleans up a lot of broken formatting.

So I think this could be merged to master and will do so if there are no other comments.

However, @mbollmann's point is a good one. For example, it looks like `<fixed-case>` is not properly handled in the current commit to master. For example, [W11-0608](https://aclanthology.info/papers/W11-0608/w11-0608) is presented incorrectly in HTML, [BibTeX](https://aclanthology.info/papers/W11-0608/w11-0608.bib), and [MODS XML](https://aclanthology.info/papers/W11-0309/w11-0309.xml). (Probably Word, too, but I don't have the patience to launch the app and find out). The BibTeX is especially bad:

```
@InProceedings{W11-0608,
  author = 	"van Rij, Jacolien
		and van Rijn, Hedderik
		and Hendriks, Petra",
  title = 	"{\{}WM{\}} Load Influences the Interpretation of Referring Expressions",
  booktitle = 	"Proceedings of the 2nd Workshop on Cognitive Modeling and Computational Linguistics",
  year = 	"2011",
  publisher = 	"Association for Computational Linguistics",
  pages = 	"67--75",
  location = 	"Portland, Oregon, USA",
  url = 	"http://aclweb.org/anthology/W11-0608"
}
```

Consequently I think that for changes beyond simple encoding ones, we should be committing them only to the `static-rewrite` branch. This will keep us from having to change the code in two places. It will also save Marcel the work of continually remerging in the master branch.

**Comment by mbollmann** [comment]
I think there's a main design choice to be made here whether the additional markup tags we're introducing should be a subset of HTML or not.

For example, `<url>` might be just as well be represented using `<a href="...">`. Other tags could be `<span class="acl-fixed-case">` or similar. That way the titles/abstracts could be parsed and converted by any tool that takes HTML input; the website could style or handle them using CSS. If we use `<url>`, `<fixed-case>` etc. instead we always need our own customized converters.

Has this been discussed before? I couldn't find anything in #135.

**Comment by davidweichiang** [comment]
I'm pretty sure that's a case where the author or workshop organizer put curly braces in the title, and the curly braces made it into the XML. I don't think I put them there.

**Comment by mjpost** [comment]
I'm referring to the conversion process—W11-0608 has `<fixed-cased>` [in the database file](https://github.com/acl-org/acl-anthology/blob/master/import/W11.xml#L1812).

Although, it occurs to me that it's possible that the HTML and citation formats were generated from before your XML conversion. Looking at the [date of the last regeneration](https://github.com/acl-org/acl-anthology/issues/117#issuecomment-465702476) and your commit date, it seems that that is in fact what happened, so if anything, your commit to master will have fixed this issue.

**Comment by mjpost** [comment]
@davidweichiang, can you add the script, too? I have some new workshops to import, and the current ingest process is to run [anthoBibs2xml.pl](https://github.com/acl-org/acl-anthology/blob/master/tools/anthoBibs2xml.pl) over the top-level bib file.

**Comment by davidweichiang** [comment]
Done.

**Comment by mjpost** [comment]
Thanks! This is great.

**Comment by davidweichiang** [comment]
Do you want `anthoBibs2xml.pl` and `normalize_xml.py` (and `anthologize.py`?) unified into a single program? Or at least refactored so they don't have overlapping jobs?

**Comment by mjpost** [comment]
Yes, ideally. It'd also be good to have it print nice errors, so that pub and workshop chairs could easily run it and get feedback on what's wrong with their bibs. 

I also think it's a good idea to move away from Perl and towards Python (3).

**Comment by davidweichiang** [comment]
I'll take a look; it would be helpful if someone could explain how `anthologize.py` and `anthoBibs2xml.pl` relate to each other, and how they are typically invoked.

**Comment by mjpost** [comment]
Sorry, where is `anthologize.py`?

`anthoBibs2xml.pl` is used to convert the bib files directly into the authoritative XML. For example, [for ALTA 2018](https://github.com/acl-org/acl-anthology/commit/c4d3b3c70ccfd9d6412a9fc5b794d2aaa214a437), I was given [this Bib file](http://aclweb.org/anthology/U/U18/U18-1.bib) and ran the following command:

```
cat U18-1.bib | $ANTH/tools/anthoBibs2xml.pl -V U18 > $ANTH/import/U18.xml
```

(This generated the following on STDERR, which I ignored for now:

> \# Copyright 2005 © by Min-Yen Kan
> XXXX 72 Business documents encode a wealth of information in a format tailored to human consumption &#8211; i.e. aesthetically disbursed natural language text, graphics and tables. We address the task of extracting key fields (e.g. the amount due on an invoice) from a wide-variety of potentially unseen document formats. In contrast to traditional template driven extraction systems, we introduce a content-driven machine-learning approach which is both robust to noise and generalises to unseen document formats. In a comparison of our approach with alternative invoice extraction systems, we observe an absolute accuracy gain of 20\% across compared fields, and a 25\%&#8211;94\% reduction in extraction latency.

)

**Comment by mjpost** [comment]
(Incidentally, we should move `anthoBibs2xml.pl` under `bin/`, too)

**Comment by davidweichiang** [comment]
anthologize.py is buried somewhere in acl-pub and seems to have a very similar function.

**Comment by knmnyn** [comment]
Hi all:

Just for context.  I think anthologize.py was created softconf or similar
to work with the output from softconf.  anthoBibs2xml.pl was written by
myself to create a stopgap for converting BibTex contributed by softconf
into the format for the Anthology.  At the time, I found it easier to rely
on exports that pub chairs were already doing (the "cdrom.tgz" export) for
their process, rather than depending on softconf's anthologize pipeline,
which was not always updated with what pub chairs were doing.

Agreed that we need to take a single workflow for all systems, else it
becomes unmanageable.

- Min

>

**Comment by mjpost** [comment]
Ah, found it—it's actually [anthology.pl](https://github.com/acl-org/acl-pub/blob/gh-pages/assets/files/create_book/bin/anthologize.pl)? It seems this script has a more specialized call setting even if the functionality is similar (which I can't quite tell without looking at it more deeply).

I don't like duplication but in any case we need this functionality in the Anthology since we sometimes import data that was not created with ACLPUB—for example, for folks who use easy chair.

**Comment by knmnyn** [comment]
Hi Matt, all:

It might be called anthology.pl.  I am not so sure...  - M

**Comment by mjpost** [comment]
Had a typo in the above (now fixed): `anthologize.pl`.

**Comment by mjpost** [comment]
To expand a bit on this picture, @slukin has added [some nice documentation](https://github.com/acl-org/acl-pub/blob/gh-pages/full-aclweb-proceedings-howto.md) for book chairs producing the proceedings. This involves calling [make_anthology.sh](https://github.com/acl-org/acl-pub/blob/gh-pages/assets/files/aclweb_proceedings/make_anthology.sh), which in turn calls our `anthologize.pl`. If that goes well, the XML file will be correct already and we will not need to re-run `anthoBibs2XML.py`. 

This makes me think that the right way to do this is to keep the XML file generation in ACLPUB. If we could factor out the part of [anthologize.pl](https://github.com/acl-org/acl-pub/blob/fd94d8ef7773af846208b358a0fc23e54f25f5cd/assets/files/aclweb_proceedings/make_anthology.sh#L30) that does the Bib → XML conversion, then we could retain [the more specific invocation](https://github.com/acl-org/acl-pub/blob/fd94d8ef7773af846208b358a0fc23e54f25f5cd/assets/files/aclweb_proceedings/make_anthology.sh#L30) (which assumes an ACLPUB directory) and have it also work to do just the XML → Bib conversion.

**Comment by davidweichiang** [comment]
I think in the last bit you meant Bib -> XML, right?

I think that sounds like a reasonable plan, but there are some corrections that need to be made to anthologize.pl. I can create an issue over there. Then we can get rid of both normalize_anth.py and anthoBibs2XML.pl.

**Comment by mjpost** [comment]
Yes, sorry, Bib → XML. Sounds good.

**Comment by davidweichiang** [comment]
I'm unclear about how these scripts handle additional files.

- `anthologize.pl` looks for files ending with `_OptionalAttachment.*`. If they are PDF files, it renames them to `.Notes.pdf`.
- [Pub chairs are expected](https://github.com/acl-org/acl-pub/blob/gh-pages/full-aclweb-proceedings-howto.md) to look at the remaining attachments and manually rename them to either `.Software.*` or `.Datasets.*`.
- `anthoBibs2xml.pl` looks for files that are called `.Software.*` or `.Datasets.*` and adds corresponding fields `<software>` or `<dataset>` to the XML file.

But my questions are:

- Does that mean that both `anthologize.pl` and `anthoBibs2xml.pl` need to be run?
- I don't see where the link to the `.Notes.pdf` file gets added to the XML.

**Comment by mjpost** [comment]
Sorry for the late response, I lost track of this. 

I think that ideally, `anthoBibs2xml.pl` would not need to be run for proceedings generated by ACLPUB. I am not sure where `.Notes.pdf` gets added, but it may be one of those things that gets generated or ingested independently. This should be a part of `anthologize.pl` as well.

Regarding the manual renaming, it seems to me that STARTv2 should allow one to specify whether one is submitting software or data—or perhaps that we should do away with the distinction altogether.

**Comment by davidweichiang** [comment]
This discussion parallels https://github.com/acl-org/acl-pub/issues/9 (my fault) but doesn't really fit well in either. I'll create a new issue so this comment thread can be laid to rest!

**Comment by davidweichiang** [comment]
Great, thanks! Will that stay for future conferences?

**Comment by slukin** [comment]
I hope so, but I think it is up to each conference PC, and hopefully the
PC's will offer their recommendation to future PCs.

I'm not 100% sure how START handles each *ACL conference, but I assume they
have some template that we might be able to ask them to update with these
separate fields across the board for all future conferences?

**Pull request merged**
