### PR TITLE
Adding 2 authors to Anthology ID 2020.winlp-1.18

### PR DESCRIPTION
**Pull request by Witty-Kitty**
The authors already appear on the paper itself, just need to update the metadata on the ACL publications website.

### CODE REVIEW

**Comment by akoehn** [comment]
Thanks for creating a PR directly and saving us some work! We still need an official word from the WiNLP organizers -- see our (just-enacted) policy on revisions to the author list.

> ### Note on author changes
>
 >   Some conferences and workshops have a policy of disallowing authorship changes after the initial submission. Because it is beyond our ability to track this, changes to the list of authors, whether in the PDF or in the metadata, require permission from the associated conference program chair or workshop/tutorial chair. You are responsible for arranging for this permission to be conveyed to us, either via email or on your Github issue. We will make exceptions for the correction of obvious spelling errors or other typos, and for author name changes (i.e., the list of authors is unchanged, but one of the authors changes their name).

**Comment by Witty-Kitty** [comment]
Do I need to get this permission from WiNLP organisers myself?
Or is that initiated from your end?

**Comment by akoehn** [comment]
It would be easiest for us if you could ask them to comment here or send an email.

**Comment by mjpost** [comment]
I'm closing this in the meantime. Please feel free to reopen it if/when permission comes through.

**Pull request closed without merging**
