### PR TITLE
Correct list of authors of 2021.bsnlp-1.14 (consistent with pdf)

### PR DESCRIPTION
**Pull request by adamjankaczmarek**
Correction request for 2021.bsnlp-1.14 paper's authors list - to be consistent with pdf version: https://www.aclweb.org/anthology/2021.bsnlp-1.14.pdf

### CODE REVIEW

**Comment by akoehn** [comment]
Please obtain an ACK from the relevant chairs per our policy: https://www.aclweb.org/anthology/info/corrections/#note-on-author-changes

**Review by lastthyme — APPROVED** [review]

**Review by akoehn — CHANGES_REQUESTED** [review]
Just to be sure: You need an ACK from the relevant chairs as I linked in my previous comment. Please let me know if you intend to obtain one, otherwise we will close this PR.

**Comment by adamjankaczmarek** [comment]
Yes I've already contacted the BSNLP'21 wokshop organizers and I'm awaiting response from them.

**Comment by valeriobasile** [comment]
Hi, I was the Publication Chair for EACL 2021, where this paper was published and I acknowledge that the request is legitimate. Is this this comment sufficient to this aim?

**Comment by jpiskorski** [comment]
On behalf of the BSNLP 2021 workshop we are fine with the changes wrt. the authors list.

Jakub Piskorski
On behalf of BSNLP 2021

**Comment by mjpost** [comment]
Okay, we'll process this with May's corrections.

**Comment by xinru1414** [comment]
see PR #1349

**Pull request closed without merging**
