### PR TITLE
Fixed-case treatment for more cases.

### PR DESCRIPTION
**Pull request by agutkin**
Julia/Quran/Quranic/Hadith/Panini/Vygotstky/Russia

### CODE REVIEW

**Comment by mjpost** [comment]
Think you'll have more of these? If so I might wait a bit so you can add them here.

**Comment by agutkin** [comment]
No, Matt. That's it for now.

**Comment by agutkin** [comment]
Hi Matt! Any chance you can merge this soon-ish? I'm mostly concerned with the Quran-related fixes, would be nice to have them in.

**Review by mjpost — APPROVED** [review]

**Comment by mjpost** [comment]
Done—sorry to have let this linger!

**Comment by mjpost** [comment]
(and many thanks for putting your time into this)

**Pull request merged**
