### PR TITLE
update author name to Robyn Speer on 3 papers

### PR DESCRIPTION
**Pull request by rspeer**
This PR replaces the name I no longer use with my current name, Robyn Speer.

### CODE REVIEW

**Comment by rspeer** [comment]
I have corresponding PDF updates for the most recent two of these papers.

- The updated paper for S17-2008 is: http://s3.amazonaws.com/rspeer-acl-updates/S17-2008.pdf
- The updated paper for S18-1162 is: http://s3.amazonaws.com/rspeer-acl-updates/S18-1162.pdf

**Comment by rspeer** [comment]
Original issue: #117

**Comment by jlowryduda** [comment]
I am the co-author of the papers and I assent to the changes.

**Comment by havasi** [comment]
I'm ok with this.

**Pull request merged**
