### PR TITLE
added booktitle to author list page (closes #521)

### LINKED ISSUE #521: add venue to papers on author pages
When perusing an author page (e.g., https://www.aclweb.org/anthology/people/m/matt-post/), it would be helpful if we listed the venue each paper was published at, perhaps as something like "ACL" instead of the long name.

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by mjpost** [comment]
Here's how this looks:

image

**Comment by mbollmann** [comment]
That seems potentially very useful! On the design side, I think I would try giving the booktitles the `text-muted` CSS class, I think this could make for a cleaner look.

**Comment by mjpost** [comment]
Awesome, will try it out tonight.

**Comment by mjpost** [comment]
That does look a lot better (underlined link has mouse over it):

image

**Comment by akoehn** [comment]
Nothing useful to add, only that I like it! (part of the initiative to give positive feedback whenever I like something)

**Comment by mjpost** [comment]
Thanks, it's nice to have input.

**Comment by akoehn** [comment]
I had a look at the templates because I was curious how this works and because I was wondering whether the whole file actually needs to be duplicated (which could lead to inconsistencies if modifications are not done in both places).  The current list template seems to be rather complicated to me. The paper data is fetched in the `single` template and also in the list item templates:

```
{{ $volume_id := slicestr .Params.anthology_id 0 3 }}
{{ $paper := index (index $.Site.Data.papers $volume_id) .Params.anthology_id }}
```
This volume id fetching is performed in several places and it seems to be brittle considering the planned switch to the new ID schema.  Couldn't the list item rendering be performed using a partial template which gets the paper metadata and whether the volume should be printed as well?  This way, this indexing would only be performed in one place and there would only be a single `list-entry` template instead of two.  That way, the weird `{{ ($.Site.GetPage $page).Render "list-entry" }}` would also not be needed; took me some time to understand what it does.

I am a bit sorry for bringing this up in a simple pull request, but every change is a possibility for simplification.  I lack the experience in hugo templating to see whether the approach with partial templates has problems and therefore don't want to implement this without any feedback.

**Comment by mbollmann** [comment]
> This volume id fetching is performed in several places and it seems to be brittle considering the planned switch to the new ID schema.

This is true, but I don't see how this is related to this PR. Changing the ID schema will require reworking the code and templates in *a lot* of places, and should probably be discussed in #291.

> That way, the weird `{{ ($.Site.GetPage $page).Render "list-entry" }}` would also not be needed; took me some time to understand what it does.

It's the Hugo way of doing things by saying "everything is a page". A paper is just a page, and if I want to print information about a specific paper, I render its page with the appropriate template. I kind of like that abstraction.

I agree with DRY though, but I would look into refactoring the repeating parts *within* the list entries into partial templates, not replacing the list entry templates themselves. Just my 2¢.

**Comment by akoehn** [comment]
> This is true, but I don't see how this is related to this PR.

My point was that we should not add another file in which this will need to be changed if we don't need to.

Re. the "everything is a page": The `single` template iterates over papers, and each paper data structure contains the necessary data to display it.  Instead of using this data, a markdown file location is computed and this markdown file is rendered.  However, as the markdown file does not include the information needed, the same paper data structure we already had available in the loop in `single` needs to be retrieved again. It seems to be much simpler to me to use a partial template, give it the `$paper` data structure and whether to add the booktitle and let it render that.  This would get rid of

 - the markdown file location generation logic
 - the repeated lookup of metadata
 - the duplicated list item template

In fact, as far as I can see, no information from the markdown page other than the ID is actually used in the template.  Do we need this additional complexity only to adhere to "everything is a page"? (This is a real question, not just a rhethorical one!)

I don't want to stop you from merging this, I just want to understand the templating code better to be able to contribute to it; these kinds of design decisions seem to be important for this.

**Comment by mjpost** [comment]
Thanks for the discussion, Arne. I agree it's good to have these discussions when they arise.

I also agree that it's somewhat of a shame to copy the list layout, only to add a single field (the booktitle). I looked for a way to parameterize this so as to keep a single template, but as far as I could tell, it's not possible in the current setup.

I haven't read enough Hugo documentation to understand how all of this works. How much work would it be to rework this in the fashion you describe, so that we could see if it's simpler?

**Comment by mbollmann** [comment]
> Re. the "everything is a page": The `single` template iterates over papers, and each paper data structure contains the necessary data to display it.

No, it iterates over a list of paper IDs. (Admittedly, the author `single` template then fetches the paper to check its publication year, which could be refactored. But the volumes `single` template does not, for example.)

>     * the repeated lookup of metadata

I agree that this is not very stylistically pleasing, but I wonder if it actually incurs much overhead. Hugo is heavily optimized, I wouldn't be surprised if that lookup was cached anyway at the time the `list-entry` template performs it again. That is something that could be worth testing, though.

> In fact, as far as I can see, no information from the markdown page other than the ID is actually used in the template.

The `.RelPermalink` is used, and AFAICT can't be obtained except for explicitly querying the page. If we move the logic to a partial template, we'd have to look up the page anyway to get this. The alternative is generating the link from scratch, which seems error-prone.

**Comment by davidweichiang** [comment]
It looks great except that the conference names are so long...

**Comment by mjpost** [comment]
We should add a `booktitle_short` tag (or an attribute on `booktitle` with a short name for each volume (e.g., “ACL”, “NAACL Demos”, etc). We could then display that here and also export it for use with acleanbib’s `--concise` option: https://github.com/Olamyy/acleanbib/issues/3). 

This could go on the “meta” tag in ACLPUB for future conferences and we could annotate old entries for all of *ACL in under an hour I bet.

**Comment by mjpost** [comment]
e.g., #567

**Comment by akoehn** [comment]
Regarding the refactoring I proposed above:  I currently don't have time to look into it so please be free to merge this and add an issue assigned to me to look into the refactoring at a later time.

**Pull request merged**
