### PR TITLE
Reverted change to FinNLP

### PR DESCRIPTION
**Pull request by mjpost**
FinNLP was accidentally overwritten with another workshop. This reverts that.

It appears that FinNLP might have had two meetings in 2023.

### CODE REVIEW

**Comment by raheelqader** [comment]
I don't think that's the correct workshop, it should be this one: https://sites.google.com/nlg.csie.ntu.edu.tw/finnlp2023/home

the accepted papers are different

**Comment by mjpost** [comment]
Yes, this was an existing FinNLP workshop, not associated with IJCNLP. It was accidentally over-written. @anthology-assist will re-ingest the IJCNLP one as volume 2.

https://sites.google.com/nlg.csie.ntu.edu.tw/finnlp-2023/home

**Comment by raheelqader** [comment]
hey @mjpost,
I think the 6th edition of the workshop has still not been indexed. Here is the link: https://sites.google.com/nlg.csie.ntu.edu.tw/finnlp2023/accepted-papers

**Comment by mjpost** [comment]
Yes, it has not been ingested. We cannot ingest from the "accepted papers" page but need the data in a special format. @anthology-assist will have to comment.

**Comment by raheelqader** [comment]
I will try to contact the organizers of the workshop and see if they can help.

**Comment by therealthapa** [comment]
Is there any update on this? The one that was ingested earlier had the correct papers. The problem was that it had overwritten the FinNLP that was conducted in IJCAI in 2023. @anthology-assist

**Comment by ChunJiChen** [comment]
Hi @anthology-assist ,  

I want to clarify the problem in this discussion. In sum, we have two FinNLP proceedings (IJCAI and IJCNLP-AACL) in 2023, but only one proceedings was uploaded. The correct version for FinNLP@IJCNLP has still not been uploaded.  

(1) The current FinNLP-2023 on ACL Anthology (https://aclanthology.org/volumes/2023.finnlp-1/) is the event we hosted in IJCAI-2023. It should not been shown together with IJCNLP-AACL (https://aclanthology.org/events/aacl-2023/)

(2) The correct version that should be shown together with IJCNLP-AACL is that shared by the IJCNLP-AACL proceedings chair. For your convenience, here is the data generated by ACLPUB from the SoftConf system: https://drive.google.com/drive/folders/1VkekfSDvzrJCRE5ds1E4HjLrBjNd7n_x?usp=sharing

Could you help to upload this proceedings, and link it with IJCNLP-AACL-2023, please? 

@mjpost Sorry for the inconvenience caused. Please help us to reopen this PR.

**Pull request merged**
