### PR TITLE
Add preview warning

### LINKED ISSUE #2356: Make previews more recognizable as such
We should add a very clear watermark on Anthology previews to prevent this kind of mistake. 

@cdmalon this pr is still marked as a draft and, to quote @xinru1414:
> We are, in fact, still waiting on certain EMNLP material to be delivered

It seems like a lot of people are visiting the preview rendering (judging from logs). To be very clear: this is not a published version, the preview is only an internal tool to check whether a pull request works as intended. Please do not view this as "the emnlp proceedings". If you want to know when the proceedings are published: watch this PR and wait for the merge notification. Only then will the proceedings be published. (Or wait for an announcement on other channels)

_Originally posted by @akoehn in https://github.com/acl-org/acl-anthology/pull/2283#issuecomment-1409025903_

### PR DESCRIPTION
**Pull request by akoehn**
fixes #2356

### CODE REVIEW

**Review by mjpost — APPROVED** [review]
Thanks for this! I already merged it into EMNLP. Only comment is it might be nice to center the text in the banner, but I'll leave that to you.

**Comment by akoehn** [comment]
I tried it yesterday for 2 minutes but then gave up due to my lack of bootstrap knowledge. Maybe @mbollmann knows how to center that text?

**Comment by mbollmann** [comment]
`class="text-center"`?
https://getbootstrap.com/docs/4.1/utilities/text/

**Comment by akoehn** [comment]
yup, thx @mbollmann!

**Pull request merged**
