### PR TITLE
Ingestion: jeptalnrecital

### PR DESCRIPTION
**Pull request by anthology-assist**

### CODE REVIEW

**Comment by mjpost** [comment]
Were these volume IDs confirmed by the JEP folks?

**Comment by mjpost** [comment]
The venues page shows very different booktitles (https://preview.aclanthology.org/jeptalnrecital-taln-ingestion/venues/jeptalnrecital/). Can we have them confirm?

**Comment by anthology-assist** [comment]
@mjpost Yes, confirmed. These are a subset of volumes. We are missing four volumes. In contact with the organizers.

**Review by mjpost — APPROVED** [review]

**Comment by mjpost** [comment]
@anthology-assist what's the status of this?

The [preview page](https://preview.aclanthology.org/jeptalnrecital-taln-ingestion/venues/jeptalnrecital/) shows lots of backslashes in the titles.

**Comment by anthology-assist** [comment]
Unsure of which PDFs and which volumes need to be updated/reingested. Waiting.

**Comment by mjpost** [comment]
In that case I suggest just reingesting over the current PR. It's the least error-prone and likely the quickest.

**Pull request merged**
