### PR TITLE
Author name unification; closes #1130, #1082

### LINKED ISSUE #1130: Correction to Anthology ID XXX
Hi, I have two author profiles in the ACL anthology.

1. https://www.aclweb.org/anthology/people/w/wasi-ahmad/
2. https://www.aclweb.org/anthology/people/w/wasi-uddin-ahmad/

My name is Wasi Uddin Ahmad, but my first name is Wasi and last name is Ahmad. So, I want to retain my first profile which is under `wasi-ahmad`. Is it possible to change my name from `Wasi Uddin Ahmad` to `Wasi Ahmad` for the following paper such that both my profiles get merged?

- https://www.aclweb.org/anthology/K19-1035/

Thanks!

### PR DESCRIPTION
**Pull request by davidweichiang**

### CODE REVIEW

**Comment by davidweichiang** [comment]
Here F. is treated as a middle initial; not sure yet if that's the right thing to do.

**Review by nschneid — APPROVED** [review]
Seems fine to me. I don't know the officially preferred way to cite a paper with a multipart surname whose first part is abbreviated, but my guess is that people would default to treating that as a middle initial.

**Comment by mjpost** [comment]
If the PDF has the `F.`, and we know it's part of the surname, shouldn't we put it there? I think our policy of (a) treating the PDF as truth and (b) binding name variants is the simplest way forward.

**Comment by nschneid** [comment]
I have heard that for multiword Portuguese surnames the last one is the most important. [CMS advises](https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Alphabetizing.html?page=2):

> Q. I’m indexing Portuguese names. For example, António Gonçalves Caldeira. Am I to index by the first last name or the second?
> 
> A. Portuguese names are indexed under the last element. If you are worried that readers will be lost, provide a cross-reference under the middle element.

I gather Ramón is Spanish, not sure if the same principle holds there.

**Comment by mjpost** [comment]
Small comment: "closes" works only with a single argument. If you want to close multiple issues you have to put it in front of each.

**Pull request merged**
