### PR TITLE
Ingestion: NAACL 2024

### PR DESCRIPTION
**Pull request by iconstantinescu**
1. [x] In the Github sidebar, add workshop to work items and the current milestone
1. [x] In the Github sidebar, make sure to link to a corresponding PR under "Development"
1. [x] Make sure the branch is merged with the latest `master` branch
1. [x] Ensure that there are editors listed in the `<meta>` block
1. [ ] If it's a workshop, add a `<venue>ws</venue>` tag
1. [x] Add events to their relevant SIGs
1. [x] Look at the venue listing for prior years, and ensure that the new volume titles are consistent. You can do this by clicking on the venue name from a paper page, which will take you to the vendor listing.
1. [x] Navigate to the event page preview (e.g., https://preview.aclanthology.org/icnlsp-ingestion/events/icnlsp-2021/), and page through, to see if there are any glaring mistakes
1. [x] Skim through the complete listing, looking for mis-parsed author names.
1. [x] Download the frontmatter and verify that the table of contents matches at least three randomly-selected papers
1. [x] Download 3–5 PDFs (including the first and last one) and make sure they are correct (title, authors, page numbers).

### CODE REVIEW

**Comment by davidstap** [comment]
Would it be possible to already merge main conference (with findings), and merge the workshops later? That way, when people watch Underline presentation videos they can be pointed to the corresponding paper in the Anthology.

**Comment by mjpost** [comment]
This is our plan, though ideally we'd include tutorials, industry track, and SRW in this ingestion. There are also a number of other outstanding items that I hope to have included on this PR:
- [ ] Correction of capitalization rules for names (see e.g., https://github.com/rycolab/aclpub2/issues/171)
- [ ] Upload the PDFs
- [ ] Attachments seem to be missing
- [ ] Getting ahold of the copyrights
- [ ] Uploading the raw ingestion material to our import archive

**Comment by mjpost** [comment]
Ideally we'd have all of the other volumes, but I am having trouble even getting responses from the NAACL team, and don't want to spend time on this. The only real blocker is the name parsing: if we use the current aclpub2 code, it will introduce a ton of errors, which will then create a lot of work for us down the road handling corrections.

**Comment by mjpost** [comment]
@iconstantinescu is this ready for merging?

**Review by mjpost — APPROVED** [review]

**Pull request merged**
