### PR TITLE
LDK 2023 ingestion

### PR DESCRIPTION
**Pull request by anthology-assist**

### CODE REVIEW

**Review by mjpost — COMMENTED** [review]
A number of issues:
- [ ] There are many encoding errors in the preview (see image below)
- [ ] Do you have a URL for the venue?
- [ ] Can you check with them whether there is a missing Oxford comma (e.g., "Proceedings of the 4th Conference on Language, Data**,** and Knowledge)
- [ ] In #2251 @anacastrosalgado notes that the `<venue>` tag is wrong for the main conference, can you please fix this?

image

**Comment by mjpost** [comment]
The latest data is available here, please reingest: https://drive.google.com/drive/folders/1Jo0FXoEkI1FY5I5TBu7EIKXzxoi00abH

**Comment by anthology-assist** [comment]
Requested for access to the drive.

**Comment by anacastrosalgado** [comment]
@anthology-assist Try again, please.
https://drive.google.com/drive/folders/1Jo0FXoEkI1FY5I5TBu7EIKXzxoi00abH

**Comment by anthology-assist** [comment]
Ingested under a new branch #2834 closing this one.

**Comment by mjpost** [comment]
Thanks. The venue tag is still wrong (it's "law").

@anacastrosalgado it seems this is the first LDK submission to the Anthology. Do you want to submit older proceedings, too?

**Comment by anacastrosalgado** [comment]
@mjpost Hi, Matt. No, I want to submit the data that is available here: https://drive.google.com/drive/folders/1Jo0FXoEkI1FY5I5TBu7EIKXzxoi00abH

**Comment by mjpost** [comment]
Yes, that is under review at #2834. I only meant that we could also ingest earlier LDK proceedings, if LDK wanted them in the Anthology (those would be separate issues, though).

**Comment by anacastrosalgado** [comment]
Dear @mjpost , the last version is enough (if I understand correctly).

**Pull request closed without merging**
