### PR TITLE
Ingest IJCLCLP 18 19 20

### PR DESCRIPTION
**Pull request by mjpost**
Supersedes #1384.

### CODE REVIEW

**Comment by mjpost** [comment]
This is ready, just needs approval.

**Comment by akoehn** [comment]
Are the files already there? https://aclanthology.org/2019.ijclclp-1.1.pdf e.g. does not seem to exist.

**Comment by mjpost** [comment]
No they'll be published on the 25th, one week prior to the start of the conference.

**Comment by mjpost** [comment]
Sorry, thought this was the ACL branch. The files are now there.

**Review by akoehn — APPROVED** [review]

**Pull request merged**
