### PR TITLE
Move "von" particles into last name.

### PR DESCRIPTION
**Pull request by danielgildea**
Moves many "von" particles into last name where they were part of the first name.

Now there are many warnings about unused name variants - what it the best way to fix that?

### CODE REVIEW

**Comment by davidweichiang** [comment]
`bin/clean_name_variants.py` should do it. It takes no arguments and writes a new `name_variants.yaml` to stdout.

**Comment by davidweichiang** [comment]
An additional concern is that these changes could have created name variants as well. Imagine if the existing variants are

```
{
canonical: {first: Ludwig, last: Van Beethoven},
variants: [{first: Ludwig van, last: Beethoven}]
}
```

and then `<first>Ludwig van</first> <last>Beethoven</last>` is changed to `<first>Ludwig</first> <last>van Beethoven</last>`. Then we need to add a new variant; otherwise the author's papers will be split in two.

The script `bin/change_authors.py` knows how to change author names while avoiding this problem. However, it wants the changes in a different format. Since you've already put a lot of work into this, maybe the really right thing to do is to improve `change_authors.py` so that it reads the original XML files, modified XML files, does a diff, and then tries to update name_variants.yaml in a way that's consistent with the diff.

**Comment by danielgildea** [comment]
Thanks David - I used clean_name_variants.py and then went through the diff by hand to identify both the merged name variants and the newly created name variants.

**Comment by davidweichiang** [comment]
OK good -- the change to change_authors.py is probably still a good idea, but I'm glad it's not urgent.

**Pull request merged**
