### PR TITLE
add webnlg to siggen

### PR DESCRIPTION
**Pull request by Shimorina**
Hello,

This adds the WebNLG workshop to SIGGEN.

It also fixes the volume id as mentioned in #1190 (Hope I got it right.)

### CODE REVIEW

**Comment by mjpost** [comment]
Thanks again for your sharp eye.

**Review by mjpost — APPROVED** [review]

**Comment by Shimorina** [comment]
Thank you for a speedy approval and merging!

Sorry I have some questions about the website build. Was the website fully updated? Even if [the new workshop link](https://www.aclweb.org/anthology/volumes/2020.webnlg-1/) is live, I can't see some of the changes applied on the website. For example, the page https://www.aclweb.org/anthology/sigs/siggen/ still doesn't list WebNLG. Also, the old link (https://www.aclweb.org/anthology/volumes/2020.webnlg-papers/) seems to be around. Shouldn't it disappear?
When I build the website locally, I see that everything is rendered correctly.

Thank you very much for your help!

**Comment by mjpost** [comment]
Hmm, this is strange. Actually, [the first time the job ran](https://github.com/acl-org/acl-anthology/runs/1864430759?check_suite_focus=true) it failed, but is now listed as having been run successfully. I just triggered a rebuild so hopefully that will fix it.

**Comment by Shimorina** [comment]
Thank you again! Now everything is perfect!

**Pull request merged**
