### PR TITLE
Ingested earlymt 1963 1971 1976

### PR DESCRIPTION
**Pull request by davidstap**
* 1963 (see https://aclanthology.org/www.mt-archive.info/50/AMTCL-1963-TOC.htm)
* 1971 (see https://aclanthology.org/www.mt-archive.info/70/LRC-1971-TOC.htm)
* 1976 (see https://aclanthology.org/www.mt-archive.info/70/FBIS-1976-TOC.htm)

### CODE REVIEW

**Comment by davidstap** [comment]
@mjpost this is now ready for review. I'm not sure what to do with the first 6 papers of the 1971 volume. I've treated them as separate papers for now.

**Comment by mjpost** [comment]
1963 looks good.

For 1971, it looks like the first four items ("Foreword", "Abstract", "Technical Evaluation", and "Table of Contents") are included in the fifth item ("Report"). I think items 1–4 should be removed, and "Report" should be reingested as item 1, with the name "Feasibility study on fully automatic high quality translation". This will shift all paper IDs by -4, so they should be reingested.

For 1976, it seems that "Full set of abstracts and papers" has been corrected ingested as the full-volume PDF. Per the frontmatter, I think you should add "David G. Hays" and "J. Mathias" as volume editors.

**Comment by davidstap** [comment]
@mjpost done

**Review by mjpost — APPROVED** [review]
LGTM!

**Comment by davidstap** [comment]
And that concludes the MT Archive ingestions! 🥳 thanks for merging.

**Pull request merged**
