### PR TITLE
Dec 2021 Correction

### PR DESCRIPTION
**Pull request by xinru1414**

### CODE REVIEW

**Review by danielgildea — COMMENTED** [review]
Can you re-ingest nsurl-2021 #1730 on this branch before merging?

**Comment by mjpost** [comment]
Yes, merging in the `master` branch is a good idea.

@xinru1414, once this has been approved, let’s set up a time to do the merge together.

**Comment by danielgildea** [comment]
I meant that we should fix the errors in nsurl-2021 - all the titles and authors are reversed.

**Comment by mjpost** [comment]
Oh, drat, how did I miss that. Xinru, please see [Dan’s comment here](https://github.com/acl-org/acl-anthology/pull/1730#issuecomment-1001640591).

Once that’s fixed, let’s just meet and we can go through the process.

**Review by danielgildea — APPROVED** [review]

**Pull request merged**
