### PR TITLE
add abstracts for L04-L14

### PR DESCRIPTION
**Pull request by leondz**
Main track papers in L04-L14 all gain abstracts where there is present & well-formed one on the LREC site.

### CODE REVIEW

**Comment by mjpost** [comment]
Thanks! Can you:

- Run `bin/indent.py` on each of the XML files to fix the indentation
- Fix the build (`make check` will tell you the problem)

**Comment by leondz** [comment]
Thanks, got it. Check passes, xml is formatted, and PR has been updated.

btw - bin/indent.py requires the following that aren't in bin/requirements.txt: slugify stop_words texsoup lxml

**Comment by leondz** [comment]
Thanks for the tip - it looks like '06 was the year where they started using the code for today and indeed, while 04 contains various non-main-conference items that don't have abstracts described in the standard way there (e.g. keynotes), the import is non-complete for that year.

**Comment by mjpost** [comment]
@leondz I swear somewhere you mentioned missing deps from `bin/requirements.txt`. If I am not hallucinating, do you want to just add them in your next PR?

**Comment by akoehn** [comment]
Matt Post writes:

> @leondz I swear somewhere you mentioned missing deps from
> `bin/requirements.txt`.

That was in a previous version and has been edited out – maybe the info
turned out to be related to the venv discussed in another issue?

**Comment by leondz** [comment]
@mjpost @akoehn It turned out to just be PEBKAC

**Pull request merged**
