### PR TITLE
Ingested AACL and workshops

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by mjpost** [comment]
@akoehn any idea why Travis seems to be failing / stalling on all these PRs?

**Comment by akoehn** [comment]
No, maybe it's a sign to clean up the CI pipeline and migrate to the hiring internal one. Maybe then we also don't have three checks on every pr anymore.

**Comment by mjpost** [comment]
@acl-org/anthology does someone have a minute to approve this? The conference has started.

**Review by davidweichiang — APPROVED** [review]

**Comment by danielgildea** [comment]
> any idea why Travis seems to be failing / stalling on all these PRs?

It looks like the problem is that Travis isn't free anymore!

They have a new pricing plan, which says something about being able to politely ask them for credits for OSS projects, but googling around it looks like they aren't actually giving out credits.

For the short term, I think we need to disable the required status before merging.

**Comment by akoehn** [comment]
Yes, we should disable that and the person approving a PR should run a check build on their own computer.

I have looked at how to use GitHub actions instead of travis for these checks and it seems to be quite straight-forward.  I'll push a change if I have a minute to spare.

**Comment by mjpost** [comment]
I'm worried about disabling checks because we often to break the build with minor things, and this will then in turn break auto-publishing.

**Comment by mjpost** [comment]
Also I really don't want to have to do local builds manually. This is already too time-consuming. I'm looking into paying for this for a month, but ideally we'd just switch to Github actions.

**Comment by mjpost** [comment]
@akoehn, if you do find time to do this today, it would be awesome. If not, that's okay; maybe we can just disable the checks for a short period of time. I'd like to get this backlog cleared.

**Comment by akoehn** [comment]
Matt Post writes:

> @akoehn, if you do find time to do this today, it would be awesome.

Done, see PR #1143

**Pull request merged**
