### PR TITLE
Fix first name in Shears paper

### PR DESCRIPTION
**Pull request by jpablomch**
This PR fixes an error in the author's name for the paper "Shears: Unstructured Sparsity with Neural Low-rank Adapter Search" at NAACL-24.

Juan Munoz -> Juan Pablo Munoz

### CODE REVIEW

**Comment by nschneid** [comment]
Thanks for raising this. The PDF at https://aclanthology.org/2024.naacl-industry.34/ actually says "J. Pablo Muñoz". Anthology policy is that the metadata should reflect the PDF.

**Comment by jpablomch** [comment]
> Thanks for raising this. The PDF at https://aclanthology.org/2024.naacl-industry.34/ actually says "J. Pablo Muñoz". Anthology policy is that the metadata should reflect the PDF.

Hi @nschneid , thanks for your prompt response. Yes, the J. stands for Juan -> Juan Pablo Muñoz. The current record is missing "Pablo," as included in the PDF. Please refer to the other papers by the same author, which follow this same pattern: https://aclanthology.org/people/j/juan-pablo-munoz/ 

Thank you in advance for your help.

**Review by mjpost — APPROVED** [review]

**Comment by nschneid** [comment]
I have edited the paper metadata to match the PDF. Please add an entry to name_variants.yaml so it will be listed on the same page as https://aclanthology.org/people/j/juan-pablo-munoz/

**Comment by jpablomch** [comment]
> I have edited the paper metadata to match the PDF. Please add an entry to name_variants.yaml so it will be listed on the same page as https://aclanthology.org/people/j/juan-pablo-munoz/

Thanks, @nschneid. I have added the name variants.

**Comment by jpablomch** [comment]
Hi @nschneid and @mjpost , is there anything else needed to merge this PR? Thanks in advance for your help.

**Comment by mjpost** [comment]
I hadn't noticed the followups. This looks good. Thank you!

**Pull request merged**
