### PR TITLE
check for tabs in XML, Makefile optimizations

### PR DESCRIPTION
**Pull request by akoehn**
- clean up existing tabs
 - This also removes incorrect abstract text from D19.

### CODE REVIEW

**Comment by mjpost** [comment]
Ooh, I was really hoping you were serious when you threatened to do this. I'll take a look soon.

**Comment by akoehn** [comment]
I did not threaten to do it, it was already done back then (-:  

I just thought I could also have the symlinking in place for the PR but that turned out to be problematic for different reasons -- one is that symlinking directories means that newly generated files are then populated in the origin directory so we would have to recreate the directory structure, symlink nearly all files one by one and copy some files because we change the content during deployment.

**Comment by mjpost** [comment]
On the symlinking issue, I was under the impression that directories like (for example) `hugo/layouts` don't get written to at all during the build, even after being copied. If that's not true, then yes, I can see how this might not be worth doing. For my common purposes (experimenting with the layouts), a sort of recursive file copy even just within that directory would be worthwhile, but I understand if you don't want to implement it!

**Review by mjpost — APPROVED** [review]
LGTM.

**Pull request merged**
