### PR TITLE
add pip -r bin/requirements.txt to README

### PR DESCRIPTION
**Pull request by davidweichiang**
Not sure if this is the right place to put the instruction, but I think it should go somewhere.

### CODE REVIEW

**Comment by mjpost** [comment]
Very confused about this build error, but maybe try `make autofix`?

**Comment by mjpost** [comment]
@akoehn all the builds (#975 #976 #977) are failing with messages about black formatting. They pass on my machine. Can you look into this? Maybe there's a version difference?

**Comment by akoehn** [comment]
Added to my todo list for tomorrow.

**Comment by danielgildea** [comment]
> @akoehn all the builds (#975 #976 #977) are failing with messages about black formatting. They pass on my machine.

Try `rm -rf venv` to update black.  See #826.

**Comment by mjpost** [comment]
Ah, thanks! But why did black suddenly start requiring all these changes? We haven't changed our config.

**Comment by mjpost** [comment]
To answer my own question, it seems that [black was recently updated](https://pypi.org/project/black/#history). We might want to fix the version, just to have some stability, if they are changing things this drastically.

```

**Comment by mbollmann** [comment]
There is nothing in the [change log](https://github.com/psf/black/blob/master/CHANGES.md) that would explain this, though. I just checked out `master`, updated `black` to the latest version, and it wants to change almost all of the files.

**Comment by mbollmann** [comment]
Also, a belated comment to this pull request; when using our Makefile, there is no need to install the packages manually via `pip`, so I'm not actually sure I would've put this line into the README here.

**Comment by mbollmann** [comment]
> Also, a belated comment to this pull request; when using our Makefile, there is no need to install the packages manually via `pip`, so I'm not actually sure I would've put this line into the README here. It's not technically a prerequisite like the others are.

**Comment by mbollmann** [comment]
Update: I've found that the changes from black arose because it doesn't find our `bin/pyproject.toml` anymore.

This could be because, according to its documentation, it looks for the file "starting from the common base directory of all files and directories passed on the command line". There is now a file `test/test_indent.py` that is also passed to black, so `bin/` is not the common base directory anymore.

Moving `bin/pyproject.toml` to the root folder essentially reverts all the changes that were introduced in 9a4574c. I'll create an issue and PR.

**Comment by mjpost** [comment]
Ah, thanks for taking a careful look at this, Marcel. I was way too hasty in trying to get this out of the way.

**Comment by davidweichiang** [comment]
> Also, a belated comment to this pull request; when using our Makefile, there is no need to install the packages manually via pip, so I'm not actually sure I would've put this line into the README here. It's not technically a prerequisite like the others are.

I was wondering about that; in this case, I was talking to someone who was trying to write a new script that imports the Anthology modules, so it might have been inconvenient for them to use the Makefile to do this.

**Pull request merged**
