### PR TITLE
More explicit XML representations

### PR DESCRIPTION
**Pull request by mbollmann**
This PR introduces some changes that represent more data explicitly in the XML, rather than inferring it at runtime in the Python library. Concretely:

1. Gets rid of inferred publication years, and makes the `<year>` tag mandatory.
2. Adds `type="proceedings"` or `type="journal"` to all volumes. (#2379)
3. Adds `<journal-issue>`, `<journal-volume>`, `<journal-title>` tags. (#2379)

### CODE REVIEW

**Review by mjpost — APPROVED** [review]
This looks great.

**Comment by mbollmann** [comment]
@mjpost Thanks. Do you have an opinion on #2379 and how difficult the questions there would be to settle? I would really like to address this too here, if possible.

**Comment by mjpost** [comment]
lol 
image

**Comment by mbollmann** [comment]
> lol image

You know the feeling :)

**Comment by mbollmann** [comment]
I've synced this with master and think I shouldn't add any more features to this PR now as it's already a pretty substantial change. This should be ready for review now. @mjpost

**Comment by mbollmann** [comment]
I've synced this with master and think I shouldn't add any more features to this PR now as it's already a pretty substantial change. This should be ready for review now. @mjpost

**Comment by mjpost** [comment]
I looked over the code and don't see any obvious problems. I'll let you merge!

**Comment by mbollmann** [comment]
We do need to remember to update ingestion scripts, though. Although for the time being, running `python bin/make_journals_explicit.py -c` should add all the required changes on existing branches. @anthology-assist

**Comment by mjpost** [comment]
Thanks! CC'ing @anthology-assist on this. 

We now have three scripts that need to be run after ingestion:
* Writing bibkeys
* Fixing unmatched abstract braces
* Making journals explicit
We should merge these into the aclpub2 ingestion script directly. I started to do this for bibkeys, but getting the `Anthology` data structures set up correctly is a bit involved, and I ran out of time.

**Pull request merged**
