### PR TITLE
More TeX-math support

### LINKED ISSUE #1244: tex-math build errors
Builds complain with the following errors. Can we:

1. Manually fix them
2. (Time-permitting) update the ingestion code to handle them better? (This is less important and I don't want it to be a blocker, but maybe some of these are easy)

```text
WARNING  Unknown TeX-math command: \sim9k
WARNING  Unknown TeX-math command: \cal
WARNING  Unknown TeX-math command: \#Turki
WARNING  Unknown TeX-math command: \Pr
WARNING  Unknown TeX-math command: \rm{P}
WARNING  Unknown TeX-math command: \rm{Y}
WARNING  Unknown TeX-math command: \text{Petersen}
WARNING  Unknown TeX-math command: \text{CAPTURE}
WARNING  Unknown TeX-math command: \text{Schnabel}
```

### PR DESCRIPTION
**Pull request by mbollmann**
Adds support for `\textrm{}`, `\mathrm{}`, `\boldsymbol{}`, `\%`, and fixes two instances of TeX-math commands in the XML.

[Before](https://aclanthology.org/2021.acl-long.430/):

image

[After](https://preview.aclanthology.org/more-texmath-support/2021.acl-long.430/):

image

Re #1244

### CODE REVIEW

**Comment by davidweichiang** [comment]
#1244 mentions `a_\alpha` as a problem case -- that's still a problem, right?

**Comment by mbollmann** [comment]
> #1244 mentions `a_\alpha` as a problem case -- that's still a problem, right?

Ah, I didn't realize this wouldn't show up as a warning during the build ... thanks for catching that.

I still don't really know how we would handle this programmatically, though, seeing that texsoup doesn't handle it and [my own code for this very hacky](https://github.com/acl-org/acl-anthology/blob/200e57de9b31afa07aaedfd755a1b97555d57364/bin/anthology/texmath.py#L167-L181). I'll give it a thought, but welcome ideas.

**Comment by davidweichiang** [comment]
Maybe we should just file this as an issue for TeXSoup and wait for them to fix it.

**Review by davidweichiang — APPROVED** [review]

**Comment by mbollmann** [comment]
I'll check our options, but have removed the closing of #1244 from this PR for now.

**Pull request merged**
