### PR TITLE
S19-2003 abstract (#438)

### PR DESCRIPTION
**Pull request by nschneid**

### CODE REVIEW

**Comment by mjpost** [comment]
Do you know what’s going on with the checks? I thought I hadn’t approved it but it seems it’s something with Travis. Maybe try pushing a meaningless change to trigger a rebuild?

**Comment by mbollmann** [comment]
Off-topic, but: I researched this issue and found this, which suggests the way we're triggering Travis CI at the moment is actually deprecated:
https://github.com/travis-ci/travis-ci/issues/10204

**Comment by mjpost** [comment]
Oh, thanks, @mbollmann! I just changed these settings.

**Comment by mjpost** [comment]
I wonder if this will affect / resolve #365.

**Comment by mjpost** [comment]
@nschneid I can't merge this until the Travis build passes, and I can't trigger a rebuild because I can't push to your branch. If you can push a dummy change it should build okay.

**Comment by nschneid** [comment]
The Travis build passed. Do you know what "Expected — Waiting for status to be reported" means?

**Comment by mjpost** [comment]
No. But I solved this by removing the Travis build for branches.

**Pull request merged**
