### PR TITLE
Link to local videos instead of Vimeo

### PR DESCRIPTION
**Pull request by davidstap**
I've downloaded Vimeo videos and stored them on the Anthology server. This pull request replaces links to Vimeo with local links. See #2637 for more details.

Progress:

- [x]  D15.xml (97/97 vimeo video links to server)
- [x]  D16.xml (100/100 vimeo video links to server)
- [x]  D17.xml (93/94 vimeo video links to server, 1 points to dead link)
- [x]  D18.xml (220/222 vimeo video links to server, 2 point to dead link)
- [x]  N15.xml (3/3 vimeo video links to server)
- [x]  N18.xml (119/119 vimeo video links to server)
- [x]  N19.xml (115/213 vimeo video links to server, 98 point to dead link)
- [x]  P17.xml (140/141 vimeo video links to server, 1 points to dead link)
- [x]  P18.xml (185/185 vimeo video links to server)
- [x]  P19.xml (244/244 vimeo video links to server)
- [x]  Q14.xml (13/13 vimeo video links to server)
- [x]  Q15.xml (12/12 vimeo video links to server)
- [x]  Q16.xml (9/9 vimeo video links to server)
- [x]  Q17.xml (27/27 vimeo video links to server)
- [x]  Q18.xml (25/26 vimeo video links to server, 1 points to dead link)
- [x]  Q19.xml (13/13 vimeo video links to server)
- [x]  W18.xml (2/2 vimeo video links to server)

Totals: 1417 successfully downloaded videos, 103 dead vimeo links 

- [x] means xml file is updated and committed.

### CODE REVIEW

**Comment by mjpost** [comment]
Awesome, that was fast!

**Comment by mjpost** [comment]
@davidstap I know there were a lot of plenary videos and others not associated with a paper—are those downloaded to the server as well?

**Comment by davidstap** [comment]
@mjpost No these are not downloaded to the server; I have only downloaded videos with an Anthology ID. Are all these plenary videos stored in dropbox? Is there an easy way to find all of them?

**Comment by davidstap** [comment]
@mjpost Also, it turns out that there are quite a few missing videos. Most of these are dead Vimeo links, such as [this video](https://vimeo.com/238231072) for [this paper](https://aclanthology.org/D17-1021/). For the cases I checked they are also unavailable on dropbox. Is there any way to get the videos, or should I remove the video links?

**Comment by anthology-assist** [comment]
#3121 might be related to this as well?

**Review by mjpost — APPROVED** [review]
Looks good; I spot-checked a number of them.

**Pull request merged**
