### PR TITLE
fixed-case: Abstract Meaning Representation in titles

### PR DESCRIPTION
**Pull request by nschneid**

### CODE REVIEW

**Comment by mjpost** [comment]
Ideally we'd add this to `bin/fixedcase/truelist` as well, but I think we don't support phrases yet, right?

**Comment by nschneid** [comment]
Not to my knowledge. Should I start a file `bin/fixedcase/truelist-phrases` for future reference?

**Comment by mjpost** [comment]
Yes—see also David's comment on #326 (he didn't think it'd be that hard to add phrasal support to the fixed caser. This would be a nice time to handle it, but if you can't or don't want to, adding a phrasal file will be helpful.

**Comment by nschneid** [comment]
I'll put it on my list to investigate when I have a free chunk of time. Created truelist-phrases for now.

**Pull request merged**
