### PR TITLE
Ingestion: gwc 2023

### PR DESCRIPTION
**Pull request by anthology-assist**

### CODE REVIEW

**Comment by arademaker** [comment]
the `meta` file contains a field for `chairs`, I filled with the conference chairs. But as in the previous years, I consider myself also one of the editors of the proceedings. The field `chairs` is transformed in the XML in the editors?

https://github.com/acl-org/acl-anthology/pull/2861/files#diff-d19b35008c049e53e5104b9b086d055412307c039c15ee20c524d82e7b4cdf21R6-R7

I am fine to leave this as it is now, my name can be only in the PDF frontpage. But this can be revised in the future?

FYI @fcbond

**Comment by mjpost** [comment]
Yes, the `chairs` field is used for editors. We can simply add you if you are missing. What name, and what position in the list?

**Comment by arademaker** [comment]
You can add “Alexandre Rademaker” as the last name in the list of editors.

**Comment by arademaker** [comment]
Can I make the pending review? We are really too late with this proceedings. Sorry to insist.

**Comment by mjpost** [comment]
Thanks for pushing. Looks good, I'll merge now.

**Review by mjpost — APPROVED** [review]

**Comment by mjpost** [comment]
Should be live in 20 minutes or so...

**Pull request merged**
