### PR TITLE
Paper Metadata: 2024.acl-long.622

### PR DESCRIPTION
**Pull request by zolastro**
Modify the BibKey to match previous paper by the same author: [see example](https://aclanthology.org/2023.acl-short.67/).

### CODE REVIEW

**Review by nschneid — CHANGES_REQUESTED** [review]
Comparing the author names to https://aclanthology.org/2024.acl-long.622.pdf, I see that "Jesus" should be "Jesús". Could you please fix that as well?

**Comment by mjpost** [comment]
Yes, please add that change and push to this branch, and then we can merge.

**Comment by zolastro** [comment]
I've already made the changes. After consulting with Calleja, he confirmed that his preference is for his name to appear as "Jesús Calleja". Along these lines, could you also update his ACL profile [Jesus Javier Calleja Perez](https://aclanthology.org/people/j/jesus-javier-calleja-perez/) to "Jesús Calleja"?

**Comment by mjpost** [comment]
This will happen automatically when this PR is merged.

**Review by mjpost — APPROVED** [review]

**Pull request merged**
