### PR TITLE
Adds the information required for .bib files to include a 'month' field.

### PR DESCRIPTION
**Pull request by villalbamartin**
This is the code for the simple fix mentioned in issue #94. The code changes the `dateIssued` field of the MODS XML file from `yyyy` to `yyyy-mm` (if the month is available). Down the line, and once we run `xml2bib` (or similar utilities), this adds a `month` field to the exported files.

### CODE REVIEW

**Comment by mjpost** [comment]
LGTM. This doesn't cover month ranges, though, right? So from MODS format, we can't handle the concatenation case mentioned in #94?

**Comment by villalbamartin** [comment]
Exactly - I made this pull request mostly to continue the conversation, and to reach a consensus about what we want to do.

If we accept the PR as it is, then `month` will have to be a single month unless someone finds a way for `xml2bib` and friends to generate custom fields. I imagine that replacing the `dateIssued` field with a string field could give us what we want, at the cost of replacing a date (which means something specific) with a string (which has no meaning by itself). And of course, we need to make it in a way that doesn't break the other export formats.

My original idea was "let's stick to the standard", but as it happens there is really no standard for this. On one hand, most discussions I found agree that `month` should contain the publication date, and therefore should be a single point in time. On the other hand, `bibtex` added explicit support for date ranges over 30 years ago, which I take as an acknowledgement that people have been using this field differently for a long time.

Thoughts on this?

**Comment by mjpost** [comment]
It seems to me that the current process of generating the official BibTeX files from MODS XML via `xml2bib` is going to limit us in important ways. This suggests an idea we've discussed in Issue #90 which is to generate the official bib directly from the *imported* XML, instead. To do this we'd need to generate our own script, which strikes me as something that shouldn't be too hard, it being a road traveled by many before. What do you think?

**Comment by villalbamartin** [comment]
I see two main challenges in generating .bib directly by ourselves: dealing with the .bib format, and dealing with the other export formats we have.

As far as the first issue goes, I imagine we would have to implement the proper escaping rules - I don't know how we are currently ensuring that "Henry Ford Jr." is being exported as "Ford, Jr., Henry" (per the LaTeX manual), but I'm very happy that I didn't need to think about this until now. Luckily we could perform automated tests for this, since we do have valid .bib to contrast.

The second issue is dealing with all the other export formats: if we generate our own .bib then we will either have inconsistent bibliography across formats or we will have to write code for all of them. I have toyed with the idea of only supporting .bib, but I ran a quick check over our logs, and for 5 days we have:

Format | Requests | Requests minus "bot"
-------|---------|----------------
.bib | 32K | 5921
.xml | 12K | 571
.endf | 7K | 74
.word | 7K | 109
.ris | 6K | 83

One way or another, MODS XML seems to be our second most popular format, so we might want to keep supporting it.

Finally, here's a crazy idea: what if we modify the code of the `bibutils` package to support this month feature, and then we use those binaries instead of the ones we have in the repo? I imagine the changes would be relatively small, and we could also share the patch.

**Comment by mjpost** [comment]
> As far as the first issue goes, I imagine we would have to implement the proper escaping rules - I don't know how we are currently ensuring that "Henry Ford Jr." is being exported as "Ford, Jr., Henry" (per the LaTeX manual), but I'm very happy that I didn't need to think about this until now. Luckily we could perform automated tests for this, since we do have valid .bib to contrast.

The authoritative XML contains separate fields for first name and last name, so this part should be easy.

I agree that we should support other citation formats, and I don't want to write custom formatters for them. What about

    XML → bib # (via a custom Python script)
    XML → MODS XML → * # for everything else

I am also open to your idea of modifying `xml2bib`. Do you know if MODS XML + `xml2bib` supports inclusion of the abstracts?

**Comment by mjpost** [comment]
I'm closing this out since it will be handled in the static rewrite. Feel free to reopen if there is more to say on this.

**Pull request closed without merging**
