### PR TITLE
restore --delete to rsync

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by mbollmann** [comment]
So just to confirm, the PDFs etc. are stored outside of `/var/www/aclanthology.org` on the server?

**Comment by mjpost** [comment]
Yes, thanks for doing one final check. They are stored under /mnt, and there are no symlinks, so all is well. Thanks for this PR!

**Review by mbollmann — APPROVED** [review]
LGTM

**Comment by akoehn** [comment]
> Yes, thanks for doing one final check. They are stored under /mnt, and there are no symlinks, so all is well.

Just to be correct: there *is* a symlink, but we generate that symlink in the generation process and rsync it as well.

**Pull request merged**
