### PR TITLE
Allow null/empty first name

### PR DESCRIPTION
**Pull request by aryamccarthy**
We'll see how this turns out—Mausam has only one name. Not split between given and surnames.
`~` is the syntax for a null value in YAML.

This hopes to unify these pages: https://aclweb.org/anthology/people/m/mausam/ and https://aclweb.org/anthology/people/m/mausam1/.

### CODE REVIEW

**Comment by aryamccarthy** [comment]
Okay, this warrants a bit of discussion. Should we render the page with no first-name field, or should we leave that field blank?

**Comment by mbollmann** [comment]
I'm not sure I follow your second comment.

The build failure is clearly a bug. The XML schema makes it clear that the first name is optional, and while my code contains some checks to handle missing first names, I think overall it doesn't handle them quite correctly yet.

**Comment by aryamccarthy** [comment]
Right—my second comment was to ask whether, for the sake of smooth sailing, we should just use `""` as the first name here. Sounds like no?

**Comment by mbollmann** [comment]
For one, that should be the current behavior already if you just omit the `first` key. But then, there may be other issues that are not properly handled in this case yet, and we could use this as an opportunity to fix them. For example, the BibTeX output will still generate "Mausam, ".

**Comment by davidweichiang** [comment]
I have this question too. There are
other people with only one name and they’re not consistently handled.

Also, for corporate authors like “The PLUM Group” it’s not clear what to do.

**Comment by davidweichiang** [comment]
Also, I think we don't have `~` as his first name anywhere in the XML, right? (Maybe I deleted it?)

**Comment by davidweichiang** [comment]
Is it ok to close this?

**Comment by mbollmann** [comment]
Why? I don't think we've addressed the issue yet, or have we?

**Comment by davidweichiang** [comment]
Oh sorry, the original issue (an entry for Mausam in `name_variants.yaml`) is gone, because there are no more variant spellings of his name, but the other issues raised here stand.

**Comment by davidweichiang** [comment]
The above commit changes a null first name into `""`, and the BibTeX rendering handles the empty first name correctly.

Is that okay, or do we need to distinguish between a null vs. empty name? Even [Falsehoods Programmers Believe About Names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) doesn't envision that possibility! 

Note that before merging, the variant "-, Mausam" should be dropped. This is a stopgap fix introduced by START; it's been fixed (https://github.com/acl-org/ACLPUB/commit/d8756ad9e0da55729619015c340f4510ff25c80f) and we won't ask authors to use the hyphen any more.

However, now I think it's possible that either the first name or last name coming out of START can be empty. According to #237 we should collapse both cases to last-name-only, but I don't think that happens anywhere yet.

**Comment by davidweichiang** [comment]
I think this could be merged now. I think anthologize should be modified to handle the first name only case.

**Pull request merged**
