### PR TITLE
Fixes & Search Documentation

### PR DESCRIPTION
**Pull request by mbollmann**
An assortment of bug fixes, and some documentation on the search results page.

The exact content/presentation of the search documentation is up for discussion, of course.

### CODE REVIEW

**Comment by mjpost** [comment]
Instead of adding a special case for C69, can we just fix the XML? I think we could just do them as single volume ID `C69-01`, numbering from 1 upward. I can then rotate the PDFs.

**Comment by mbollmann** [comment]
Sure, that would be ideal. (Though the ID should be `C69-1`, without a leading zero.)

**Comment by mjpost** [comment]
Do you want to remove the special case-handling for C69? I'd like to merge this other stuff, and I'm worried that it will get forgotten when we fix #147 or that not seeing it will reduce the desire to address it.

**Comment by mbollmann** [comment]
C69 is completely broken at the moment (i.e., most papers are not actually accessible right now), so I think it's better to have this hotfix. It doesn't change the core problem anyway; C69 still will still look weird on the website, but at least the papers will all be there.

(Also, when we address #147 properly, not changing this code would lead to visible problems again. ;))

**Comment by mjpost** [comment]
Okay, sounds good.

**Pull request merged**
