### PR TITLE
Added WS links for 2020--2021 (closes #2180)

### LINKED ISSUE #2180: Add workshop links
Prior to 2020, workshops were automatically gathered under the "ws" venue tag, such that one could easily peruse all workshops in a given year (e.g., [2019](https://aclanthology.org/events/ws-2019/)). With 2020's new ID system, that linkage is no longer automatic, and while we seemed to do this for a bit in 2020, we haven't in 2021 and 2022. This removes a feature that some people have found useful.

We should go back and, for all main conference venues (NAACL, ACL, EMNLP, CoNLL, and COLING), add each workshop as joint with "ws" in `data/yaml/joint.yaml`.

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by xinru1414** [comment]
@mjpost are these workshops supposed to be unlinked from their associated venues (see comment in #2180)? For futuure conferences, do we only link workshops under `ws`, or both `ws` and their associated venues?

**Comment by mjpost** [comment]
* Every volume post-2019 is automatically linked to its actual venue because of the new ID format 
* Old-style volumes are manually linked with their venues (eg, W19-52 with wmt)
* Volumes are also listed under the major event they were collocated with (eg, 2022.autosimtrans-1 with naacl)
* Newly, we link all workshops with "ws"

This is all done via the "joint.yaml" file, even though these are very different concepts. Soon, I will refactor this (see #1896 and discussion)

**Review by xinru1414 — APPROVED** [review]
LGTM

**Comment by xinru1414** [comment]
@mjpost OK thanks for the explanation. I completely missed #1896.

**Pull request merged**
