### PR TITLE
DOIs for EMNLP and workshops

### PR DESCRIPTION
**Pull request by xinru1414**

### CODE REVIEW

**Comment by mjpost** [comment]
Hi, this should include all the EMNLP workshops, too (look in joint.yaml).

**Comment by mjpost** [comment]
Can you merge in master so the diff is correct?

**Review by mjpost — APPROVED** [review]
LGTM. I checked

* 10.18653/v1/2021.cinlp-1.4
* 10.18653/v1/2021.crac-1.12
* 10.18653/v1/2021.econlp-1.12
* 10.18653/v1/2021.insights-1.3
* 10.18653/v1/2021.mrqa-1.8
* 10.18653/v1/2021.emnlp-main.14

**Comment by mjpost** [comment]
Where is sustainlp?

**Comment by xinru1414** [comment]
> This is missing:
> 
> * [ ]  sustainlp
> * [ ]  the DOI script should output an error if the author or editor list is empty (the mistake you encountered)

@mjpost I left out sustainlp for now because I checked three places (`2021.sustainlp.xml` , https://aclanthology.org/2021.sustainlp-1.0.pdf and the bib file for sustainlp-1.0) and no editors can be found. Should I list the organizers as chairs, or get in touch with them?

I'll work on updating the script.

**Comment by mjpost** [comment]
I would add the organizers listed here: https://sites.google.com/view/sustainlp2021/organization

Then email then to confirm.

**Comment by mjpost** [comment]
This is stalled until

- [ ] the HTTPS cert is fixed (#1749)
- [ ] someone runs `./add_dois.py 2021.sustainlp-1` and commits the changes

**Review by mjpost — APPROVED** [review]

**Pull request merged**
