### PR TITLE
gurt 23 ingestion

### PR DESCRIPTION
**Pull request by xinru1414**

### CODE REVIEW

**Comment by nschneid** [comment]
https://preview.aclanthology.org/gurt-23-ingestion/sigs/sigparse/

- [ ] TLT editors: should be Lori Levin (not Levine)
- [ ] [This Depling paper](https://preview.aclanthology.org/gurt-23-ingestion/2023.depling-1.1/): typo in author's name (also in PDF): Wulff, not Wullf
- [ ] The full proceedings PDFs have the TEMPLATETITLE issue. Maybe we don't have a way to fix this?
- [ ] no bibtex - has it just not been generated yet?

**Comment by nschneid** [comment]
CC: @ddakota

**Comment by ddakota** [comment]
@nschneid the tlt issue is fixed in the yaml and new version in the drive. I wrote the authors of that paper to request a new pdf and can fix the yaml when I receive it.

**Comment by ddakota** [comment]
@xinru1414 new versions of the tlt and depling tgz are in the drive that correct the two points above
cc: @nschneid

**Comment by nschneid** [comment]
Are we all set here?

**Comment by mjpost** [comment]
Is the TEMPLATETITLE issue resolved? I don't see any outline at all in my PDF reader.

We don't generate bibtex on previews to save time and space (hundreds of thousands of files).

**Review by mjpost — APPROVED** [review]

**Comment by xinru1414** [comment]
@mjpost same here, I don't think the TEMPLATETITLE is an issue.

**Pull request merged**
