### PR TITLE
Build preview for papers with code 

### PR DESCRIPTION
**Pull request by mjpost**
Adding this to get a build preview for #1635.

### CODE REVIEW

**Comment by mbollmann** [comment]
XML schema needed updating, and of course the `ingest_pwc.py` needed to be run once before any actual changes appear on the preview. Let's see now!

**Comment by mbollmann** [comment]
I've added a workflow that would commit daily updates. I tested it on a fork of the repo, it generates commits like this:

https://github.com/mbollmann/acl-anthology/commit/0bd14add40f37dd80b1d27216b446181c16c1f60

I've set it to run daily at 0:30 UTC, but that can be changed to something else of course.

**Comment by mjpost** [comment]
This is so cool, and even already [has EMNLP papers](https://preview.aclanthology.org/pwc/events/emnlp-2021/).

I think we’re set to merge this, right? Is there anything I’m not thinking of?

**Comment by mjpost** [comment]
Merged in #1635.

**Pull request closed without merging**
