### PR TITLE
Update 2021.americasnlp.xml

### PR DESCRIPTION
**Pull request by hayleypark**
I'd like to update my name from "Hyunji Park" to "Hyunji Hayley Park".
The pdf version actually has the later name, so I just want to update the meta data for consistency among my papers.

### CODE REVIEW

**Review by xinru1414 — APPROVED** [review]
LGTM

**Comment by hayleypark** [comment]
Thanks!

**Comment by hayleypark** [comment]
Sorry I mistakenly closed the pull request :( Can someone help me merge this pull request?

**Comment by mjpost** [comment]
Done. Thanks for the PR!

**Pull request merged**
