### PR TITLE
ACL 2019

### PR DESCRIPTION
**Pull request by mjpost**
This will go live on 2019-07-28 at 0:00 UTC+14, so it should not be merged until Friday.

Ambiguous names cause problems because (a) they create a build error and (b) they are time-consuming to resolve manually. Here, I resolve them automatically, by selecting the shortest ID. It would be great to be able to resolve this automatically by including more information in the `<author>` tags.

I also removed an author who had an ID, but no ambiguous names (just surface variants). These also slow down the ingestion by requiring manual intervention, but it is only ambiguity that is the problem at ingestion time.

### CODE REVIEW

**Comment by mjpost** [comment]
@davidweichiang it would be good for you to look at the name change stuff.

**Comment by davidweichiang** [comment]
Is there an easy way to search for where you've done the shortest-ID thing? What do you mean by more information in the `<author>` tags?

**Comment by davidweichiang** [comment]
Maybe we should officially adopt a convention (already followed de facto) where the unadorned id is the "leftover" id for author occurrences that haven't been disambiguated yet.

**Comment by mjpost** [comment]
I added a `get_ids()` function to `index.py` ([link](https://github.com/acl-org/acl-anthology/blob/c768ff5c6fd1100840a4a706979cd7a7dea5c637/bin/anthology/index.py#L266)).

I mean that currently, ingestion just takes the `<paper>` entries and adds them to the Anthology. When you build, you get an error if an `<author>` is ambiguous and needs an ID. But if the ACLPUB-outputted data included more information, then when a `PersonName` is created from the `<author>` tag, it could make use of other tags in order to help disambiguate an author name and choose the right `id` attribute. In my PR here, `ingest.py` uses `get_ids()` to find all the IDs for a name. `get_ids()` returns them in sorted order. If there is ambiguity (len > 1), it just assigns the first name.

**Comment by mjpost** [comment]
Yes, using the unadorned version of the ID in this way is a great idea.

**Comment by mjpost** [comment]
That's effectively what I do here in this PR. We might want to update the HTML page to clarify that this is what we are doing. That is, instead of saying "Other people with similar names", it would read something like "Disambiguated people with this name". e.g., [Yang Liu](https://www.aclweb.org/anthology/people/yang-liu).

**Comment by davidweichiang** [comment]
I can't access the papers, but it should be relatively easy on your end to confirm that W19-4449 is Yang Liu at LAIX -- can you do that?

**Comment by mjpost** [comment]
You mean W19-4450? Yes, Yang Liu of LAIX. Same for 4416.

**Pull request merged**
