### PR TITLE
add Github pull-request check workflow, remove travis

### PR DESCRIPTION
**Pull request by akoehn**
By popular demand.

Tested it on my clone, see https://github.com/akoehn/acl-anthology/pull/1

@mjpost  I deleted the .travis.yml but I don't know whether there is other integration that can now be disabled as well.

### CODE REVIEW

**Comment by akoehn** [comment]
Ha, you can already see the check of the PR in this PR!

**Comment by mjpost** [comment]
Awesome, Arne, thank you so much! Now can you make it run two more times redundantly, for old time's sake? :) 

I deleted the Travis webhook, but it still seems to require it on this PR. Maybe that decision is made when the PR is created?

**Comment by akoehn** [comment]
Probably. You will have to do your magic to enable merging for this PR.

**Comment by mjpost** [comment]
Looks like a push didn't shake the Travis CI. I think you may have to create a new PR, now that the webhook has been disabled.

**Comment by akoehn** [comment]
aah, the dummy commit is in this one as well now, I will push a new branch.

**Comment by mjpost** [comment]
I was just going to remove it and then squash-merge. Sorry for all the churn.

**Pull request closed without merging**
