### PR TITLE
ingested iwslt 2015

### PR DESCRIPTION
**Pull request by davidstap**
See https://aclanthology.org/www.mt-archive.info/15/IWSLT-2015-TOC.htm for original.

### CODE REVIEW

**Comment by xinru1414** [comment]
I think

- https://preview.aclanthology.org/ingest-iwslt-2015/volumes/2015.iwslt-keynotes/
- https://preview.aclanthology.org/ingest-iwslt-2015/volumes/2015.iwslt-papers/
- https://preview.aclanthology.org/ingest-iwslt-2015/volumes/2015.iwslt-evaluation/

should be combined to one page since the OG site includes all of them. Otherwise LGTM

**Comment by davidstap** [comment]
I think in this case the OG site is wrong, since the IWSLT proceedings are typically split up by an Evaluation Track + Technical Papers track. See for instance the original proceedings listed at the IWSLT 2015 website: https://workshop2015.iwslt.org/downloads/proceeding.pdf 

In this case, the Evaluation Campaign and Technical papers are split, and I think we should follow this. Do you agree?

**Comment by mjpost** [comment]
I agree, three volumes here is appropriate.

**Review by xinru1414 — APPROVED** [review]
All good!

**Pull request merged**
