### PR TITLE
aacl 2022 ingestion

### PR DESCRIPTION
**Pull request by xinru1414**

### CODE REVIEW

**Comment by xinru1414** [comment]
Waiting on `demo` and `tutorials`

**Comment by mjpost** [comment]
@xinru1414 when this is ready please convert it from draft. I'll first merge #1896 first and will then rebuild this on top of it.

**Comment by mjpost** [comment]
@xinru1414 is this ready?

**Review by mjpost — APPROVED** [review]

**Comment by xinru1414** [comment]
@mjpost Yes!

**Pull request merged**
