### PR TITLE
Added SIGDIAL 2020

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by mjpost** [comment]
We don't have a Yang Liu @ Amazon, so I'm not sure if [paper #35](https://www.aclweb.org/anthology/2020.sigdial-1.35.pdf) is a new Yang Liu.

**Comment by davidweichiang** [comment]
It appears to be ICSI Yang Liu: https://cs.utdallas.edu/people/faculty-alumni/liu-yang/

**Comment by davidweichiang** [comment]
And now I just realized (sorry, Yang) that her PhD was from Purdue, not ICSI.

**Comment by mjpost** [comment]
Ah, thanks. I'll add this affiliation to the name variants file. 

How did we come to assign the "ICSI" identifier to her? I had thought we were using the Ph.D. institution in the ID (no matter, just trying to understand).

**Pull request merged**
