### PR TITLE
Proposed update to authorship changes policy

### PR DESCRIPTION
**Pull request by mjpost**
This is a draft policy update under discussion in #1873.

### CODE REVIEW

**Comment by mbollmann** [comment]
Might want to clarify in that section under what circumstances name changes are okay (i.e., an author changing their name, not a name being changed as a result of mismatching the PDF). Treating the PDF as authoritative could sound like we don't accept such name changes otherwise.

**Comment by mjpost** [comment]
That's a good point. Name changes are a separate issue that generally require an updated PDF, anyway. I removed this item and altered the title, which I hope helps clarify that this item is separate from actual name changes.

**Review by akoehn — CHANGES_REQUESTED** [review]
Looks good.

The issue template needs to be changed as well to reflect the new policy:
https://github.com/acl-org/acl-anthology/blob/master/.github/ISSUE_TEMPLATE/file-a-correction.md

**Comment by mjpost** [comment]
@akoehn thanks for noticing this, done.

**Review by akoehn — APPROVED** [review]
LGTM :-)

**Pull request merged**
