### PR TITLE
Add ruff as a code linter

### PR DESCRIPTION
**Pull request by mbollmann**
We currently use [black](https://github.com/psf/black) as a code formatter, but don't use any other type of linting. Recently, [ruff](https://github.com/charliermarsh/ruff) has become popular as a Python linter, being incredibly fast and currently used by pandas, SciPy, HuggingFace's libraries, and many others.

I think there's a good argument for using a linter in our codebase, and ruff might be fast and versatile enough to consider adding.

For example, if I run ruff on the files in `bin/anthology/` (only disabling "E501 Line too long", because that's already black's job), I get:

```
bin/anthology/__init__.py:1:24: F401 [*] `.anthology.Anthology` imported but unused
bin/anthology/__init__.py:2:21: F401 [*] `.people.PersonName` imported but unused
bin/anthology/__init__.py:3:21: F401 [*] `.papers.Paper` imported but unused
bin/anthology/__init__.py:4:22: F401 [*] `.volumes.Volume` imported but unused
bin/anthology/anthology.py:22:22: F401 [*] `datetime.datetime` imported but unused
bin/anthology/anthology.py:23:8: F401 [*] `pytz` imported but unused
bin/anthology/anthology.py:31:20: F401 [*] `.utils.is_newstyle_id` imported but unused
bin/anthology/anthology.py:31:36: F401 [*] `.utils.infer_year` imported but unused
bin/anthology/bibtex.py:15:8: F401 [*] `copy` imported but unused
bin/anthology/bibtex.py:16:8: F401 [*] `re` imported but unused
bin/anthology/bibtex.py:18:1: E401 Multiple imports on one line
bin/anthology/data.py:40:1: E722 Do not use bare `except`
bin/anthology/index.py:25:24: F401 [*] `.formatter.bibtex_encode` imported but unused
bin/anthology/index.py:27:21: F401 [*] `.venues.VenueIndex` imported but unused
bin/anthology/index.py:390:17: E713 [*] Test for membership should be `not in`
bin/anthology/latexcodec.py:94:21: E722 Do not use bare `except`
bin/anthology/latexcodec.py:110:25: F821 Undefined name `unicode`
bin/anthology/latexcodec.py:117:21: F821 Undefined name `unicode`
bin/anthology/latexcodec.py:212:24: F821 Undefined name `unichr`
bin/anthology/latexcodec.py:215:24: F821 Undefined name `unichr`
bin/anthology/latexcodec.py:218:24: F821 Undefined name `unichr`
bin/anthology/papers.py:26:5: F401 [*] `.utils.remove_extra_whitespace` imported but unused
bin/anthology/papers.py:28:5: F401 [*] `.utils.is_volume_id` imported but unused
bin/anthology/people.py:17:8: F401 [*] `logging` imported but unused
bin/anthology/sigs.py:118:16: E713 [*] Test for membership should be `not in`
bin/anthology/texmath.py:151:35: F821 Undefined name `code`
bin/anthology/utils.py:36:1: E731 [*] Do not assign a `lambda` expression, use a `def`
bin/anthology/utils.py:144:16: F401 [*] `ssl` imported but unused
bin/anthology/utils.py:378:5: F841 [*] Local variable `old_text` is assigned to but never used
bin/anthology/venues.py:19:18: F401 [*] `copy.deepcopy` imported but unused
bin/anthology/venues.py:21:20: F401 [*] `typing.List` imported but unused
bin/anthology/volumes.py:18:8: F401 [*] `re` imported but unused
bin/anthology/volumes.py:19:8: F401 [*] `logging` imported but unused
bin/anthology/volumes.py:27:5: F401 [*] `.utils.is_newstyle_id` imported but unused
Found 34 errors.
[*] 25 potentially fixable with the --fix option.
```

This looks overall quite useful to improve our code and keep it cleaner. This PR serves as an example of how it could be added.

Thoughts?

### CODE REVIEW

**Comment by mjpost** [comment]
Thanks for adding this! Looks like good hygiene to me.

**Comment by akoehn** [comment]
Good idea. Maybe we should fix the ruff version (similar to black) to not suddenly have our builds fail because a new version is complaining about something new.

**Comment by mbollmann** [comment]
Alright, here are some commits that should hopefully satisfy the ruff linter, so you can check out what would change.

This has already uncovered some potential bugs, and I've tried to group the "linting fixes" and "actual bugfixes" in separate commits to make it easier to see.

**Comment by mbollmann** [comment]
In contrast to black, ruff's autofixer can clearly be destructive, so we should maybe be more careful with that ...

**Review by mjpost — APPROVED** [review]
LGTM. I ran it locally but did not look too extensively at the changes.

**Comment by anthology-assist** [comment]
@mbollmann @mjpost 

I propose we revert the changes. A lot of the ruff changes are breaking ingestion scripts.

**Comment by mbollmann** [comment]
@anthology-assist Breaking how? 

Linting changes should never break anything, though I might have made a mistake somewhere.

**Comment by anthology-assist** [comment]
@mbollmann 

When I run the ingestion script (`bin/ingest.py`), [ this line](https://github.com/acl-org/acl-anthology/blob/0ff80bdb0a7340ca9c39a1bb0b7ff60b05ac2230/bin/latex_to_unicode.py#L170) is throwing an error "LookupError: unknown encoding: ulatex+utf8".  Then I noticed the importing update from ruff (remove of the`import latexcodec`). After I add it back a new error pops up [this line](https://github.com/acl-org/acl-anthology/blob/0ff80bdb0a7340ca9c39a1bb0b7ff60b05ac2230/bin/fixedcase/protect.py#L81) "NameError: name 'TreebankWordDetokenizer' is not defined".

I have not looked into this in details but I suspect this is due to the ruff merge, because the only code changes we have merged into master from last ingestion is the ruff merge.

**Comment by mbollmann** [comment]
Thanks, I will look into this tomorrow, sounds like some imports might have "magic" side-effects, which isn't great for code maintenance. 😕

In general, if it's possible to revert only those files that cause problems now, that would be much preferable to reverting this entire PR. Adding a `# ruff: noqa` in the file will stop Ruff from complaining about it.

**Comment by mbollmann** [comment]
@anthology-assist Can you check if you get any more errors with the fixes from the [fix-breaking-ruff-changes](https://github.com/acl-org/acl-anthology/tree/fix-breaking-ruff-changes) branch?

I don't have any example proceedings that I could use to test the ingestion script myself...

**Comment by anthology-assist** [comment]
@mbollmann the branch seems to fix the ingestion breaks (run with no error)! Thank you!

**Pull request merged**
