### PR TITLE
add PWC dataset for TempEval-3

### PR DESCRIPTION
**Pull request by leondz**
Add dataset link for TempEval-3 via PWC.

### CODE REVIEW

**Comment by mbollmann** [comment]
Thanks! I can see the dataset [is linked on PwC's paper page](https://paperswithcode.com/paper/semeval-2013-task-1-tempeval-3-evaluating). This info is synced automatically from PwC once a week, so manual PRs aren't necessary (and would be overwritten by the automatic sync anyway).

**Comment by leondz** [comment]
This paper isn't connect in the anthology, is it?

**Comment by leondz** [comment]
Is this a valid dataset link? That PwC dataset link on the PwC page for S13-2001 (a paper/ page) goes to another PwC page (the dataset/ page), not to a download. What do you think? Do the anthology PwC download links get created after transitive traversal of PwC entries, or just based on the first hop?

**Comment by mbollmann** [comment]
I'm not sure what you mean by "Anthology PwC download links". The PwC links always go to pages on the PwC website and are never direct download links AFAICT.

**Comment by leondz** [comment]
"Anthology PwC download links" refers to the links to PwC on the Anthology. Currently no dataset is defined for S13-2001 on PwC, so I am unsure if a PwC download link will appear on the Anthology.

**Comment by mbollmann** [comment]
But there is a dataset defined for S13-2001 on PwC, see: https://paperswithcode.com/paper/semeval-2013-task-1-tempeval-3-evaluating (alternatively: https://paperswithcode.com/paper/?acl=S13-2001) -- That will appear as soon as the next round of PwC updates is processed. Unless you're talking about something else?

**Comment by leondz** [comment]
Does https://paperswithcode.com/paper/semeval-2013-task-1-tempeval-3-evaluating look like a valid dataset page to you? I To me it looks like page describing use of a dataset, not a dataset. A dataset page would be something like https://paperswithcode.com/dataset/tempeval-3, the two differentiated by the URL path prefix, as mentioned above. But will the PwC import add links to the anthology to all the datasets a given paper uses (vs. presents)?

**Comment by mbollmann** [comment]
https://paperswithcode.com/paper/semeval-2013-task-1-tempeval-3-evaluating is the page associated with the ACL paper of ID S13-2001. Datasets and code linked from that page will therefore appear as links on the ACL Anthology's paper page for S13-2001 as well.

If I run the `bin/ingest_pwc.py` script on the master branch, the exact line added in this PR appears in S13.xml.

**Comment by leondz** [comment]
Woah, OK, that was super unexpected! Why does that paper/ page trigger a dataset import?

**Comment by leondz** [comment]
Woah, OK, that was super unexpected! I don't remember editing anything on that paper/ page. Well, I'm lost with why that works, but maybe it's better not to ask.

**Comment by mbollmann** [comment]
I wish I knew what the underlying confusion was. :) Papers with Code is a service that links up papers with code implementations and dataset information. We simply show that information directly on the Anthology, no more, no less. It's not related at all to _archiving_ code or datasets on the Anthology, if maybe that's where the confusion comes from?

**Comment by leondz** [comment]
Me too! Well, I'll write a vignette of my story, don't know if it helps.

I heard the dataset link in S13-2001 was broken. Thought it'd make sense to add a link to the anthology but didn't know how, so I looked in the source and saw this pwc data element hanging around. Realised this would need a dataset entry on pwc. Went to pwc, looked for the TempEval-3 data, it wasn't there, so created a new dataset there. Part of this asks for a paper link; the only one could find was to the arXiv paper. So I added that, and got sent to this nice pwc dataset page, with a url path starting dataset, and all kinds of info about papers that had used this data. Neat! Oddly I then saw the proper SemEval paper listed as a work that *uses* this dataset, where really, it's the paper that *introduces* this dataset. I didn't expect the anthology to start giving pwc links to datasets that papers *use*, only to give links to datasets that are presented by papers. This is where I perceived a problem: the correct pwc page for the paper wasn't configured as the paper that introduces the data.

**Comment by mbollmann** [comment]
Ah! I might be wrong, but I don't think PwC has the concept of papers *introducing* versus *using* datasets. I think it's a simple (bidirectional) link between a "paper" entity and a "dataset" entity. On [their API documentation,](https://paperswithcode.com/api/v1/docs/) it says "Return all datasets *mentioned* in the paper."

**Comment by leondz** [comment]
Aha. Woah, so corpus papers and application papers are represented the same way, and the relation is papers*:datasets* ? OK, that's cool, did not expect it :)

**Comment by leondz** [comment]
Oh, there *is* a distinction -- see e.g. here where Datasets are subcategorised into "Introduced in the Paper:" and "Used in the Paper:". https://paperswithcode.com/paper/offensive-language-and-hate-speech-detection

Does the anthology show links for all of both of these?

**Comment by mbollmann** [comment]
Ah, good catch! It looks like both will be shown, but there is no such distinction on our side.

For reference, I did the following to check:
```bash
$ wget -O pwc.json https://paperswithcode.com/integrations/acl/  
$ jq '.["2020.lrec-1.430"]' pwc.json
```

That shows you the exact data we get from PwC's ACL API for that paper:
```json
{
  "code": {
    "url": null,
    "additional": false,
    "name": null
  },
  "datasets": [
    {
      "url": "https://paperswithcode.com/dataset/dkhate",
      "name": "DKhate"
    },
    {
      "url": "https://paperswithcode.com/dataset/olid",
      "name": "OLID"
    }
  ]
}
```

**Comment by leondz** [comment]
Ah, that's their endpoint? 

I realise I have no power here, but it seems unintuitive for all datasets a paper uses & introduces to be listed on the anthology without distinction. Would a richer response from PwC, that distinguishes between the types, be better?

**Pull request closed without merging**
