### PR TITLE
Conditional bibtex generation

### PR DESCRIPTION
**Pull request by akoehn**
replaces #1227.

Just adds an if/else to use empty rules instead of the real ones if NOBIB=true

Also includes the checks from #1227.

### CODE REVIEW

**Review by mjpost — APPROVED** [review]
LGTMAFAIK.

Can you comment on why you moved to using a variable instead of a separate target? Typing something like `make dev` would be slightly more convenient. We might even make the development environment the default, since that's the one people building it manually are most likely to use.

**Comment by mjpost** [comment]
(Approving though, since this is a definite step forward)

**Comment by akoehn** [comment]
> Can you comment on why you moved to using a variable instead of a separate target?

General time constraints requiring an easy solution (could only work on this in a 1h window Sunday evening), the need to redefine the mods/bibtex/endnote targets.  I am unfortunately severly time-constricted due to the state of the world. 

`hugo` needs to depend on bibtex (otherwise the data is not generated *before* hugo runs) and if we want to not generate bibtex, we need to redefine the target.  I am not sure we can do that easily as part of a rule (and if we can,  without triggering redefinition warnings).  With the if/else, we either define one or the other and have no warnings.

**Comment by mjpost** [comment]
Thanks, good to have down for the record.

**Pull request merged**
