### PR TITLE
Correction to Anthology ID 2020.nuse-1.5

### PR DESCRIPTION
**Pull request by Franck-Dernoncourt**
- Fixed typo Frank -> Franck. 
- Fixed author order to match the [PDF](https://www.aclweb.org/anthology/2020.nuse-1.5.pdf).

### CODE REVIEW

**Comment by mjpost** [comment]
Hi Franck—Sorry to be a pain, but this paper, too, falls under our [author change policy](https://www.aclweb.org/anthology/info/corrections/#note-on-author-changes). So we will need some kind of authorization from the NUSE organizers.

**Comment by Franck-Dernoncourt** [comment]
@mjpost no worries, I have amended the PR so that it doesn't fix the order to match the PDF. This way we don't have to go through the ACL author change policy (since the PR now only fixes a typo in one author name). Is it ok to merge now? Thanks!

**Comment by mjpost** [comment]
Yes, I’ll process this with the next round of corrections.

**Comment by Franck-Dernoncourt** [comment]
Great, thanks!

**Comment by mjpost** [comment]
Merged.

**Pull request closed without merging**
