### PR TITLE
April 2022 Corrections

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Review by xinru1414 — APPROVED** [review]
LGTM

**Review by xinru1414 — APPROVED** [review]
LGTM

**Comment by xinru1414** [comment]
@mjpost shall i merge? i remember you have a paper retraction?

**Comment by mjpost** [comment]
Not yet will add today

**Comment by mjpost** [comment]
On second thought, I'm going to reprocess that last one as a retraction.

**Pull request merged**
