### PR TITLE
EMNLP DOIs and fixes

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by nschneid** [comment]
Any ETA on this? I'd prefer for DOIs to be in place before I start importing papers into my Zotero.

**Comment by mjpost** [comment]
I was waiting for more changes but can merge this as soon as someone approves it.

**Comment by mjpost** [comment]
I just need a review and I can merge this.

**Review by mbollmann — APPROVED** [review]
LGTM

**Pull request merged**
