### PR TITLE
Author/editor `id` attribute

### PR DESCRIPTION
**Pull request by davidweichiang**
The initial commit here converts the `complete` attribute to an `id` attribute.

- The intent is that the author of a paper is identified as proposed in #208: If the `author` tag has an `id` attribute, the `id` is looked up in `name_variants.yaml`; else, the `first` and `last` name are looked up in `name_variants.yaml`.
- So far, ids are used only if the previous version used the `complete` attribute. There's no resolving of name collisions (e.g., Yang Liu) yet.
- I went with the slug of the canonical name as the default id. There are currently no slug collisions, so no need for number suffixes (yet). The canonical name is usually the most frequently used name, but in some cases, in order to disambiguate, or sometimes for no reason, I've changed it so the canonical name is the most specific name. If another convention for choosing ids is desired, now would be a good time to decide that.

To do:
- [ ] check all these initially-generated ids to see if they are reasonable
- [x] check and enforce the constraint that if a first+last name is ever used with an id, it should always be used with an id
- [x] allow entries in `name_variants.yaml` to have colliding canonical/variant names if they both have ids
- [x] author's canonical slug (i.e., the one used in the URL for their page) should be same as id if it exists (?)
- [x] generation of author links should use ids
- [x] add ids to Yang Liu's paper as (the principal) test case

### CODE REVIEW

**Comment by davidweichiang** [comment]
Assuming this passes, I think this is ready. But it's a large change and should be reviewed carefully.

**Comment by davidweichiang** [comment]
Hm, I didn’t get those errors locally and will take a closer look. But the above build is a good example of the “always or never use id” constraint in action. It’s picky but I think it helps to catch errors.

**Comment by mjpost** [comment]
Those are some awesomely detailed error messages. I’ll take a careful look soon.

**Comment by davidweichiang** [comment]
OK, this passes and I think I'm done.

**Comment by mjpost** [comment]
Great—will review tomorrow.

**Comment by mjpost** [comment]
I looked over the code a bit and it looks fine to me, though it would benefit from a glance by someone more familiar with its intricacies.

I did pull it down and try to build it. The Python preprocessing all goes well, but I get this error when running `hugo server` (in lieu of `hugo cleanDestinationDir --minify`). Is this enough information to make sense of?

```bash
$ hugo server
Building sites … ERROR 2019/05/08 14:01:22 [en] REF_NOT_FOUND: Ref "/people/i/i-aldezabal.md" from page "/Users/post/code/acl-anthology/hugo/content/people/0/0-ansa.md": page not found
ERROR 2019/05/08 14:01:22 [en] REF_NOT_FOUND: Ref "/people/i/i-alegria.md" from page "/Users/post/code/acl-anthology/hugo/content/people/0/0-ansa.md": page not found
ERROR 2019/05/08 14:01:22 [en] REF_NOT_FOUND: Ref "/people/j/j-m-arriola.md" from page "/Users/post/code/acl-anthology/hugo/content/people/0/0-ansa.md": page not found
ERROR 2019/05/08 14:01:22 [en] REF_NOT_FOUND: Ref "/people/n/n-ezeiza.md" from page "/Users/post/code/acl-anthology/hugo/content/people/0/0-ansa.md": page not found
```

**Comment by davidweichiang** [comment]
I think this might be related to #316, but what's `0-ansa.md`?

**Comment by mjpost** [comment]
Had the same thought, am trying to clean up and rebuild...

**Comment by mjpost** [comment]
(It would be nice if all the generated files were written to a build directory so that cleanup could be done by just `rm -rf`ing a single directory.)

**Comment by mjpost** [comment]
Okay, that fixed things for me. I'm going to merge.

**Pull request merged**
