### PR TITLE
Ingested GWC 2016

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by arademaker** [comment]
Thank you @mjpost!

**Review by akoehn — APPROVED** [review]
LGTM, but should it be part of any venue or similar?

**Comment by arademaker** [comment]
The Global Wordnet Conference is a bianual conference

http://globalwordnet.org/global-wordnet-conferences-2/

It is organized by the Global Wordnet Association

http://globalwordnet.org

**Comment by arademaker** [comment]
I am preparing the data to submit all previous editions from the conference to ACL Anthology

**Comment by arademaker** [comment]
Hi @mjpost , can you merge this PR?

**Pull request merged**
