### PR TITLE
Metadata correction of papers 2021.findings-acl.280 and 2021.paclic-1.6

### PR DESCRIPTION
**Pull request by ridho-kata**
Fixed the author metadata of 2021.paclic-1.6 and the title metadata of 2021.findings-acl.280, both to reflect the PDFs.

### CODE REVIEW

**Review by xinru1414 — COMMENTED** [review]
LGTM

**Review by xinru1414 — COMMENTED** [review]
Double checked with the paper PDF. LGTM.

**Comment by mbollmann** [comment]
@ridho-kata Yes it's the missing line break at the end of the XML file. You can just push another commit here that fixes this.

**Comment by danielgildea** [comment]
Something seems to be wrong with 2021.paclic.xml.  The list of papers does not correspond to the table of contents in the volume pdf.  For example, the first paper in the pdf, "Under the Microscope: Interpreting Readability Assessment Models for Filipino" doesn't appear in the xml file.

**Comment by xinru1414** [comment]
@danielgildea thanks for putting this out! I'm in touch with the conference organizer. @ridho-kata I'm keeping this PR open till I fix the paper orders and incorporate the author names fixes.

**Comment by mjpost** [comment]
@xinru1414 can you contact the volume editors to ask about this?

[Kaibao Hu](https://aclanthology.org/people/k/kaibao-hu/), [Jong-Bok Kim](https://aclanthology.org/people/j/jong-bok-kim/), [Chengqing Zong](https://aclanthology.org/people/c/chengqing-zong/), [Emmanuele Chersoni](https://aclanthology.org/people/e/emmanuele-chersoni/) (Editors)

**Review by mjpost — APPROVED** [review]
LGTM

**Comment by xinru1414** [comment]
@mjpost In touch with the person in charge. Waiting on new proceedings to reingest.

**Comment by ridho-0** [comment]
Hi @xinru1414, I've just realized that for some reason the changes I made were reverted back (see the current [2021.public.xml](https://github.com/acl-org/acl-anthology/blob/master/data/xml/2021.paclic.xml)). Do you know what happened?

Should I just make another pull request?

**Pull request merged**
