### PR TITLE
Auto accents for 2015-2019

### PR DESCRIPTION
**Pull request by davidweichiang**
This is the run of auto_authors.py on conferences 2015-2019 but excluding NAACL 2019. Most of the changes involve restoration of accents that appear in the PDF but not the metadata, but there are also capitalization, hyphenation, and spacing changes.

There are no actual spelling changes; for example, if the PDF says Kathleen but the metadata says Kathy, the script prints a warning but does not change anything.

### CODE REVIEW

**Comment by davidweichiang** [comment]
#333

**Comment by davidweichiang** [comment]
NAACL 2019 will be done shortly, so please don't approve just yet.

**Comment by mjpost** [comment]
Do you want to update the MOTD with this PR? It’d be nice to have some mention of this in the landing page banner.

**Comment by davidweichiang** [comment]
I don’t think it merits an announcement, especially since not all years are done yet and I am still figuring out how to do spelling changes.

**Pull request merged**
