### PR TITLE
Corrections for July 2021

### PR DESCRIPTION
**Pull request by mjpost**
Marking as draft until the end of the month.

### CODE REVIEW

**Review by xinru1414 — APPROVED** [review]
LGTM

**Comment by mjpost** [comment]
Let's wait a day or two to merge, in case anything comes in for ACL (which is starting today).

**Comment by xinru1414** [comment]
> Let's wait a day or two to merge, in case anything comes in for ACL (which is starting today).

SG

**Comment by xinru1414** [comment]
@mjpost time to merge?

**Comment by mjpost** [comment]
I think so, unless there are any other stray ones you want to pull in. Let's merge tonight though!

**Pull request merged**
