### PR TITLE
Ingest amta 1996

### PR DESCRIPTION
**Pull request by mardub1635**

### CODE REVIEW

**Comment by danielgildea** [comment]
I think ingest_tsv.py needs to be re-run to generate the checksums for the pdfs.
Where is the tsv file?

**Comment by davidweichiang** [comment]
Why is the check failing on the URLs?

**Comment by mbollmann** [comment]
Missing checksums.

**Comment by mjpost** [comment]
Hi folks—this is backlogged a bit while I deal with ACL (and other venues that are pushing for ingestion). The good part here is that the updated `ingest_tsv.py` script is now on the main branch. The task for each of these old imports (under `data/` here: https://github.com/mardub1635/mt-archive/) is to:

1. Verify the file list in the TSV against the MT Archive page
2. Make any necessary corrections
3. Run `ingest_tsv.py`
4. Create a PR

There are something like 200 individual conferences to import from MT archive. We are using [this spreadsheet](https://docs.google.com/spreadsheets/d/1fpxmdV_BPwR6BQHyU9VJQxXeSOmy4__5nQCHBEviyAw/edit#gid=0) to track progress. These involve many complicated editorial decisions.

I'd love for help here for people who are interested. I'll post a set of instructions soon so that anyone wanting to can do so. I'll set a target date of Sunday for doing that.

**Comment by mjpost** [comment]
Okay. If anyone wishes to help, I'd like to ingest these one by one. I wrote up [some instructions here](https://github.com/acl-org/acl-anthology/wiki/MT-Archive-Ingestion-Checklist).

**Pull request merged**
