### PR TITLE
eamt 2023 ingestion

### PR DESCRIPTION
**Pull request by anthology-assist**

### CODE REVIEW

**Comment by kjp-souza** [comment]
I just have one doubt, @anthology-assist and @mjpost: these LaTex escape characters were automatically generated within the BibTex files when running the script.
Is it just appearing on the preview or is it an issue that should be corrected before publishing? I've highlighted them below:
image

**Comment by kjp-souza** [comment]
> Build successful. Some useful links:
> 
> * Complete site preview: https://preview.aclanthology.org/eamt-23-ingestion
> * Potential volumes of interest: [2022.emnlp-main](https://preview.aclanthology.org/eamt-23-ingestion/volumes/2022.emnlp-main), [2022.emnlp-tutorials](https://preview.aclanthology.org/eamt-23-ingestion/volumes/2022.emnlp-tutorials), [2022.emnlp-demos](https://preview.aclanthology.org/eamt-23-ingestion/volumes/2022.emnlp-demos), [2022.emnlp-industry](https://preview.aclanthology.org/eamt-23-ingestion/volumes/2022.emnlp-industry), [2022.tsar-1](https://preview.aclanthology.org/eamt-23-ingestion/volumes/2022.tsar-1), [2023.at4ssl-1](https://preview.aclanthology.org/eamt-23-ingestion/volumes/2023.at4ssl-1), [2023.crowdmt-1](https://preview.aclanthology.org/eamt-23-ingestion/volumes/2023.crowdmt-1), [2023.eamt-1](https://preview.aclanthology.org/eamt-23-ingestion/volumes/2023.eamt-1), [2023.gitt-1](https://preview.aclanthology.org/eamt-23-ingestion/volumes/2023.gitt-1)
> 
> This preview will be removed when the branch is merged.

Some of these volumes you mentioned are not part of EAMT and belong to another conference - could you clarify why they should be considered, please? Thank you!
image

**Comment by mbollmann** [comment]
> Is it just appearing on the preview or is it an issue that should be corrected before publishing? 

That should be corrected. Names should appear as Unicode strings in the XML.

> Some of these volumes you mentioned are not part of EAMT and belong to another conference - could you clarify why they should be considered, please?

They shouldn't. It's just an automatically-generated aid, and I suspect it has included EMNLP because we merged in the recent changes from the master branch here, which included changes to EMNLP.

**Comment by kjp-souza** [comment]
> > Is it just appearing on the preview or is it an issue that should be corrected before publishing?
> 
> That should be corrected. Names should appear as Unicode strings in the XML.
> 
> > Some of these volumes you mentioned are not part of EAMT and belong to another conference - could you clarify why they should be considered, please?
> 
> They shouldn't. It's just an automatically-generated aid, and I suspect it has included EMNLP because we merged in the recent changes from the master branch here, which included changes to EMNLP.

So, if it's not a problem, I've pulled this eamt-23-ingestion branch and will try and update the XML strings and will push the changes. Is that ok?

**Comment by kjp-souza** [comment]
> > Is it just appearing on the preview or is it an issue that should be corrected before publishing?
> 
> That should be corrected. Names should appear as Unicode strings in the XML.
> 
> > Some of these volumes you mentioned are not part of EAMT and belong to another conference - could you clarify why they should be considered, please?
> 
> They shouldn't. It's just an automatically-generated aid, and I suspect it has included EMNLP because we merged in the recent changes from the master branch here, which included changes to EMNLP.

@mbollmann - tried correcting and pushing the commits, but I have no permission it seems.

**Comment by kjp-souza** [comment]
@mbollmann, @mjpost, @anthology-assist, here are my last commits on forked repo tracking `eamt-23-ingestion` branch. After these corrections, this should be ok to merge! Let me know if I should change the .tgz file or anything else instead, please.

**Review by mjpost — APPROVED** [review]

**Pull request merged**
