### PR TITLE
Ingest TALN 2015

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by mjpost** [comment]
The ACL 2020 ingest will be coming soon and I'd like to clear the queue ahead of time. Does someone have time to review this? @acl-org/anthology

**Comment by ozancaglayan** [comment]
Just noticed these things when trying to learn about ingestion pipeline:

image
image

**Comment by ozancaglayan** [comment]
are we allowed to send PR's directly on top of the `xml`s to fix these?

**Comment by davidweichiang** [comment]
Yes please, that's the best! Thanks for catching this.

Do we know how this happened? Are fixes needed in the ingestion scripts?

**Comment by mjpost** [comment]
I am working with someone to ingest old TALN conferences. This slipped through but he's corrected it for future ones (e.g., #906).

**Comment by mjpost** [comment]
But come to think of it, the ingestion scripts could check for `\'` and `texttildeascii`. If the latter ever shows up legitimately, I'm quitting.

**Pull request merged**
