### PR TITLE
Added NAACL 2021 best paper awards

### PR DESCRIPTION
**Pull request by mjpost**
We will wait till June 10 to merge.

### CODE REVIEW

**Comment by mjpost** [comment]
@mbollmann do you know how to fix this?

image

Excerpt:

```html
                <p class="d-sm-flex align-items-stretch">
                    <span class="d-block mr-2 text-nowrap list-button-row">
                        <a class="badge badge-primary align-middle mr-1" href=https://preview.aclanthology.org/naacl-best-papers/2021.naacl-main.119.pdf data-toggle=tooltip data-placement=top title="Open PDF">pdf
                        </a>
                        <a class="badge badge-info align-middle mr-1" href=#abstract-2021--naacl-main--119 data-toggle=collapse aria-expanded=false aria-controls=abstract-2021.naacl-main.119 title="Show Abstract">abs</a>
                        <br class="d-none d-sm-inline-block">
                        <span data-toggle=tooltip data-placement=bottom title="Best Long Paper">
                            <i class="fas fa-award"></i>
                        </span>
                        <a class="badge badge-attachment align-middle mr-1" href=https://preview.aclanthology.org/naacl-best-papers/attachments/2021.naacl-main.119.OptionalSupplementaryCode.zip data-toggle=tooltip data-placement=top title="Optional supplementary code">
                            <i class="fas fa-file"></i>
                        </a>
                    </span>
```

**Comment by mbollmann** [comment]
Probably needs at least `class="align-middle mr-1"` on the `<span>` element. Can test tomorrow if that's not enough.

**Comment by mjpost** [comment]
That did it, thank you!

**Review by mbollmann — APPROVED** [review]
LGTM (though I trust that you tagged the correct papers ;))

**Pull request merged**
