### PR TITLE
[May 22] Ingestion: nlp4call & resourceful

### PR DESCRIPTION
**Pull request by anthology-assist**

### CODE REVIEW

**Comment by mjpost** [comment]
Please add to `2023.ws.xml`

**Comment by mjpost** [comment]
What conference was this associated with?

Note also this is the first time they have expanded "NLP" in their booktitle, was this intentional?
image

**Comment by mbollmann** [comment]
Conference is [NoDaLiDa](https://www.nodalida2023.fo/workshops).

**Comment by mjpost** [comment]
Please cross-list from nodalida, and possibly merge these PRs.

**Comment by mjpost** [comment]
Hi, there are many missing PDFs, can you upload them?

**Comment by nilinykh** [comment]
Hello,

the missing PDFs had a minor problem described here: https://github.com/acl-org/acl-anthology/issues/2516#issuecomment-1559156012.

Could you please re-upload and update the PDFs? The correct ones are available on the link above.

**Comment by nilinykh** [comment]
A different detail that we have noticed is that the current ACL preview link places our proceedings under the ACL keyword NLP4call which is another workshop.

https://preview.aclanthology.org/nlp4call-ingestion/2023.resourceful-1.pdf

(nlp4call in the link above)

I have been told there is an existing independent handle for our workshop, e.g. RESOURCEFUL. Could you tell us if this will be used for our proceedings?

**Comment by mjpost** [comment]
That is just a preview. You can see your preview here: https://preview.aclanthology.org/nlp4call-ingestion/volumes/2023.resourceful-1/. Is it correct (Including the PDFs)?

**Comment by nilinykh** [comment]
@xinru1414 , the PDFs are correct now, but my pull request which fixed the list of editors (https://github.com/acl-org/acl-anthology/pull/2540/commits/4022a0a6a881552f64649ad8bc18db846a822059) is not included. It disappeared with the merge, but it should be included.

**Comment by nilinykh** [comment]
I have added the pull request for correcting the list of editors, https://github.com/acl-org/acl-anthology/pull/2562

**Comment by mjpost** [comment]
@anthology-assist can you please add 2023.nlp4call-1 and 2023.resourceful-1 to 2023.ws.xml? This should done as part of [the ingestion checklist](https://github.com/acl-org/acl-anthology/wiki/Ingestion-Checklist).

**Comment by mjpost** [comment]
@nilinykh changing the PDFs after the original ingestion request adds some complication to the ingestion. Can you please visit [this preview link](https://preview.aclanthology.org/nlp4call-ingestion/events/nodalida-2023/#2023nlp4call-1), sample 10–15 PDFs papers across the main volume and the workshops, and ensure they are correct?

**Review by mjpost — APPROVED** [review]

**Pull request merged**
