### PR TITLE
Ingested WMT 2021

### PR DESCRIPTION
**Pull request by mjpost**
At long last.

### CODE REVIEW

**Review by xinru1414 — COMMENTED** [review]
The ingested xml file LGTM

**Comment by mjpost** [comment]
Lots of churn here, but:

* I added a nice new feature: the preview link that gets posted here now provides a direct link to all changed volumes, making it easier to check them
* I fixed a bug in `ingest.py` that caused it not to find the book in certain cases (I worry we've missed a number of them)

**Comment by arturnn** [comment]
Hello Matt,

Could all of the WMT21 papers have venues specified as EMNLP | WMT (as it is specified in the WMT20 papers)? Also, will Proceedings of the Sixth Conference on Machine Translation be added to the list of contents of EMNLP2021?

**Comment by mjpost** [comment]
Oh yes, thanks for noticing this. I forgot to add that link. 

Want to become a contributor by adding to the PR yourself? You just have to add entries in data/yaml/joint.yaml.

**Comment by mjpost** [comment]
2021.wmt-1 also has to be added to sigs/sigmt.yaml

**Comment by mjpost** [comment]
While it's on my mind:
- [ ] Add to EMNLP in `data/yaml/joint.yaml`
- [ ] Add to SIGMT
- [ ] Generate DOIs (@xinru1414: will have to be a second PR)

**Comment by arturnn** [comment]
> Oh yes, thanks for noticing this. I forgot to add that link.
> 
> Want to become a contributor by adding to the PR yourself? You just have to add entries in data/yaml/joint.yaml.

Sure thing, created PR: https://github.com/acl-org/acl-anthology/pull/1772

**Review by xinru1414 — COMMENTED** [review]
LGTM

**Review by xinru1414 — COMMENTED** [review]
LGTM

**Review by xinru1414 — COMMENTED** [review]
LGTM

**Comment by mjpost** [comment]
@xinru1414 you left a comment but didn’t actually approve? Once you do that, I’ll merge.

**Comment by xinru1414** [comment]
> @xinru1414 you left a comment but didn’t actually approve? Once you do that, I’ll merge.

yes i was going through the files you changed one by one. i will approve once i go through them all

**Comment by xinru1414** [comment]
> Lots of churn here, but:
> 
> * I added a nice new feature: the preview link that gets posted here now provides a direct link to all changed volumes, making it easier to check them
> * I fixed a bug in `ingest.py` that caused it not to find the book in certain cases (I worry we've missed a number of them)

@mjpost the new feature is really nice thanks for adding that!

regarding the bug in `ingest.py`, i just noticed it while doing paclic35 ingestion and manually fixed it. We probably missed some. I could check on all 2021 ingestions. thanks for the bug fixing!

**Review by xinru1414 — COMMENTED** [review]
LGTM

**Comment by xinru1414** [comment]
> While it's on my mind:
> 
> * [x]  Add to EMNLP in `data/yaml/joint.yaml`
> * [x]  Add to SIGMT
> * [ ]  Generate DOIs (@xinru1414: will have to be a second PR)

@mjpost got it, this is just for `2021.wmt-1` right? (there are other potential volumes listed under preview)

**Review by xinru1414 — APPROVED** [review]

**Comment by mjpost** [comment]
> > @xinru1414 you left a comment but didn’t actually approve? Once you do that, I’ll merge.
> 
> yes i was going through the files you changed one by one. i will approve once i go through them all

Oh, they just appear in sequence, it’s hard to tell what they’re attached to. I thought it was a mistake. Thanks!

**Pull request merged**
