### PR TITLE
Move links from footer to header

### PR DESCRIPTION
**Pull request by mjpost**
This moves the links from the footer to the header. Discussion continued from #539 and #538 .

### CODE REVIEW

**Comment by mbollmann** [comment]
I'd like to build this locally to play around with it a bit, but it could take me a couple of days to find the time.

**Comment by mjpost** [comment]
Sounds great, thanks, Marcel.

**Comment by mjpost** [comment]
@mbollmann, do you think we could merge this and improve it later when you have time? I think having the information in the header would help advertise key information that I currently have to email people links to and would like to merge this before too much longer.

**Comment by mjpost** [comment]
Another thing we could do here is to move the Search Bar to the middle permanently, and put the links on the right. Then everything would collapse correctly without needing an inversion at collapse time. A centralized search bar is fairly common (e.g., amazon.com).

**Comment by akoehn** [comment]
Sounds reasonable, but I would merge this PR first before it gets endlessly delayed.

**Comment by mjpost** [comment]
Will do.

**Pull request merged**
