### PR TITLE
Added EACL 2024 videos

### PR DESCRIPTION
**Pull request by davidstap**
This PR adds Underline presentation videos presented during EACL 2024.

### CODE REVIEW

**Comment by mjpost** [comment]
Hi @davidstap, we've been getting a number of requests from people who had allowed recording of their videos but asked for them not to be released. Can you verify with our Underline contact that this designation is being passed to us, and is reflected in this latest import?

**Comment by davidstap** [comment]
Good point @mjpost - my guess is that this import is based on all available videos without taking into account author designations. I'll reach out to Underline.

**Comment by mjpost** [comment]
Any response?

**Comment by davidstap** [comment]
Still waiting, I’ll send a reminder.

**Comment by davidstap** [comment]
Got a response now. It turns out that indeed, this PR includes *all* videos, not just videos with consent. Same issue for earlier conferences.

Underline will share the consent data. I will then sort out how to fix this, also retroactively for earlier venues.

**Comment by mjpost** [comment]
Awesome, that sounds great—thanks, David.

**Review by mjpost — APPROVED** [review]
I spot-checked a few of these.

**Pull request merged**
