### PR TITLE
Update to 2023.eacl-main.57

### PR DESCRIPTION
**Pull request by ridho-0**
Add the missing authors to correctly reflect the [paper pdf](https://aclanthology.org/2023.eacl-main.57.pdf):
- Timothy Baldwin
- Jey Han Lau
- Rico Sennrich
- Sebastian Ruder

### CODE REVIEW

**Comment by mjpost** [comment]
Many errors have been discovered in the EACL submissions. The EACL team is working on resubmitting so we can re-ingest. I hope this will fix your issue.

**Comment by gentaiscool** [comment]
thanks @mjpost for helping.

**Comment by mjpost** [comment]
I think this is fixed now that we re-ingested; can you pull in `master` and confirm?

**Comment by mjpost** [comment]
I think the diff is minimal, only two affiliations, and I might have merged the wrong way. Closing, but feel free to reopen if you want these affiliations updated.

**Pull request closed without merging**
