### PR TITLE
Update 2020.vlsp.xml

### PR DESCRIPTION
**Pull request by sonvx**
- PR to update the meta file of VLSP proceedings. See the original issue here: https://github.com/acl-org/acl-anthology/issues/1249

### CODE REVIEW

**Comment by mjpost** [comment]
Can you do two more things?

(a) Attach a new front matter PDF, e.g., https://www.aclweb.org/anthology/2020.vlsp-1.0.pdf
(b) Update the crc32 checksum for that file (the `<url>` tag in the `<frontmatter>` block)
(c) Also update the crc32 checksum for the new complete PDF you attached to #1249 (the `<url>` tag in the `<meta>` block)

**Comment by sonvx** [comment]
@mjpost : Could you please check the PR again? I added the checksums and attached here the PDF of both *frontmatter* and the complete proceedings:

[VLSP_2020_frontmatter.pdf](https://github.com/acl-org/acl-anthology/files/6292925/VLSP_2020_frontmatter.pdf)
[2020.vlsp-1.pdf](https://github.com/acl-org/acl-anthology/files/6292934/2020.vlsp-1.pdf)

**Comment by mjpost** [comment]
Usually the front matter includes everything before the first paper, can you update again (PDF and checksum). I'll merge and make it live tonight.

**Comment by sonvx** [comment]
@mjpost I see, I just updated the checksum and attached the PDF here again:

[VLSP_2020_frontmatter.pdf](https://github.com/acl-org/acl-anthology/files/6292987/VLSP_2020_frontmatter.pdf)

**Review by xinru1414 — APPROVED** [review]
checksum for 2020.vlsp-1.pdf LGTM

**Pull request merged**
