### PR TITLE
added video link

### PR DESCRIPTION
**Pull request by TalSchuster**
video link to N19-1162

### CODE REVIEW

**Comment by akoehn** [comment]
Thanks for the PR!  It is really unfortunate that we don't get an official list of correspondences to videos.

@mjpost do you know why the N19 videos are not on the acl account in vimeo and whether we will finally get a list of videos at some point in time?

**Comment by mjpost** [comment]
I cannot get our video provider to supply the links, nor have I been able to view the contract. I have written [this document](https://github.com/acl-org/acl-anthology/wiki/Contract-Guidelines-for-Recording-Talks) and have been proactively emailing PCs to make sure they attach it to the contract. 

I was going to ask if you could run your matching code for NAACL 2019?

**Comment by akoehn** [comment]
I can try but the problem is that the new videos are on a different account and I have to see how I need to change the code to make the account configurable.

**Comment by mjpost** [comment]
You mean a different Vimeo account? Maybe I can transfer them over. They should all be in one place. Argh.

**Comment by akoehn** [comment]
Matt Post writes:

> You mean a different Vimeo account? Maybe I can transfer them over. They should all be in one place. Argh.

Yes, they are on a different vimeo account: the old ones were all on the
ACL account, the ones for naacl are on a “techtalkstv” account.

It is really a bit of a mess :-(

**Comment by mjpost** [comment]
NAACL 2019 is under ACL. The older ones are techtalks.tv which is defunct as you know. Status is [here](https://docs.google.com/document/d/1Ys8ULnFyaeSh-UZ_uh9BKp4aOfXrwxe2f5PXPDzG6UY/edit?usp=sharing).

**Comment by akoehn** [comment]
I only see those videos on the techtalks tv account on vimeo.  See the one we linked in this PR:
https://vimeo.com/search?q=Cross-Lingual+Alignment+of+Contextual+Word+Embeddings%2C+with+Applications+to+Zero-shot+Dependency+Parsing

these are uploaded on this user: https://vimeo.com/user72337760  but ACL is this one: https://vimeo.com/aclweb

**Comment by akoehn** [comment]
With 
> a “techtalkstv” account.

I meant that account on vimeo, not the old techtalks.tv website.

**Comment by mjpost** [comment]
Here they are: https://vimeo.com/channels/1503729

**Comment by akoehn** [comment]
There are some, but some are on the techtalks channel and not in the naacl channel, including the one linked in this PR.  I just went through the list to check.

**Pull request merged**
