### PR TITLE
lucyw/merge names

### PR DESCRIPTION
**Pull request by lucylw**
Merging my author profile pages: 

https://aclanthology.org/people/l/lucy-lu-wang/
https://aclanthology.org/people/l/lucy-wang/

And correcting anthology entries with the wrong canonical name: Lucy Wang -> Lucy Lu Wang

### CODE REVIEW

**Review by xinru1414 — APPROVED** [review]
LGTM

**Comment by xinru1414** [comment]
@mjpost does the [name_variants.yaml](https://github.com/acl-org/acl-anthology/pull/2215/commits/d03716e34b46cebe1762714a4189f3271643b4a5#diff-73a252beacc4895aaa0d57180f1e406fcc8408db735f98ce6662d1b5b20495b2) need to include `{first: Lucy L., last: Wang}` ?

**Comment by xinru1414** [comment]
@lucylw thanks for the PR!

**Comment by mjpost** [comment]
Only if that variant exists somewhere, and needs to be grouped here. 

The file doesn't need to contain the canonical name as a variant, though, so the third entry can be removed.

**Comment by lucylw** [comment]
Thanks!

**Pull request merged**
