### PR TITLE
NEJLT ingestion

### PR DESCRIPTION
**Pull request by mjpost**
Created NEJLT stub. I've copied the code and updated the tools to handle it. We just need the data now.

### CODE REVIEW

**Comment by mjpost** [comment]
Missing PDFs.

**Comment by mjpost** [comment]
@leondz can you look over the preview linked above? Does all look okay? Should we merge this now or wait for volume 8? https://preview.aclanthology.org/nejlt/volumes/2021.nejlt-1/

**Comment by leondz** [comment]
> @leondz can you look over the preview linked above? Does all look okay? Should we merge this now or wait for volume 8? https://preview.aclanthology.org/nejlt/volumes/2021.nejlt-1/

Vol 8 now also in #2336

**Comment by leondz** [comment]
Everything looks good from my side. Thanks!

**Review by xinru1414 — APPROVED** [review]

**Pull request merged**
