### PR TITLE
Added MT Summit tutorials

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by akoehn** [comment]
Build on travis and on my machine fails with
`REF_NOT_FOUND: Ref "/people/l/laura-rossi.md" from page "/home/travis/build/acl-org/acl-anthology/build/content/volumes/W19-76.md": page not found`

I unfortunately don't have time to think about why this happens @mbollmann ?

**Comment by mjpost** [comment]
It may be because she appears only once and as an editor?

**Comment by mbollmann** [comment]
Hmm, I *thought* the relevant parts of the script treat authors and editors the same, but maybe not. It will take me a couple of days before I can look at this, though.

**Comment by mjpost** [comment]
Figured it out. The person causing the error is an editor on a volume, and appears nowhere else. However, I added this volume manually, and there is no frontmatter PDF, so there was no `<frontmatter>` tag, so she was invisible to the system. I just added an empty `<frontmatter>` block and that solved the problem. Note: this means that *any* volume without `<frontmatter>` will not generate a bib entry for the volume itself.

**Comment by mjpost** [comment]
This should just be a quick review @acl-org/anthology

**Comment by aryamccarthy** [comment]
ltgm

**Pull request merged**
