### PR TITLE
Fix author name and metadata

### PR DESCRIPTION
**Pull request by mathewhuen**
Fix author metadata for 2024.lrec paper (paper ID: 1289) to match the pdf (and existing author ID) and add author name variant to name_variants.yaml (author ID: mathew-huerta-enochian) to catch future cases.

### CODE REVIEW

**Comment by mathewhuen** [comment]
The check-build job failed with the following error:
```
2024-06-12T18:20:37.5050745Z [INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
2024-06-12T18:20:37.5051528Z [INFO] Once installed this environment will be reused.
2024-06-12T18:20:37.5052060Z [INFO] This may take a few minutes...
2024-06-12T18:20:37.6127692Z An unexpected error has occurred: CalledProcessError: command: ('/home/runner/work/acl-anthology/acl-anthology/venv/bin/python3', '-mvirtualenv', '/home/runner/.cache/pre-commit/repobjas32pi/py_env-python3')
2024-06-12T18:20:37.6129828Z return code: 1
2024-06-12T18:20:37.6130314Z stdout:
2024-06-12T18:20:37.6131286Z     TypeError: object.__init__() takes exactly one argument (the instance to initialize)
2024-06-12T18:20:37.6132292Z stderr:
2024-06-12T18:20:37.6133029Z     Exception ignored in: <function BaseFileLock.__del__ at 0x7f477f38fbe0>
2024-06-12T18:20:37.6134181Z     Traceback (most recent call last):
2024-06-12T18:20:37.6135484Z       File "/home/runner/work/acl-anthology/acl-anthology/venv/lib/python3.10/site-packages/filelock/_api.py", line 365, in __del__
2024-06-12T18:20:37.6136596Z         self.release(force=True)
2024-06-12T18:20:37.6137904Z       File "/home/runner/work/acl-anthology/acl-anthology/venv/lib/python3.10/site-packages/virtualenv/util/lock.py", line 34, in release
2024-06-12T18:20:37.6138936Z         with self.thread_safe:
2024-06-12T18:20:37.6140124Z     AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'
```

Is this a problem with the virtual environment? It looks like the [latest commit on master](https://github.com/acl-org/acl-anthology/commit/179e7560214995e0851af588ef4f57c189bf70ef) also failed a [job](https://github.com/acl-org/acl-anthology/actions/runs/9487683508/job/26144866557) with the same error.

**Comment by mjpost** [comment]
Looks like [a bad filelock](https://github.com/CDCgov/multisignal-epi-inference/issues/181). We should be pegging the version numbers, anyway.

**Comment by mjpost** [comment]
It seems filelock is not an explicit dependency of ours. I'm testing a fix on #3357. You could merge in master or push some dummy change which might also work, since they yanked 3.15.0 and pushed up a fix.

**Comment by mathewhuen** [comment]
Thank you for checking on this. As you suggested, I merged master into my branch and pushed the changes.

**Review by mjpost — APPROVED** [review]

**Pull request merged**
