### PR TITLE
Ingested IWSLT 2006.

### PR DESCRIPTION
**Pull request by davidstap**
See https://aclanthology.org/www.mt-archive.info/05/IWSLT-2006-TOC.htm for original.

### CODE REVIEW

**Comment by xinru1414** [comment]
- https://preview.aclanthology.org/ingest-iwslt-2006/volumes/2006.iwslt-papers/
- https://preview.aclanthology.org/ingest-iwslt-2006/volumes/2006.iwslt-evaluation/
- https://preview.aclanthology.org/ingest-iwslt-2006/volumes/2006.iwslt-plenaries/

Should be on one page?

Also, `plenaries` is inconsistent with the other years' naming convention

**Comment by davidstap** [comment]
@xinru1414 

Again, I think the OG site is wrong, see https://www2.nict.go.jp/astrec-att/workshop/IWSLT2006/archives/2005/11/proceedings.html for the official proceedings. Here, Evaluation Campaign and Papers are split up. Do you agree it is best to do the same here?

Also, do you agree it makes sense to follow this convention for *all* other IWSLT editions as well?

**Comment by mjpost** [comment]
I think splitting into plenaries, research papers, and system papers makes sense everywhere, for historical imports, especially if the distinction on the import site makes it easy to do so.

It seems they did *not* do this [recently in 2021](https://aclanthology.org/venues/iwslt/), but that’s partly because of the system they used to manage them, which makes it difficult to create separate volumes.

**Review by xinru1414 — APPROVED** [review]
LGTM

**Pull request merged**
