### PR TITLE
reimported CoNLL (addresses #612)

### PR DESCRIPTION
**Pull request by mjpost**
I reimported this. The fixed-case handling is much easier to read, but I'm actually not sure which is correct. There is also still something of a mess with attachments; they're not labeled, and are sometimes double-imported.

### CODE REVIEW

**Comment by davidweichiang** [comment]
Generally we are supposed to only protect the initial, in case a bst prints titles in all caps. So `{E}nglish` becomes `ENGLISH`.

 But in some cases you would indeed want to protect lowercase, like maybe `McKINLEY`. So it can be a tough call.

What happened with the attachments? That seems more worrisome.

**Comment by mjpost** [comment]
It looks like our fixed-case code respects supplied BibTeX protection braces, so it took those ones. I am not inclined to fix them.

Attachments are all there, but in many cases, there are two of them. Poking around (sigh), it seems that it may have been that one was uploaded at submission time, and the other at camera-ready.

```bash
$ tar tzvf proceedings.tgz | grep additional | awk '{print $NF}' | sort
proceedings/cdrom/additional/K19-1001_OptionalSupplementaryMaterial.pdf
proceedings/cdrom/additional/K19-1008_Supplementary_Material.zip
proceedings/cdrom/additional/K19-1009_Supplementary_Material.pdf
proceedings/cdrom/additional/K19-1011_OptionalSupplementaryMaterial.zip
proceedings/cdrom/additional/K19-1017_OptionalSupplementaryMaterial.pdf
proceedings/cdrom/additional/K19-1017_Supplementary_Material.pdf
proceedings/cdrom/additional/K19-1018_Supplementary_Material.zip
proceedings/cdrom/additional/K19-1026_Supplementary_Material.pdf
proceedings/cdrom/additional/K19-1028_Supplementary_Material.pdf
proceedings/cdrom/additional/K19-1029_OptionalSupplementaryMaterial.zip
proceedings/cdrom/additional/K19-1032_Supplementary_Material.pdf
proceedings/cdrom/additional/K19-1037_OptionalSupplementaryMaterial.zip
proceedings/cdrom/additional/K19-1040_OptionalSupplementaryMaterial.pdf
proceedings/cdrom/additional/K19-1043_OptionalSupplementaryMaterial.pdf
proceedings/cdrom/additional/K19-1045_Supplementary_Material.zip
proceedings/cdrom/additional/K19-1046_OptionalSupplementaryMaterial.pdf
proceedings/cdrom/additional/K19-1046_Supplementary_Material.pdf
proceedings/cdrom/additional/K19-1048_OptionalSupplementaryMaterial.pdf
proceedings/cdrom/additional/K19-1048_Supplementary_Material.pdf
proceedings/cdrom/additional/K19-1050_OptionalSupplementaryMaterial.zip
proceedings/cdrom/additional/K19-1050_Supplementary_Material.zip
proceedings/cdrom/additional/K19-1058_OptionalSupplementaryMaterial.pdf
proceedings/cdrom/additional/K19-1058_Supplementary_Material.pdf
proceedings/cdrom/additional/K19-1061_OptionalSupplementaryMaterial.pdf
proceedings/cdrom/additional/K19-1061_Supplementary_Material.pdf
proceedings/cdrom/additional/K19-1065_OptionalSupplementaryMaterial.pdf
proceedings/cdrom/additional/K19-1065_Supplementary_Material.pdf
proceedings/cdrom/additional/K19-1073_OptionalSupplementaryMaterial.zip
proceedings/cdrom/additional/K19-1075_OptionalSupplementaryMaterial.zip
proceedings/cdrom/additional/K19-1077_Supplementary_Material.zip
proceedings/cdrom/additional/K19-1078_Supplementary_Material.zip
proceedings/cdrom/additional/K19-1081_Supplementary_Material.zip
proceedings/cdrom/additional/K19-1084_OptionalSupplementaryMaterial.pdf
proceedings/cdrom/additional/K19-1084_Supplementary_Material.pdf
proceedings/cdrom/additional/K19-1087_OptionalSupplementaryMaterial.zip
proceedings/cdrom/additional/K19-1087_Supplementary_Material.zip
proceedings/cdrom/additional/K19-1092_OptionalSupplementaryMaterial.zip
proceedings/cdrom/additional/K19-1093_OptionalSupplementaryMaterial.zip
proceedings/cdrom/additional/K19-1093_Supplementary_Material.zip
proceedings/cdrom/additional/K19-1096_OptionalSupplementaryMaterial.txt
```

**Comment by mjpost** [comment]
See for example 1046, 1048, 1087, etc.

**Comment by davidweichiang** [comment]
Why would attachments appear only when reimporting with -t?

**Comment by mjpost** [comment]
I just reimported the whole file and these are the changes after some manual deleting. So this is incidental. I had to do some other renaming earlier (they were all named OptionalSupplementaryAttachment). There have been too many manual fixes here for me to remember exactly.

**Pull request closed without merging**
