### PR TITLE
iwcs 2021 ingestion

### PR DESCRIPTION
**Pull request by xinru1414**

### CODE REVIEW

**Comment by xinru1414** [comment]
@kovvalsky For marking awards, can you provide a .tsv file that contains two columnes `paper_anthology_id` (e.g. `2021.iwcs-1.1` )and `award_name` (e.g. `outstanding paper award`)?

**Comment by mjpost** [comment]
Please be sure to use proper capitalization for the award title, since we will use it directly. For example "Best Paper", "Outstanding Demo", or "Test of Time (25 Years)".

**Comment by kovvalsky** [comment]
@xinru1414, I am attaching the file here (fyi, it starts with `2021.iwcs-1.0`)
[outstanding_papers.zip.zip](https://github.com/acl-org/acl-anthology/files/7454789/outstanding_papers.zip.zip)

**Comment by mjpost** [comment]
I added the awards. @kovvalsky or @nschneid, were these workshops colocated with IWCS? If so, @xinru1414, can you list them in `joint.yaml` so they appear on the event page?

**Comment by nschneid** [comment]
Yes—ISA, MMSR, NALOMA, SemSpace were colocated: https://iwcs2021.github.io/workshops.html

**Review by mjpost — APPROVED** [review]

**Pull request merged**
