### PR TITLE
Ingest tmi 2004

### PR DESCRIPTION
**Pull request by davidstap**
See https://aclanthology.org/www.mt-archive.info/00/TMI-2004-TOC.htm for original.

### CODE REVIEW

**Comment by xinru1414** [comment]
`Latest challenges to MT R&D` on the OG site doesn't contain a pdf/presentation link, so there's no link on the preview site either. In this case maybe it can be omitted? Otherwise it looks good!

**Comment by davidstap** [comment]
I think @mjpost would like to include it for historical reasons and/or to record it happened, so let's merge? :-)

**Comment by mjpost** [comment]
Yes, better to have it be a known unknown than an unknown unknown. The PDF may turn up some day. Thanks!

**Review by xinru1414 — APPROVED** [review]
LGTM

**Pull request merged**
