### PR TITLE
Update 2023.starsem.xml

### PR DESCRIPTION
**Pull request by Dodo-s95**
Fixed:
- Title of paper 25
- Surname (Calò) and bibkey of paper 17

### CODE REVIEW

**Comment by Dodo-s95** [comment]
Could @anthology-assist or @mjpost review this? Thanks a lot! :)

**Review by mjpost — APPROVED** [review]
Not sure why the build failed, maybe a time-out.

**Comment by Dodo-s95** [comment]
@mjpost it failed again :/

**Comment by akoehn** [comment]
I restarted it, let's see whether it works now.

**Comment by Dodo-s95** [comment]
@mjpost @akoehn Thanks for your help!

**Pull request merged**
