### PR TITLE
Add citation button

### PR DESCRIPTION
**Pull request by mjpost**
Adds a citation button per #412.

### CODE REVIEW

**Comment by mjpost** [comment]
Here is what this looks like:

image

Clicking "Copy Citation" gives

```
[Improving Word Sense Disambiguation in Neural Machine Translation with Sense Embeddings](https://www.aclweb.org/anthology/W17-4702) (Rios Gonzales, Mascarell, & Sennrich, WMT 2017)
```

A note about how the venue acronym is computed: for 2020+, this is simple: the acronym can be looked up via the venue ID encoded in the paper's Anthology ID. Prior to 2020, we have two styles of IDs: those use "oldstyle letters" (which can similarly be looked up), and those using the "W" prefix. In that case, it's a bit trickier. I use the following heuristic. These events have the primary venue of the generic "WS", but often have joint associations with their real venue, e.g., WMT. So I look through all joint events, and return the acronym of the first such event that has no "oldstyle letter". This seems to work pretty well (including in the example).

One change I could make would be to omit the venue identifier entirely if it ends up as "WS", which is pretty meaningless.

We also do have some work cut out for us, associated some events that we were assigned "W" despite being long-running existing workshop or even conference venues.

**Comment by akoehn** [comment]
> ```
> [Improving Word Sense Disambiguation in Neural Machine Translation with Sense Embeddings](https://www.aclweb.org/anthology/W17-4702) (Rios Gonzales, Mascarell, & Sennrich, WMT 2017)
> ```

This is not what I would have expected clicking on that link.  I would
have guessed something like this (which is auto-generated by helm-bibtex
and not perfect):

```
- Vaswani, A., & Sagae, K. (2016). Efficient structured inference for
  transition-based parsing with neural networks and error
  states. Transactions of the Association for Computational Linguistics,
  4(), 183–196. http://dx.doi.org/10.1162/tacl_a_00092
```

What would the use of the format you are proposing be?

**Comment by mjpost** [comment]
Maybe what I have produced is better referred to as a (extended) "reference" or "reference string" or "citation string".

I think the use for both is that they're simple to include in text documents, say if you're collecting a list of papers you want to read. My proposal was a bit more compact and relatively easy to produce.

**Comment by mjpost** [comment]
How about this approach: a button at the top that just copies the summary text:

image

The icon formatting is off, I'd have to play with it. Here it is now:

```html
<button type=button class="btn btn-clipboard btn-secondary btn-sm d-none" data-toggle=tooltip title="Copy as markdown" data-clipboard-text="[Simulated multiple reference training improves low-resource machine translation](https://www.aclweb.org/anthology/2020.emnlp-main.7) (Khayrallah et al., EMNLP 2020)">
  <i class="far fa-clipboard pr-2"></i>
</button>
```

**Comment by mbollmann** [comment]
Re the formatting, remove this:

> ```
> pr-2
> ```

This is Bootstrap-speak for `p`adding `r`ight, size `2`.

- - -

I wonder if this would be more intuitive as a text field that *showed* you the text it was copying, and that copies it when you click on it. (I've seen this many times on the web, but when I want to link to an example I can't find one, of course...)

**Comment by nschneid** [comment]
Another option would be to provide a short citation field above "PDF:". For many purposes it's sufficient to copy directly off the page and paste as rich text (preserving links).

**Comment by nschneid** [comment]
I.e.
image

**Comment by akoehn** [comment]
The preview looks very broken -- no citation possibilities at all anymore.

**Comment by mjpost** [comment]
This may be because we don't generate bib and other secondary files for previews. Maybe we should change that.

**Comment by mbollmann** [comment]
Yeah, I was wondering about that. I also wanted to look into implementing the options we discussed in #412, but they'd probably also rely on the bibliography files being there.

**Comment by mjpost** [comment]
Let's change it. Not at terminal but it's a quick fix to the "preview" target in the Makefile.￼

**Comment by mjpost** [comment]
Superseded by (nicer work in) #1375.

**Pull request closed without merging**
