### PR TITLE
Fix abstract in 2022.emnlp-main.62

### PR DESCRIPTION
**Pull request by jpwahle**
Updating EMNLP 2022 abstract of paper 62 "How Large Language Models are Transforming Machine-Paraphrase Plagiarism".

The abstract did not have spaces after the punctuation mark which were added.

No other paper was edited.

@mjpost I would kindly ask you for a review. Thanks!

### CODE REVIEW

**Comment by mjpost** [comment]
Over 11k lines were changed and Github won't show me the diff. Perhaps you changed the new lines or some other formatting? Please fix this and then I can review and merge.

**Comment by jpwahle** [comment]
Thanks for your prompt response. This seems to be an [issue GitHub has](https://stackoverflow.com/questions/19593909/git-diff-sees-whole-file-as-changed-when-its-not) with diffs of XML files.

You can verify this locally as described in StackOverflow or open VSCode. Here is a screenshot.

Screenshot 2023-06-02 at 08 35 37

**Comment by mbollmann** [comment]
@jpwahle It's an issue with the newlines, as described in an answer to the StackOverflow post you linked. Our files have LF newlines (Unix-style), while your changed file has CRLF newlines (Windows-style). If we merge it like this, our git history for this file will become useless, as it will show every line as changed by you.

**Comment by jpwahle** [comment]
You are right @mbollmann , thanks!

I updated the commit and it reflects the changes now in GitHub diff too.

**Review by mjpost — APPROVED** [review]
LGTM.

**Comment by jpwahle** [comment]
Great, thanks for the fast review @mjpost and @mbollmann.

What is the timeline for the merge, do you have periodic release intervals?

**Comment by mjpost** [comment]
When users submit their own fixes, we merge them right away. Thanks for the PR!

**Comment by jpwahle** [comment]
Awesome, thanks!

**Pull request merged**
