### PR TITLE
Add [RETRACTED] to titles of retracted papers

### PR DESCRIPTION
**Pull request by mjpost**
This was added at the suggestion of Google Scholar folks to reflect the practice used by many other publications: "Publishers using this approach include: ScienceDirect, SpringerNature, Taylor & Francis, Wiley, OUP, SAGE, ACM, and others."

### CODE REVIEW

**Comment by mbollmann** [comment]
Shouldn't we do this in the code, rather than the metadata? This would duplicate information, since there's already a `<retracted>` tag.

**Comment by mjpost** [comment]
It is a little redundant with the title, but it was also a lot easier to just change the title than to change every downstream display of the title. It also makes it harder to miss, even when looking through the XML. As a result I'm okay with this small amount of redundancy.

**Comment by mbollmann** [comment]
I would expect that there only needs to be a single change in the code: right at the source where the `<title>` tag is read. But maybe we can also consider this for the new library instead, and use your solution for now.

**Comment by mjpost** [comment]
I'm open to your suggestion, which seems easy enough. Is the site generation currently using your module, or the old code under `bin/anthology`?

**Comment by mbollmann** [comment]
Old code

**Pull request merged**
