### PR TITLE
Check pr with gh

### PR DESCRIPTION
**Pull request by akoehn**
By popular demand.

Tested it on my clone, see https://github.com/akoehn/acl-anthology/pull/1

### CODE REVIEW

**Comment by mjpost** [comment]
Drat, still there.

**Comment by akoehn** [comment]
@mjpost It still tries to run travis :-(  Maybe travis checks the content of the master branch?

**Comment by akoehn** [comment]
Can't you disable the check-needed thing for a minute and we merge this one?

**Comment by mjpost** [comment]
Hmm, before, I turned off the webhook. Now I turned off the requirement. But it seems once again not to apply to existing PRs.

image

**Comment by mjpost** [comment]
Oh, it's gone!

**Comment by akoehn** [comment]
Lol, your dummy commit broke the end-of-file check! I'll close this PR and reopen the original #1443

**Pull request closed without merging**
