### PR TITLE
removed nonexistent DOI

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by knmnyn** [comment]
Hi all:

Under our legacy addressing scheme,

- YXX-[1-9]000 or WXX-[01-99]00 should resolve to the frontmatter of the
same conference or workshop.
- YXX-[1-9] / WXX-[01-99] should resolve to the full volume of the
conference or workshop.  Usually this would also contain the frontmatter
and author index (if any)

Hope that clarifies!  Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by mjpost** [comment]
The issue is that we don't redirect volumes URLS of the form

> aclweb.org/anthology/P17-1

to their proper locations at

> aclweb.org/anthology/volumes/P17-1

Which is what causes this to fail.

I could add a redirect rule instead if we think that's appropriate for volumes. I also have not been assigning DOIs for frontmatter or volumes lately; perhaps I should fix that.

**Comment by mbollmann** [comment]
Can't the DOI be changed to point to the `volumes/P17-1` URL? (I have no idea how this works tbh.)

**Comment by mjpost** [comment]
We could update it. There are a number of other ones, so it should be done thoroughly. A spot-check turned up

- https://www.aclweb.org/anthology/volumes/P14-1/
- https://www.aclweb.org/anthology/P14-1000/ (links to same)
- https://www.aclweb.org/anthology/volumes/P16-1/

etc.

**Comment by mjpost** [comment]
The next time I assign DOIs I'll deal with this (if I remember).

**Comment by akoehn** [comment]
Is this still an active PR or should we close it and add an issue to track old DOI generation?

**Comment by mjpost** [comment]
Yes, let's close this. I'll create an issue.

**Pull request closed without merging**
