### PR TITLE
added LiLT and CCL to the front page

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Review by akoehn — APPROVED** [review]
Isn't there a less year-dependent url for CCL than
http://cips-cl.org/static/CCL2020/index.html
?

**Comment by mjpost** [comment]
Hmm, maybe [here](http://cips-cl.org). Too late to slip it in...

**Comment by akoehn** [comment]
Open an issue and tag someone who knows Chinese? I'm not completely sure what the best site is.

**Comment by davidweichiang** [comment]
Or http://cips-cl.org/webmirror, which lists CIPS's conferences (CCL is the main one, but not the only one).

**Comment by davidweichiang** [comment]
Or http://cips-cl.org/anthology, which are the proceedings.

**Pull request merged**
