### PR TITLE
Blog post announcing new metadata workflow

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Review by mbollmann — APPROVED** [review]

**Comment by mbollmann** [comment]
@mjpost Should we announce this on Bsky and Twitter, or wait until next year?

**Comment by nschneid** [comment]
Maybe hold off until we figure out some policy issues with the current corrections.

**Comment by mjpost** [comment]
Yes, let's work out all the kinks and then we can do a coordinated announcement. I'm mostly offline today (traveling) but hope to address outstanding issues by tomorrow. If you could slow down with all the huge feature improvements it would help :)

**Comment by mbollmann** [comment]
We still haven’t announced this publicly, even though many people have interacted with it by now. I wonder if we should update the blog post to explain the difference between fixing author and paper metadata maybe, and then finally post on socials about this too.

**Comment by nschneid** [comment]
Good idea. Possible text:

> Paper pages as well as author pages now have a yellow "Fix data" button that will guide you through creating a structured GitHub issue. The issues will be reviewed by Anthology staff, who may ask for changes. Approved changes will be incorporated into the database on a regular cycle (approximately weekly).
> 
> ### Which kind of fix should I choose?
> 
> The golden rule of the ACL Anthology is that **the contents of the PDF are considered authoritative**. So if you see errors or inconsistencies in metadata (title, authors, abstract), you need to start by checking the associated paper PDF(s).
> 
> ☞ If there is **an error in the PDF** (e.g. a typo in an author's name), you need to submit a revision to the paper.
>
> ☞ If **the metadata for one or more papers doesn't match the PDF**, please use the paper page "Fix data" button to correct it for each individual paper. This is commonly caused by author middle names/initials being included in OpenReview/SoftConf profiles but not the PDF, or vice versa. (In which case, please also fix your profile on those platforms so it will be correct for future publications!) Another common problem is that for an author name written with multiple spaces, the split between first and last names may be incorrect, leading to bibliography errors. When you submit a paper correction, please ensure that *all* authors' names match the PDF.
>
> ☞ Author pages are autogenerated based on paper-level metadata. Where necessary, it is possible to record explicitly that an individual uses multiple name variants or to distinguish multiple authors with the same name. If an author has published under **different names** on different papers, has permanently **changed their name**, or is being incorrectly grouped on an author page with **another individual with the same name**, use the author page "Fix data" button to report this.

**Comment by mjpost** [comment]
@nschneid Thanks for this draft! Do you intend it for [the blog post](https://aclanthology.org/posts/2024-12-27-new-metadata-workflow/) or for the top of [the corrections page](https://aclanthology.org/info/corrections/)?

**Comment by nschneid** [comment]
Whatever you think is best

**Comment by nschneid** [comment]
(added a bit about diacritics)

**Comment by mjpost** [comment]
Incorporated a bunch of this into #4223. It took longer than I thought, so I may have rushed at the end, please feel free to suggest / make changes.

**Pull request merged**
