### PR TITLE
Add missing WS venues

### PR DESCRIPTION
**Pull request by GuyAglionby**
I noticed that a few workshops weren't associated with the venue created for that workshop series -- this PR addresses that. I've manually verified the suggested changes.

There were a couple of duplicated venues: CNewsStory/CNS and Ethics-NLP/EthNLP both appear to refer to the same venues respectively, so I merged them. The same appears to be true for CoSLI and COSLI, but the latter is tagged as non-ACL and the former as ACL and I wasn't completely sure which was the case (ACL, I think?).

### CODE REVIEW

**Comment by mjpost** [comment]
This is awesome, thank you! We have been mostly offline for the holidays, as you've probably guessed, but one of us will review this within the next few days, I expect.

**Comment by GuyAglionby** [comment]
Of course! No worries and no rush

**Comment by mjpost** [comment]
Okay, I spot-checked a number of these and they look correct.

I couldn't figure out whether CoSLI is ACL or non-ACL, but sent an inquiry.

I'll merge in a day or two, in case I get a response.

**Comment by mjpost** [comment]
It looks like CoSLI 2013 was ACL, so maybe we can combine them as ACL.

Moving forward, I think making the ACL/non-ACL distinction at the venue level is too coarse.

**Comment by GuyAglionby** [comment]
Sounds good, have removed the duplicate. Only one venue uses it (W13-07) and I've checked that the chosen capitalisation (CoSLI) matches.

**Comment by mjpost** [comment]
Hmm, so COSLI was entirely unused?

**Comment by GuyAglionby** [comment]
Doesn't look like it. COSLI was added [here](https://github.com/acl-org/acl-anthology/commit/fc1e78561701cc453513a9dd3e7388066cda916f) with no associated volume. For reference, CoSLI was added [here](https://github.com/acl-org/acl-anthology/commit/cfd4f848241d311baf77d45a2d0e1dcf547576ad).

**Comment by mjpost** [comment]
Thanks so much for the contribution! Should be live within the hour.

**Comment by GuyAglionby** [comment]
No problem! I'm happy to do similar for others, if appropriate (cf #721). Not a problem if not

**Pull request merged**
