### PR TITLE
Authorship Correction in the .bib 

### PR DESCRIPTION
**Pull request by andyweizhao**
Hi Matt, 

Thanks. We would like to correct the .bib file to reflect the order in the paper, and we just submitted an pull request with corrected authorship. Refer to the issue: https://github.com/acl-org/acl-anthology/issues/100. 

The link you mentioned is not corrected, which is https://github.com/acl-org/acl-anthology/blob/918dcc4dba25f07c09fe0807e3f6adbb8d589c6d/import/D18.xml#L5983.

Best,
Wei

### CODE REVIEW

**Comment by mjpost** [comment]
This author order (Zhao Zhang Ye...) is different from the PDF (Zhao Ye Zhang).

**Comment by andyweizhao** [comment]
Thank you for the reminder. Yes, I am issuing an new pull request. Sorry for this.

**Comment by mjpost** [comment]
No, please just edit this one. If you push to your master branch, this will be updated.

**Comment by andyweizhao** [comment]
Yep. Thanks.

**Comment by andyweizhao** [comment]
Cool. Thanks for your help!

**Pull request merged**
