### PR TITLE
sigdial-2022-ingestion

### PR DESCRIPTION
**Pull request by xinru1414**

### CODE REVIEW

**Comment by xinru1414** [comment]
@mjpost the preview job has been failing frequently for the most recent several ingestions (COLING, CCL etc). I couldn't find the error by looking through the log. Any idea why this is happening? I've been fixing by simply re-run the preview job.

**Comment by mbollmann** [comment]
Looks like Hugo just gets killed, so we might be starting to hit either a memory limit or runtime limit?

**Comment by mjpost** [comment]
We're using a very old version of hugo (0.58.3). We should upgrade that. It seems hugo also has a way to test how efficient our build process is: https://gohugo.io/troubleshooting/build-performance/

**Review by mjpost — APPROVED** [review]

**Comment by xinru1414** [comment]
@mbollmann @mjpost noted. thanks!

**Pull request merged**
