### PR TITLE
Processed revisions to many papers

### PR DESCRIPTION
**Pull request by mjpost**

### CODE REVIEW

**Comment by mjpost** [comment]
All right, I added a few more.

The `add_revision.py` script was updated to

*  Use the correct directory for storing PDFs (it's flatter for new-style IDs)
*  Correctly download, rename, and compute the hash on the original file, when processing the first revision (id 2)

**Comment by mjpost** [comment]
I also documented this [here](https://github.com/acl-org/acl-anthology/wiki/Processing-revisions-and-errata).

**Comment by akoehn** [comment]
I only checked one paper, but there the v1 pdf URL serves is the html page and not the original pdf (which is still available under D19-1225.pdf).

 - D19-1225.pdf -> new pdf
 - D19-1225v1.pdf -> D19-1225/index.html
 - D19-1225v2.pdf -> new pdf

**Comment by mjpost** [comment]
@akoehn thanks for your diligence here. I have restored the v1 PDFs and the checksums, but now realize that we also have to update the checksums on the `<url>` tags.

There is too much complexity and consequent room for user (director :)) error in this process. I am going to create a new issue because we should raise this item for internal discussion.

**Comment by mjpost** [comment]
They were, but the rewrite rules didn't handle them. Fixed.

**Comment by mjpost** [comment]
Possibly ready now...

**Pull request merged**
