### PR TITLE
ingestion: rocling 2023

### PR DESCRIPTION
**Pull request by anthology-assist**

### CODE REVIEW

**Review by mjpost — APPROVED** [review]

**Comment by ouartz99** [comment]
Dear Anthology Director and  anthology-assist,

Thank you very much for the assistance.

We found some issues with the preview version.

1、The bib (full) link is 404 (Bib Export formats)
2、Most paper without export BibTex button
3、There are errors present in specific paper author rankings or author links, as detailed below:

●Story Co-telling Dialogue Generation via Reinforcement Learning and Knowledge Graph

●Improving End-to-end Taiwanese-Speech-to-Chinese-Text Translation by Semi-supervised Learning

●Construction of Message Deliver Service Dialog Systems

●Improving Low-Resource Speech Recognition through Multilingual Fine-Tuning with Language Identifiers and Self-Training

●Is GPT-4 a Good Islamic Expert for Answering Quran Questions?

●Fine-Tuning and Evaluation of Question Generation for Slovak Language

●Sentence-level Revision with Neural Reinforcement Learning

●KNOT-MCTS: An Effective Approach to Addressing Hallucinations in Generative Language Modeling for Question Answering

●Fine-Grained Argument Understanding with BERT Ensemble Techniques: A Deep Dive into Financial Sentiment Analysis

●The NTNU Super Monster Team (SPMT) system for the Formosa Speech Recognition Challenge 2023 - Hakka ASR

Thank you very much

**Comment by mjpost** [comment]
We do not generate all BibTeX files for the previews.

The authors are incorrect because the data you provided was not formatted correctly. Please fix your data and resubmit.

**Comment by ouartz99** [comment]
Dear Anthology Director and anthology-assist,

I am so sorry about the mistake in my provided data. I have double-checked all the BibTeX files to ensure the format is correct. All new BibTeX files and proceedings PDF file are uploaded to the following URL:

https://drive.google.com/drive/folders/1V6gEXEaOLquvKzc0cb8No_fNEcVW5Gf2?usp=drive_link

Thank you very much for the assistance again.

**Comment by ouartz99** [comment]
Dear Anthology Director and Xinru,

Thank you for your reply and provided the XML file.

I am modifying the author's information on line 3441 of the XML file (attached file).

And some of the BibTeX files need help replaced with new ones.
2023.rocling-1.2.bib
2023.rocling-1.3.bib
2023.rocling-1.4.bib
2023.rocling-1.8.bib
2023.rocling-1.15.bib
2023.rocling-1.20.bib
2023.rocling-1.24.bib
2023.rocling-1.26.bib
2023.rocling-1.30.bib
2023.rocling-1.55.bib

New BibTeX (https://drive.google.com/drive/folders/1_8G6gJyrMWHnhclzPtfx3tZkbsyX_LoU?usp=drive_link)

As for PDF files, we add footers to each paper. Could you help me replace all of the PDFs with new PDF files?

(https://drive.google.com/drive/folders/1HfyS8u9ViARrL5BfV40Mcla7Ceb5ahbf?usp=drive_link)

Thank you so much

Best regards,

Dr. Hou-Chiang Tseng




[2023.rocling.zip](https://github.com/acl-org/acl-anthology/files/13295114/2023.rocling.zip)

**Comment by mbollmann** [comment]
@ouartz99 We do not store any BibTeX files directly; all of our BibTeX files are generated automatically from the XML. Therefore, all changes that affect BibTeX files need to made directly in the XML.

**Comment by ouartz99** [comment]
@mbollmann  Thanks for the explanation.

I am do my best to modify the author's information on line 3441 of the XML file. 

I hope all the information can be corrected.

Thank you very much for the assistance.

**Comment by mbollmann** [comment]
@ouartz99 The file you attached does not appear to contain the XML file; it looks like a web page of some sort.

Also, you mentioned ten different BibTeX files that should be replaced — so I would expect changes in the XML file for each of these papers, i.e., more than just one line.

So what exactly is it that should be corrected, and how?

**Comment by ouartz99** [comment]
@mbollmann The file "2023.rocling.xml" was provided by Dr. Matt Post, and I only got this file. I modified the file with ten papers' author's information on line 3441 of the XML file. (The string is very long).
You can download  the "2023.rocling.xml" as following "https://drive.google.com/file/d/1m3ftt9xB_Hy3D-AasrhiO4ww657jFugW/view?usp=drive_link"

If I need to correct the author's information, Could you teach me how to make this right?


The paper title: "Story Co-telling Dialogue Generation via Reinforcement Learning and Knowledge Graph". The author's information

Chia-Hui Chang Yu-Kai Lee   →  Yu-Kai Lee | Chia-Hui Chang

==================================================================================
The paper title:  "Improving End-to-end Taiwanese-Speech-to-Chinese-Text Translation by Semi-supervised Learning".  The author's information

Chung-Che Wang Yu-Chun Lin | Jyh-Shing Jang  →   Yu-Chun Lin | Chung-Che Wang | Jyh-Shing Roger Jang

==================================================================================
The paper title: "Construction of Message Deliver Service Dialog Systems". The author's information

Chia-Hui Chang Cheng-Hung Yeh  →   Cheng-Hung Yeh | Chia-Hui Chang

==================================================================================
The paper title:  "Improving Low-Resource Speech Recognition through Multilingual Fine-Tuning with Language Identifiers and Self-Training".  The author's information

Michal Ptaszynski Karol Nowakowski  →   Karol Nowakowski | Michal Ptaszynski

==================================================================================
The paper title:  "Is GPT-4 a Good Islamic Expert for Answering Quran Questions?" .  The author's information

Eric Atwell Sarah Alnefaie | Mohammad Ammar Alsalka   →   Sarah Alnefaie | Eric Atwell | Mohammad Ammar Alsalka


==================================================================================The paper title:  "Fine-Tuning and Evaluation of Question Generation for Slovak Language" .  The author's information

Ondrej Megela | Ján Staš Daniel Hladek, Matus Pleva | Ming-Hsiang Su | Yuan-Fu Liao  →   Ondrej Megela | Daniel Hladek | Matus Pleva | Ján Staš | Ming-Hsiang Su | Yuan-Fu Liao

==================================================================================
The paper title:  "Sentence-level Revision with Neural Reinforcement Learning" .  The author's information

Kenji Hashimoto Zhendong Du  →   Zhendong Du | Kenji Hashimoto


==================================================================================
The paper title:  "KNOT-MCTS: An Effective Approach to Addressing Hallucinations in Generative Language Modeling for Question Answering".  The author's information

Chung-Wen Wu | Guan-Tang Huang | Berlin Chen Yue-Yang He    →    Chung-Wen Wu | Guan-Tang Huang | Yue-Yang He | Berlin Chen

==================================================================================
The paper title:  "Fine-Grained Argument Understanding with BERT Ensemble Techniques: A Deep Dive into Financial Sentiment Analysis".  The author's information

Eugene Sy | Tzu-Cheng Peng | Shih-Hsuan Huang | Yung-Chun Chang Heng-Yu Lin    →    Eugene Sy | Tzu-Cheng Peng | Shih-Hsuan Huang | Heng-Yu Lin | Yung-Chun Chang

==================================================================================
The paper title:  "The NTNU Super Monster Team (SPMT) system for the Formosa Speech Recognition Challenge 2023 - Hakka ASR".  The author's information

Tzu-Ting Yang | Hsin Wei Wang | Berlin Chen Meng-Ting Tsai    →    Tzu-Ting Yang | Hsin-Wei Wang | Meng-Ting Tsai | Berlin Chen

**Comment by mjpost** [comment]
I did not describe this in enough detail. We don't use the BibTeX except for ingestion; after ingestion, we generate our own BibTeX. This is done from the XML file I pointed you to. So we need to correct those errors. This should be apparent from the structure of the XML (find the paper with the corresponding ID, and break the name apart into `<first>` and `<last>` segments). If you are not familiar with Github, perhaps you have a colleague who is, and who could help you to create a new pull request?

As for the PDFs, can you describe what has changed with them, that they need to be updated? The reason I ask is to decide whether we can just fix them, or whether they need to go through the [revision process](https://aclanthology.org/info/corrections/).

**Comment by ouartz99** [comment]
Dear Anthology Director and Xinru,

I copied the original XML code and modified it again.  Could you help again? Thank you so much.

https://github.com/acl-org/acl-anthology/pull/2875

As for PDF files, we add footers to each paper. Could you help me replace all of the PDFs with new PDF files?

(https://drive.google.com/drive/folders/1HfyS8u9ViARrL5BfV40Mcla7Ceb5ahbf?usp=drive_link)

Thank you so much

Best regards,

Dr. Hou-Chiang Tseng

**Comment by mjpost** [comment]
@anthology-assist can you look at these PDFs and characterize their differences?

**Comment by ouartz99** [comment]
Dear Anthology Director,

The current version of the PDFs (2023.rocling-1.1.pdf to 2023.rocling-1.56.pdf) has no page number.

So I am adding the page number 2023.rocling-1.1.pdf to 2023.rocling-1.56.pdf (https://drive.google.com/drive/folders/1HfyS8u9ViARrL5BfV40Mcla7Ceb5ahbf)

Thank you very much.

Best regards,

Hou-Chiang Tseng

**Comment by ouartz99** [comment]
Dear @mjpost  and @anthology-assist 

Is there anything else I need to process about replacing PDFs with new versions? If so, please let me know.

Thanks for your help.

Best regards,

Hou-Chiang Tseng

**Pull request merged**
