### PR TITLE
scil 2023 ingestion

### PR DESCRIPTION
**Pull request by anthology-assist**

### CODE REVIEW

**Comment by mjpost** [comment]
PDFs are not right, e.g., these don't match:
* https://preview.aclanthology.org/scil-23-ingestion/2023.scil-1.30
* https://preview.aclanthology.org/scil-23-ingestion/2023.scil-1.30.pdf

**Comment by blprickett** [comment]
Sorry about that mismatch--should be fixed in this new version.
[data.zip](https://github.com/acl-org/acl-anthology/files/12806279/data.zip)

**Comment by mjpost** [comment]
@anthology-assist The PDFs still don't match. Did you re-upload the PDFs? Please test the last one, a random one in the middle, and the first one.

**Comment by mjpost** [comment]
The one I pointed out before also still does not match.

**Comment by blprickett** [comment]
Sorry again--it looks like I had fixed the problem in one spot but missed another. Just double checked the version at this link and I think it should be good:

https://drive.google.com/file/d/1ql9hhVz4IAZxb7Chh453E3vksgGapCCq/view?usp=sharing

**Comment by mjpost** [comment]
@blprickett before we go through the ingestion again can you please go through these and manually validate them (or at least a large sample of them)?

**Comment by blprickett** [comment]
> @blprickett before we go through the ingestion again can you please go through these and manually validate them (or at least a large sample of them)?

Just finished triple checking a large proportion of them by hand. Didn't see any differences between the .bib files and the PDFs in the most recent link I sent (https://drive.google.com/file/d/1ql9hhVz4IAZxb7Chh453E3vksgGapCCq/view?usp=sharing).

**Comment by mjpost** [comment]
Okay, thank you. @anthology-assist, please re-ingest and re-upload the PDFs when you have a minute.

**Review by mjpost — APPROVED** [review]
LGTM, thanks, everyone!

**Pull request merged**
