### PR TITLE
added 3/4 INLG workshops

### PR DESCRIPTION
**Pull request by mjpost**
The other workshop cannot be located.

@davidweichiang, can you advise me on the new process for doing title correction and name checking? What scripts should I run? Now that I have some actual test data, once I have that, I'll incorporate them into the ingestion process and the documentation.

### CODE REVIEW

**Comment by davidweichiang** [comment]
For titles, nothing has changed. The stuff I did recently was specifically for titles in all caps, and that is extremely rare nowadays. For author names, you would use `author_case.py`.

**Comment by mjpost** [comment]
Can someone take a look at this? It just adds workshops (the fourth one is likely not coming), and updates some scripts to be more efficient. @acl-org/anthology

**Comment by burtenshaw** [comment]
@mjpost 

Hi Matt, I'm on the organising committee of the fourth workshop (CCNLG). I submitted the parsed proceedings via email, and have been chasing up their publication.

Could I submit proceedings directly?

**Comment by mjpost** [comment]
Hi @burtenshaw—I'm not sure what you mean by directly—I suggest you follow the instructions here: https://github.com/acl-org/ACLPUB/tree/master/anthology.

**Pull request merged**
