### PR TITLE
Add Github link to navbar

### PR DESCRIPTION
**Pull request by mbollmann**
I propose to add a prominent link to our Github repo to the website's navbar, in order to make it easier to discover.

We could make a button on the front page as well (analogous to the BibTeX download buttons), but I thought this would be nicer.

### CODE REVIEW

**Comment by mjpost** [comment]
Good idea. To discuss: is "Find us on Github" too verbose? Maybe just the text "Github" (with the icon)? I'm fine either way. We could always shorten. later.

**Review by mjpost — APPROVED** [review]

**Comment by akoehn** [comment]
I would also shorten it, the current version does not wrap nicely on smaller screens.

**Comment by mjpost** [comment]
I hope you don't mind that I overloaded this PR with some changes to the FAQ, per a private email thread.

**Comment by mbollmann** [comment]
> I would also shorten it, the current version does not wrap nicely on smaller screens.

Ah! In my testing it always collapsed the entire nav bar before it got too cramped.

(That's also why I made the "ACL Anthology" type always stay visible now. It only disappeared for me when the nav bar was collapsed anyway, leaving lots of empty space.)

**Comment by akoehn** [comment]
I used the forged desktop mode on mobile, maybe it was an artifact of that.

The faq changes look good @mjpost

**Pull request merged**
