### PR TITLE
Adding Papers with Code integration

### PR DESCRIPTION
**Pull request by rstojnic**
Adding integration with metadata on Papers with Code (PWC - paperswithcode.com). 

The `bin/ingest_pwc.py` script is used to fetch the metadata from PWC API and merge it into `data/xml` files. This is done in a way that preserves the formatting of the original XML file and just adds the two extra fields from PWC. These changes can be committed directly into the github repo and except for running this command there is no other change to the build workflow. The data merge itself is very fast (<10s). 

What's missing from the PR is the cronjob to do a regular pull from PWC. The regular cronjob would need to do the following:

```
python3 bin/ingest_pwc.py
git add data/xml/*
git commit -m "Update metadata from Papers with Code"
git push
```

This could be run either daily, or if ends up generating a lot of commits, weekly. This could be achieved by using GitHub Actions or by some other way - suggestions are welcome!

Here is a screenshot of how it looks like on an example page (2020.acl-main.525):

Screen Shot 2021-11-05 at 9 27 25 AM

### CODE REVIEW

**Comment by mjpost** [comment]
I enabled the checks. If you run "make autofix" and commit the changes, it should fix the build.

I'm going to get you added to the Anthology team so you can push directly to a local branch, which will cause a preview to be built.

**Comment by rstojnic** [comment]
Thanks @mjpost - I've run autofix so hopefully that should fix the formatting in 28f3deb.

**Comment by mjpost** [comment]
@rstojnic from a quick pass over, this looks fantastic. I just added you as a member of the Anthology team. Do you want to update this PR to push directly to the `pwc` branch? That will cause a preview to be built at `https://preview.aclanthology.org/pwc`.

**Comment by mjpost** [comment]
I'm actually not sure it's possible to update a PR like that. Ideally we could so we'd have this history here, but I created a separate one so we'll have the preview.

**Comment by mbollmann** [comment]
Thanks @rstojnic, great work!

I've made an update to the XML schema that was required for the new tags, and created a suggestion for a GitHub action that we could use to automate updates, over in #1640.

**Comment by mbollmann** [comment]
Regarding the "Add Code" button:

I think it's fine to have a link like that, but with the current proposal, the "Add Code" button is just as prominent as the "Code" button. That makes it harder to distinguish at a glance between papers that have code and those that don't. I would suggest moving the "Add Code" button to the code line at the bottom, and not show it on the right-hand side.

Also, I wonder if we also want to display a PwC button on the events pages, maybe like this (just a quick mockup):
grafik

**Comment by mjpost** [comment]
+1 on adding the button to the paper listing pages.

I like the idea of the “Add code” button but agree it shouldn’t have a prominent spot on the right. But this fits in with a feature that’s missing on paper pages, which is links to general information about how to correct or augment data on each page. What if put all this in a paper page footer, with links to the correction policy, how to associate code with the page, and also at some point how to upload slides? This latter issue is a larger one that needs a bit of reworking, including getting submitters to sign an indemnification form, and should be managed by a dynamic content site, perhaps similar to what PWC is doing (otherwise it creates too much manual work for Anthology staff).

**Comment by rstojnic** [comment]
Thanks @mbollmann @mjpost ! 

Agreed - having a unified way to modify metadata would make more sense than having individual "add/edit" buttons for each of the separate artefacts (code, data, videos, etc). So for now I've just removed the "Add code" button and perhaps you could re-add the link in a more appropriate place later. I think the footer is probably a good place to do this. 

Thanks for the suggestion of adding the PWC icons to the list pages - I've now done this in 439f493 and c2c596a. I've also added custom icons for gitlab (e.g. see 2021.wanlp-1.9) and bitbucket (e.g. see 2020.socialnlp-1.6). 

Thanks for deploying the preview service - this is looking pretty good. I've also pushed my commits to that branch so it rebuild the preview. One thing I noticed in the preview is that the github icon is somehow corrupted and the spacing is not the same as just doing 'make' locally. 

E.g. compare the preview here: https://preview.aclanthology.org/pwc/2020.emnlp-main.5/ 

image

.. to just running `make` + `make serve` locally on the same `pwc` branch (that produces the correct SVGs and spacing):

image



Is there some additional post-processing step that might somehow corrupt SVGs in this way?

**Comment by mbollmann** [comment]
Hmm, I don't have an immediate explanation for that icon behavior. Do they differ in the generated HTML on the page? If not, it must be a CSS thing.

However, note that we're already including FontAwesome on all pages, so I think Github/Gitlab/Bitbucket icons could also be produced that way (`<i class="fab fa-github"></i>` etc.).

**Comment by rstojnic** [comment]
@mbollmann the SVGs in html and on the preview site are different. The one in the preview site is shorter, that's why I thought that maybe there is an additional step to try to optimize images. In any case, I'll try switching to FontAwesome icons, perhaps that's going to be the simplest fix.

**Comment by rstojnic** [comment]
It looks like cdd0cb7 solved the svg problem: https://preview.aclanthology.org/pwc/2020.emnlp-main.5/

**Comment by mjpost** [comment]
I just commented over on #1640. I think this is ready, but @rstojnic, can you pull from our `pwc` branch (in #1640) and also then merge the latest from our `master` branch?

**Review by mjpost — APPROVED** [review]

**Pull request merged**
