### PR TITLE
New ID format

### PR DESCRIPTION
**Pull request by mbollmann**
This PR enables the use of the new ID format (#291; e.g., `2020.acl-1.1`) in the Anthology.

**It is ready for discussion and testing, but contains a dummy file for testing (`data/xml/2020.test4nlp.xml`) that needs to be removed before merging.**

Notes:

1. For adapting the Python code, I chose the path of least resistance, which was to introduce `if/else` statements based on checking whether an ID is in old or new format. I think that ideally, the whole ID handling should be refactored into classes, so instead of slicing up strings and passing them around we could do:

   ```python
   x = Identifier.from_string("2020.acl-1.1")  # will work with both old and new format
   do_stuff(x.collection_id, x.paper_id)
   ```

   However, this is a way more complex change to the code base, so I prioritized getting things working first.

2. The venue handling is a mess. It's split up over multiple YAML files and has some assumptions about the old ID format baked in. I've now introduced yet another YAML file to handle new-style IDs – probably we should look into merging this.

   **We should probably discuss this here: #527**

3. I've not looked at any of the scripts in the repo other than those that are called for `make site`, so some of these scripts might potentially be broken.

### CODE REVIEW

**Comment by mjpost** [comment]
I pushed up some regexes for new files. I am going to simplify the format a little bit, putting files in

    /pdf/2020.acl/*

versus the old

    /pdf/P/P19/*

(i.e., removing subdirectories for years).

We do need to decide how to name revisions and errata. I am thinking of `2020.acl-1.1-v2.pdf` but I am not sure.

**Comment by mjpost** [comment]
Hi, are there any updates on this? Anything I can do to help push it along?

**Comment by mbollmann** [comment]
As I said, it's basically ready for review and testing, I'm mainly waiting for feedback on this. See my summary above.

The main question I can think of is point 2) above, i.e. whether we also want to tackle the venue handling right now.

**Comment by mjpost** [comment]
I built the site and it seems to work. I just merged in `master` and pushed up a change to the `.htaccess` file, which is live, and [works (test)](http://aclweb.org/anthology/2020.test4nlp-1.1.pdf). Contrary to what I wrote above, I am storing files as

> ~/anthology-files/pdf/test4nlp/*

(rather than adding another year-level subdirectory, since our file naming lets us sort).

I am in favor of fixing scripts as we encounter and have to deal with them.

One thing that also needs to be done is to modify ACLPUB with updated instructions. This may be tricky because Softconf will have to handle this even this year. Here is the current user interface:

image

I will have to test this, but I think the main user-facing changes are:

- The `abbreviation` field matters now, and needs to be consistent over years
- We no longer need `bib_url` with its sometimes-confusing string formatting syntax
- We *do* need to know the volume identifier (**see note below**)
- (Separately, we should add a "short title" field)

Requiring a volume number could get confusing since the volume numbers are meaningless to users. We may be removing one complication (`bib_url`) only to add another. Two solutions I see:

- We could infer them (e.g., volume 2 is the second ingested volume with the `acl` conference name in 2020). A downside is that unless we are careful, this could lead to ingesting a secondary volume (e.g., `srw`) before a primary one (e.g., long papers).
-  **I wonder if volumes should be permitted to be names**, e.g., `2020.acl-srw.1` for the student research workshop, `2020.acl-long.1` for long papers, etc. Along these lines, we could also allow forgoing the volume number entirely, for example for workshops that have only one volume. This could lead to e.g., `2020.test4nlp-1.pdf`, etc.

**Comment by mjpost** [comment]
An advantage that comes to mind with allowing text volume IDs is that one could quickly and easily find, say, the EMNLP tutorial abstracts, which would be at

> https://www.aclweb.org/anthology/volumes/2020-emnlp.tutorials

Instead of

> https://www.aclweb.org/anthology/volumes/D19-2/

(with different numbers every year).

**Comment by mbollmann** [comment]
Should the ACLPUB comments be in the ACLPUB team/repo instead? I don't know who's involved there, but I can't comment on these at all.

>     * **I wonder if volumes should be permitted to be names**, e.g., `2020.acl-srw.1` for the student research workshop, `2020.acl-long.1` for long papers, etc. Along these lines, we could also allow forgoing the volume number entirely, for example for workshops that have only one volume. This could lead to e.g., `2020.test4nlp-1.pdf`, etc.

One headache of this will be sorting. If we don't want `acl-demo` to appear before `acl-long`, for example, we'd need to introduce an additional YAML file or something that gives the sort order, and then implement sorting in the Hugo templates.

From a technical point of view, this should already work, I don't think the code specifically expects the volume ID to be a number. Allowing an empty volume ID would definitely require some refactoring.

**Comment by mjpost** [comment]
> One headache of this will be sorting. If we don't want acl-demo to appear before acl-long, for example, we'd need to introduce an additional YAML file or something that gives the sort order, and then implement sorting in the Hugo templates.

On this point, isn't it sufficient to just follow the volume order in the XML file? That way, we only have to ensure that we get the order right at ingestion time.

I am torn about making volumes optional in the ID. Arguments:

PRO:
- Many events have just a single volume, and having "2020.event-N" is prettier than "2020.event-1.N"

CON:
- IDs would no longer follow the hierarchical XML format (collection + volume + paper); instead, we'd need contextual information to know when not to use it (the context being whether the volume is the only volume)
- It wouldn't be clear from a file name, e.g., 2020.event-1.pdf whether it were (a) the PDF of the entire volume or (b) the PDF of the first paper of an event with only a single volume
- Parsing of IDs would therefore be more complicated

I therefore suggest that we:

- Require volume names, so the format is "year.event-volume.paper"
- Allow volumes names to match `([a-z][A-Z][0-9])+`

**Comment by mbollmann** [comment]
> On this point, isn't it sufficient to just follow the volume order in the XML file? That way, we only have to ensure that we get the order right at ingestion time.

That looks feasible. I've looked at the code, and it _might_ be as simple as removing the `sorted` wrapper from [a single line](https://github.com/acl-org/acl-anthology/blob/master/bin/create_hugo_yaml.py#L135). (Or rather, replacing it with `list`.) 

I can't get around to trying it at the moment, but if you have the time, you could try creating a dummy XML file that follows this convention, and try to run the pipeline after just making the change above.

> I therefore suggest that we:
> 
>     * Require volume names, so the format is "year.event-volume.paper"
> 
>     * Allow volumes names to match `([a-z][A-Z][0-9])+`

I agree. The cons seem like a pain to work with in practice.

**Comment by mbollmann** [comment]
> That looks feasible. I've looked at the code, and it _might_ be as simple as removing the `sorted` wrapper from [a single line](https://github.com/acl-org/acl-anthology/blob/master/bin/create_hugo_yaml.py#L135). (Or rather, replacing it with `list`.)

This seems to work as predicted; the website generates fine and places the volumes in the right order with the latest commits.

**Comment by akoehn** [comment]
What is the status of this; is there anything I can help with?

**Comment by mbollmann** [comment]
Testing and reviewing :)

(Note that since I also changed the front page to include 2020, we probably shouldn't merge this until we have our first ingestion from 2020, or temporarily revert this change again.)

**Comment by mjpost** [comment]
We do have IWCLUL (which met at the end of January) ready to proceed. I'll ingest that on top of this later today, and we can see how it looks.

**Comment by akoehn** [comment]
Tried it via #771. The only thing I noticed is that proceedings have an ID but their URL field is empty (in contrast to old proceedings).

Will have a look at the code later.

**Comment by mbollmann** [comment]
The main reason this is still a draft PR is that the dummy `test4nlp` is still in here. I'll remove the draft status after I remove that file.

Other than that, I'm happy to merge, but also happy to wait for @akoehn's code comments (if any).

**Comment by mjpost** [comment]
Awesome, sounds great.

Once you remove `test4nlp`, I'll rebase #771, so we'll have an actual 2020 conference.

**Comment by akoehn** [comment]
As stated, it would be nice to fix this:

> proceedings have an ID but their URL field is empty (in contrast to old proceedings).

I only had time for a short look through the code and that looked reasonable (if the cl and tacl special-casing is correct for upcoming publications). Don't wait for a more thorough code review from me.

**Comment by mjpost** [comment]
@akoehn can you post a screenshot or URL (to your localhost:8000 build is fine)? I don't quite understand, and my local build looks fine:

e.g., http://localhost:8000/anthology/volumes/W19-32/

image

**Comment by akoehn** [comment]
Look at the same for the 2020 test case. There they are empty.

**Comment by mjpost** [comment]
Thanks. This is because there is no entry for `test4nlp` in `data/yaml/venues.yaml`. This problem does not exist in #771, where I created entires for IWCLUL in both that file and `venue_mappings.yaml`. So that is the temporary solution.

image

I'd love to straighten out the venues situation, but maybe after we merge the new ID format (and #771)?

**Comment by akoehn** [comment]
Marcel, do it! :-)

**Comment by mbollmann** [comment]
On it!

> Look at the same for the 2020 test case. There they are empty.

Pretty sure the reason for this is that I didn't add a `<url>` entry to the `<meta>` block of the `2020.test4nlp.xml` file. Not every old-style proceedings volume has an URL entry either, e.g. https://www.aclweb.org/anthology/volumes/W19-01/

**Pull request merged**
