### PR TITLE
Correction to Anthology ID W19-8632

### PR DESCRIPTION
**Pull request by Franck-Dernoncourt**
- Fixed typo in author name: Nabah -> Naba.
- Added missing author to match the [PDF](https://www.aclweb.org/anthology/W19-8632.pdf).

### CODE REVIEW

**Comment by mjpost** [comment]
Thanks for the PR. Please see our [recently-enacted policy](https://www.aclweb.org/anthology/info/corrections/#note-on-author-changes) on name changes—we just need some confirmation from the workshop chair that this change to the list of authors is permitted.

**Comment by Franck-Dernoncourt** [comment]
@mjpost  Thanks I've emailed the workshop chair to get their permission. I'll keep you posted when they get back to me (or they might directly leave a message here).

**Comment by linron84** [comment]
Hi, adding Lidan Wang to the author list of the paper https://www.aclweb.org/anthology/W19-8632/  is fine to us. 

PC Chairs of INLG 2019
Kees van Deemter, Chenghua Lin and Hiroya Takamura

**Comment by mjpost** [comment]
Thanks. This will be merged with #977.

**Comment by Franck-Dernoncourt** [comment]
Thanks very much! By the way I've fixed the PR #939, it's ready to merge as well.

**Pull request closed without merging**
