### PR TITLE
Ingest tc 1988

### PR DESCRIPTION
**Pull request by davidstap**
See https://aclanthology.org/www.mt-archive.info/70/Aslib-1988-TOC.htm * for original.

* edit: updated link after copy-paste error

### CODE REVIEW

**Comment by xinru1414** [comment]
Couldn't find the corresponding link on the preview link @davidstap

**Comment by davidstap** [comment]
Whoops I made a copy-paste error. The correct link is -> https://aclanthology.org/www.mt-archive.info/70/Aslib-1988-TOC.htm

**Comment by xinru1414** [comment]
@davidstap @mjpost Is the subtitle `the translation environment 10 years on` supposed to be capitalized (first letter of each word)?

**Comment by mjpost** [comment]
Agreed that you should use Title Case consistently within any title. Also, the first word after a colon should be capitalized regardless ("The translation environment", also "From FAHQT to realism" later on)

**Comment by mjpost** [comment]
It looks like 1998.tc got merged on an earlier commit.

**Comment by davidstap** [comment]
Indeed, not sure how that happened.

**Pull request merged**
