### PR TITLE
ingested tc 2015

### PR DESCRIPTION
**Pull request by davidstap**
See https://aclanthology.org/www.mt-archive.info/15/Asling-2015-TOC.htm for original.

### CODE REVIEW

**Review by xinru1414 — APPROVED** [review]
Compared OG site and https://preview.aclanthology.org/ingest-tc-2015/events/tc-2015/#2015-tc-1

LGTM

**Comment by mjpost** [comment]
Can you add a name variant for "Will Lewis"? (There's an existing entry for William Lewis which is canonical)

**Comment by davidstap** [comment]
@mjpost I think I misunderstand, but I'm not sure where "Will Lewis" is coming from? There is a "William Lewis" in this proceedings, who is in fact "William D. Lewis". So all is good, right?

**Comment by mjpost** [comment]
Hmm, looking again, I’m not sure where my comment came from. This indeed looks good, thanks, David.

**Pull request merged**
