### PR TITLE
Update name_variants.yaml

### PR DESCRIPTION
**Pull request by mladenk42**
I added an entry into name_variants.yaml which should modify the vanity page of "Mladen Karan" to "Vanja M. Karan"

### CODE REVIEW

**Comment by mbollmann** [comment]
Thanks for the PR! Is this a pre-emptive measure for future publications, due to a recent name change? I am asking because I could not find any publications with the name "Vanja M. Karan".

**Comment by mladenk42** [comment]
Hi. Yes exactly, it's a pre-emptive measure.

**Comment by anthology-assist** [comment]
If it's pre-emptive, we will need to confirm that the new name is what's on the pdf. Please let us know once the paper is published.

**Comment by mladenk42** [comment]
Once what paper is published?
I'm requesting you to change the name on my existing papers.

I can send a picture of my old "Mladen Karan" id and my new "Vanja Karan"
id card, would that work?

Best
Vanja

**Comment by mjpost** [comment]
To clarify: this is not just preemptive, but is also a partial commit for a name change on existing PDFs. We can change the metadata for this PR, and update the PDFs (and their hashes) in a separate request.

**Comment by mjpost** [comment]
The diff here is huge. I'm not sure why, it's not locally.

**Comment by mjpost** [comment]
My only guess for the huge diff (136 miles) is that, with a remote PR like this, the diff doesn't update against the target branch (`master`), but only against the original checkpoint. If so, I'm not sure if this is by design or is a bug.

**Review by mjpost — APPROVED** [review]
The PR is massive (it shows 136 files changed), but locally, it is a much smaller subset, just the files that have affected papers. I am hoping the diff is just a bug.

**Pull request merged**
