### PR TITLE
add iwslt papers to sigslt; small fixes

### PR DESCRIPTION
**Pull request by esalesky**
Adds past IWSLT volumes to SIGSLT to facilitate finding past years and papers

Other small fixes:
- workshop -> conference in name (changed in 2016)
- adds is_acl (now true, venue of an ACL SIG and ACL co-located event)
- removes WS from IWSLT 2020 for consistency (this was the only year which listed IWSLT as a WS)
- fixes one misspelled author name in IWSLT 2014

### CODE REVIEW

**Comment by mjpost** [comment]
@esalesky can you merge in master and push up so that it will trigger a rebuild?

**Comment by esalesky** [comment]
merged master and pushed!

**Comment by esalesky** [comment]
Ah, I think because I am a first-time anthology contributor someone needs to approve the build?

**Comment by mjpost** [comment]
Done. 

But looks like your merge didn't get the latest master. And weird that the commits to master are showing up here. It should just be a single merge. Did you fetch first? (and can you redo to resolve the conflicts?)

**Comment by esalesky** [comment]
Resolved; there had been a few commits here after I merged in master which had caused a conflict.  
I had pulled locally and pushed to my fork so there was not a merge commit. I reset and fetch/merged instead.

**Review by mjpost — APPROVED** [review]

**Comment by mjpost** [comment]
Thanks for the PR!

**Pull request merged**
