### PR TITLE
C80-1084 title: German adjective shouldn't be fixed-case

### PR DESCRIPTION
**Pull request by nschneid**

### CODE REVIEW

**Comment by mjpost** [comment]
I'll leave this to @akoehn or @mbollmann, but it seems that none of the nouns here should be fixed case?

(also, while you're here, can you add a `<language>deu</language>` tag?)

**Comment by nschneid** [comment]
All German nouns are always capitalized (in edited text), ja? So they should be fixed-case (unless BibTeX has some magic German POS tagger I'm not aware of).

**Comment by mjpost** [comment]
Ah yes, you're right of course.

**Comment by akoehn** [comment]
There is no BibTeX magic, so the nouns should be fixed-case.  Bürgernahen is an adjective and should not be fixed-case. -> Agree with the PR.

**Review by mjpost — APPROVED** [review]

**Pull request merged**
