### PR TITLE
Use GitHub actions to publish the anthology.

### PR DESCRIPTION
**Pull request by akoehn**
Before merging:
@mjpost please add the secrets described in the README to the repository on github.

### CODE REVIEW

**Comment by mjpost** [comment]
Done.

**Comment by akoehn** [comment]
Okay, someone review it so I can merge it.

**Comment by akoehn** [comment]
An hour it is indeed; the rsync to the acl web server is quite slow.  But it seems to work without problems! Maybe we should run rsync without `-v` to have smaller logs.

**Comment by mjpost** [comment]
Not a bad idea on the rsync. I'm impressed this all came together so smoothly.

**Comment by akoehn** [comment]
It only looks smooth because I did all the testing on my fork.  Took me 19 commits to get it right because the GitHub actions documentation is at least underwhelming.

I failed to write an if statement(!) so that the action runs only if the secrets are defined because I could not figure out how to write a condition for that!

**Pull request merged**
