### PR TITLE
Add missing ACL 24 papers

### PR DESCRIPTION
**Pull request by mjpost**
Many papers were missed in the ingestion. This adds
- [x] Short papers
- [ ] Long papers

### CODE REVIEW

**Comment by akoehn** [comment]
Why did all these hashes change? Was the initial data changed for all these papers at some point in time?

**Comment by mjpost** [comment]
The volume title was changed (to add "Volume 2: Short Papers"), so all the footers changed.

**Review by akoehn — APPROVED** [review]
I did not check the checksums but I assume they are correct

**Comment by TheShayegh** [comment]
Here is a list I prepared: https://theshayegh.github.io/ACL2024MissingPapers/

**Comment by mjpost** [comment]
@TheShayegh thanks. ACL is still working on this actively and has the list in OR. I hope we will have this resolved soon.

**Pull request merged**
