### PR TITLE
ranlp-2021-ingestion

### PR DESCRIPTION
**Pull request by xinru1414**

### CODE REVIEW

**Comment by mjpost** [comment]
`ranlpstud` is not a new venue. This should be a volume named “srw” (Student Research Workshop) within the “ranlp” venue.

**Comment by mjpost** [comment]
Also probably best to merge in the `master` branch.

**Comment by mjpost** [comment]
I just merged in `master`, but the `ranlpstud` issue needs to be addressed yet.

**Comment by xinru1414** [comment]
@mjpost Let me know if I should change the volume from `1` to `main` for the main conf after adding `srw` volume

**Comment by mjpost** [comment]
Thanks, @xinru1414, I just did it myself a second now.

**Review by mjpost — APPROVED** [review]

**Pull request merged**
