### PR TITLE
SyntaxFest 2019, 2021, 2023: list syntaxfest as a venue alongside workshop name (#2417)

### PR DESCRIPTION
**Pull request by nschneid**

### CODE REVIEW

**Comment by nschneid** [comment]
https://preview.aclanthology.org/syntaxfest2019-venues/venues/syntaxfest/

**Comment by mjpost** [comment]
Thanks for the PR! It seems you added Windows carriage returns to all of W19.xml, can you fix that?

**Comment by nschneid** [comment]
I was wondering why I couldn't preview the diff of that file 😂

**Comment by mjpost** [comment]
Yeah I had to pull it down :) 

I notice sometimes you put the new venue first, sometimes second. Was there rhyme or reason to this? First is meant to be primary though I can't recall at the moment if there is any effect.

**Comment by nschneid** [comment]
Always putting syntaxfest second as it is the umbrella venue

**Review by mjpost — APPROVED** [review]

**Pull request merged**
