### PR TITLE
Add .htaccess

### PR DESCRIPTION
**Pull request by mbollmann**
Adds our own `.htaccess` to the repository, including some updates.

@mjpost, can you triple-check this actually works and does what the commits say it does on the server before merging?

### CODE REVIEW

**Comment by mjpost** [comment]
A difficult testing here is all the absolute URLs. I first tried just putting this in place in the live Anthology and it broke—none of the images loaded on the main page. I quickly reverted this and created https://www.aclweb.org/anthology-test/, but all the URLs and images and so on point to `/anthology`, making it hard to evaluate this.

The `https` redirect, however, doesn't work: http://www.aclweb.org/anthology-test/

**Comment by mjpost** [comment]
Also, don't we want the 404 line to read:

    ErrorDocument 404 /anthology/404.html

**Comment by mbollmann** [comment]
> The `https` redirect, however, doesn't work: http://www.aclweb.org/anthology-test/

Hmm, I suspect now that `https://%{SERVER_NAME}/$1` actually needs to read `https://%{SERVER_NAME}/anthology/$1` (or just `https://aclweb.org/anthology/$1` to sort out the canonical format at the same time).

Re the 404: I was under the assumption that this is relative to the current directory (as all the rewrite rules are), but I might be wrong -- didn't have a local Apache setup ready to verify...

**Comment by mjpost** [comment]
Those links are relative because they happen in the root. The 404 can occur anywhere. That fix fixes it.

Are you familiar enough with this that you can tell me the diff between these two lines?

    RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
    RewriteRule ^(.*)$ https://aclweb.org/anthology-test/$1 [R=301,L]

Doesn't the first one subsume the second?

I think I have this working, I'll push up the changes soon.

**Comment by mjpost** [comment]
Can you push this branch to acl-org/acl-anthology? I have a small update for it and then I can write to it.

**Comment by mbollmann** [comment]
> Are you familiar enough with this that you can tell me the diff between these two lines?
> 
> ```
> RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
> RewriteRule ^(.*)$ https://aclweb.org/anthology-test/$1 [R=301,L]
> ```
> Doesn't the first one subsume the second?

Since this `.htaccess` lives in `/anthology-test/`, I assume that `$1` will only contain the part that comes after that, so the first rule would mistakenly redirect to a URL without it. (e.g. `http://aclweb.org/anthology-test/foobar` would redirect to `https://aclweb.org/foobar`)

At least I'm inferring that from the fact other rewrite rules omit the `/anthology/` part as well.

**Comment by mjpost** [comment]
I asked that hoping to preserve this open PR, but realized you won't be able to update it, either. You can pull from the `htaccess` branch to get my update.

**Comment by mjpost** [comment]
I believe this is all working now. You can augment this PR by pulling from the `htaccess` branch here.

**Pull request merged**
