### PR TITLE
Update Q18.xml

### PR DESCRIPTION
**Pull request by aryamccarthy**
See discussion in #163

### CODE REVIEW

**Comment by aryamccarthy** [comment]
@anyone: review and pull when ready

**Comment by mjpost** [comment]
Sorry, can you merge in master? I just merged in a video commit which changed a few things.

**Comment by aryamccarthy** [comment]
done

**Comment by mjpost** [comment]
Oh, great. It looks like this corrected a lot of errors, too.

Where is the PDF bundle?

**Comment by mjpost** [comment]
See note in #163. Some of the paper IDs are wrong, and you should add in the script you wrote.

**Comment by aryamccarthy** [comment]
PDF bundle—mentioned in #163 that its location is [cs.jhu.edu/~arya/pdf.zip](here). Where should it go instead?

I don't see any erroneous paper IDs, after sampling a handful. Can you point me to them?

**Comment by mjpost** [comment]
See comment on 163. The paper IDs in the Anthology should be consecutive, but they jump from 1041 to 1240. Try `grep "<paper" data/xml/Q18.xml`.

**Pull request merged**
